flipt-io/flipt

Gopkg.lock, Gopkg.toml, vendor/github.com/sirupsen/logrus/entry.go, vendor/github.com/sirupsen/logrus/logger.go, vendor/github.com/sirupsen/logrus/logrus.go, vendor/github.com/sirupsen/logrus/terminal_check_aix.go, vendor/github.com/sirupsen/logrus/terminal_check_notappengine.go, vendor/github.com/sirupsen/logrus/text_formatter.go
=> Bump logrus to 1.3.0

.travis.yml, server/flag_test.go, server/rule_test.go, server/segment_test.go, storage/rule_test.go, storage/segment_test.go
Fixes #2 
Thanks @u5surf 
Closes #15
=> U5surf issue 2

docs/configuration.md, examples/auth/Caddyfile, examples/auth/README.md, examples/auth/docker-compose.yml
Adds example on how to configure HTTP Basic Auth using reverse proxy
=> Auth example

Gopkg.lock, Gopkg.toml, Makefile, proto/flipt.pb.go, proto/flipt.pb.gw.go
=> Bump proto

cmd/flipt/main.go, scripts/integration
Reports:
* Version
* Commit
* Build Date
* Go Version
=> Meta Info endpoint

server/metrics.go, server/server.go, storage/cache/cache.go, storage/cache/metrics.go
* Add metrics for server errors
* Move cache errors under `storage` subsystem
=> Errors metrics

.github/workflows/test.yml, cmd/flipt/main.go, config/config_test.go, server/options_test.go, server/server_test.go
Outputs API/UI addresses on STDOUT in case user has file logging enabled
=> Coverage; add api/ui address on STDOUT

.golangci.yml, Makefile, cmd/flipt/main.go, config/config.go, go.mod, go.sum, storage/cache/flag.go, storage/db.go, storage/evaluator.go, storage/rule.go
Use go 1.13 errors over pkg/errors
=> Use go 1.13 errors

script/test/api, ui/__tests__/targeting.spec.js, ui/src/components/Flags/Rule.vue, ui/src/components/Flags/Targeting.vue, ui/src/mixins/targeting.js
Fixes: #186 
Calculate rollout percentages so they always add up to 100% in UI
=> Calculate rollout percentages so they always add up to 100% in UI

cmd/flipt/main.go
Expose handling time metrics via prometheus
=> Enable response time histogram

ui/src/components/Flags.vue, ui/src/components/Segments.vue
=> Fix variants and constraints columns always showing Yes in UI

.github/workflows/benchmark.yml, .github/workflows/database-test.yml, .github/workflows/integration-test.yml, .github/workflows/test.yml, README.md, cmd/flipt/flipt.go, server/server.go, storage/db/migrator_test.go
=> Bump go versions in CI; update README

cmd/flipt/flipt.go, config/config.go, config/config_test.go, config/default.yml, config/testdata/config/advanced.yml
Allow configuration of db connections; fix `meta.check_for_updates` config option
=> Config db conns

cmd/flipt/flipt.go
=> Dont log db url

.github/workflows/benchmark.yml, .github/workflows/codeql-analysis.yml, .github/workflows/database-test.yml, .github/workflows/integration-test.yml, .github/workflows/licensed.yml, .github/workflows/snapshot.yml, .github/workflows/test.yml, DEVELOPMENT.md, Dockerfile, _tools/go.mod, examples/basic/Dockerfile, go.mod, go.sum, ui/yarn.lock
Upgrade to go 1.15 and some yarn deps
=> Upgrade to go 1.15 and some yarn deps

.dockerignore, .github/workflows/snapshot.yml, .goreleaser.yml, build/Dockerfile, script/build
Build snapshot version with docker buildx action and export build cache
=> Try to use docker buildx action with build cache

.github/workflows/benchmark.yml, .github/workflows/database-test.yml, .github/workflows/integration-test.yml, .github/workflows/licensed.yml, .github/workflows/snapshot.yml, .github/workflows/test.yml
Speed up `go test` by also caching the Go build cache
=> Try caching build cache

.github/workflows/licensed.yml, .github/workflows/release.yml, .github/workflows/test.yml
To prevent issues like #380 from happening again
Verify that the Docker images are available on DockerHub and GHCR after release
=> Add workflow to verify images published on release

.github/workflows/licensed.yml
=> licensed updates

ui/src/components/Flags/Targeting.vue
=> Fix segment autocomplete

ui/src/App.vue, ui/src/assets/sass/main.scss, ui/src/components/Flags.vue, ui/src/components/Flags/DebugConsole.vue, ui/src/components/Flags/Flag.vue, ui/src/components/Flags/NewFlag.vue, ui/src/components/Flags/Rule.vue, ui/src/components/Flags/Targeting.vue, ui/src/components/Nav.vue, ui/src/components/Segments.vue, ui/src/components/Segments/NewSegment.vue, ui/src/components/Segments/Segment.vue, ui/src/main.js, ui/src/mixins/autoKeys.js, ui/src/mixins/notify.js, ui/src/mixins/targeting.js, ui/src/mixins/utils.js, ui/src/router/index.js, ui/src/services/api.js
Runs [Prettier](https://prettier.io/) on all js files
=> Prettify everything

.github/workflows/test.yml, Makefile
=> Revert "Use coverpkg"

.github/workflows/nancy.yml
https://github.com/sonatype-nexus-community/nancy-github-action
=> Add Sonatype Nancy

go.mod, go.sum
Fix https://ossindex.sonatype.org/vulnerability/c16fb56d-9de6-4065-9fca-d2b4cfb13020?component-type=golang&component-name=github.com%2Fdgrijalva%2Fjwt-go&utm_source=nancy-client&utm_medium=integration&utm_content=1.0.29
=> Replace with jwt-go

storage/sql/migrator_test.go
=> Add test for expected migration version count

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/feature_request.md
Update issue templates to include export instructions, small cleanup
=> Update issue tmpl

CHANGELOG.md, deploy/charts/flipt/Chart.yaml
=> Releases 1.8.1

ui/src/components/Flags/Targeting.vue
=> Re-allow rules to be created without variants

deploy/charts/flipt/Chart.yaml, deploy/charts/flipt/templates/deployment.yaml
Fix helm chart configmap/volume
=> Fix helm chart

.github/workflows/benchmark.yml, .github/workflows/buf.yml, .github/workflows/database-test.yml, .github/workflows/integration-test.yml, .github/workflows/nancy.yml, .github/workflows/test.yml, deploy/charts/flipt/Chart.yaml
```yaml
branches:
- master
paths-ignore:
- "deploy/**"
- "examples/**"
- "logos/**"
- "**.md"
- "**.txt"
- "**.ya?ml"
pull_request:
paths-ignore:
- "deploy/**"
- "examples/**"
- "logos/**"
- "**.md"
- "**.txt"
- "**.ya?ml"
```
=> Ignore various filetypes/folders for Actions

script/test, test/api.sh, test/ui.sh, ui/e2e/createFlag.spec.js, ui/e2e/createSegment.spec.js
Fix playwright and enable in ITs again
=> Fix playwright and enable in ITs

cmd/flipt/main.go
- Dont log from telemetry client
- Dont run telemetry in development/snapshot versions
=> Dont log from telemetry client

.github/workflows/benchmark.yml, .github/workflows/buf.yml, .github/workflows/database-test.yml, .github/workflows/integration-test.yml, .github/workflows/scan.yml, .github/workflows/test.yml
- Update workflows to point to main
- Add gitleaks workflow
=> Update workflows to point to main; gitleaks

go.mod, go.sum
Bump negroni version to one from this decade
=> Bump negroni

.github/actions/integration-test/action.yml, .github/workflows/integration-test-image.yml, .goreleaser.yml, DEVELOPMENT.md, Dockerfile.it, README.md, docker-compose.yml, examples/auth/docker-compose.yml, examples/basic/docker-compose.yml, examples/mysql/Dockerfile, examples/postgres/Dockerfile, examples/prometheus/docker-compose.yml, examples/tracing/docker-compose.yml, rpc/flipt/marshaller.go
=> update most remaining namespace refs

CHANGELOG.md, Taskfile.yml, cmd/flipt/main.go
Build date was always showing current date/time, fixed to be correct date/time of build
=> Build date fix

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/feature_request.md, .github/workflows/benchmark.yml, .github/workflows/database-test.yml, .github/workflows/release.yml, .github/workflows/snapshot.yml, CHANGELOG.md, examples/mysql/Dockerfile, examples/postgres/Dockerfile, examples/prometheus/docker-compose.yml, ui/src/components/Flags/DebugConsole.vue, ui/src/components/Flags/Targeting.vue
=> Fix ui button spacing issues and other small issues

.github/workflows/database-test.yml, examples/postgres/docker-compose.yml
Re: #993  Bump examples/action tests to postgres 12
=> Bump to postgres 12

.github/workflows/release.yml, .github/workflows/snapshot.yml, .goreleaser.yml
Update the goreleaesr config with:
* arm64 binary builds
* mutli-arch docker image builds
Also, add the newly required dependencies for multi-arch builds to the
Github Actions workflows.
=> Support arm64 builds

CHANGELOG.md
Update Changelog for 1.11 release
=> Update CHANGELOG for 1.11

CHANGELOG.md, config/default.yml, config/production.yml, deploy/charts/flipt/README.md
- After logging changes in #1029 & #1027 , adds the defaults to the example `default.yml` config
- Adds `json` encoding to `production.yml` config
- Removes `deploy` folder as it was basically empty
=> update yaml config files with defaults for logging changes

CHANGELOG.md, ui/src/components/Flags/Flag.vue, ui/src/components/Segments/Segment.vue
Fixes fa clone icons for Flag variants and Segment constraints in UI
=> Fix clone icons

.github/workflows/nightly.yml, .goreleaser.yml
Fixes: FLI-90
- Enable nightly builds / releases w goreleaser
- Enable RC builds
=> chore: setup nightly builds, allow for pre-release builds

.github/workflows/nightly.yml, README.md
chore: add nightly builds section to README
=> chore: add nightly builds section to README

CHANGELOG.md
Release PR for Flipt `v1.16.0`.
=> feat: release v1.16.0

cmd/flipt/main.go
=> fix: dont print to stdout using color/non json formatted output when running with JSON output logger

build/internal/flipt.go
to get more inline with https://github.com/flipt-io/flipt/blob/main/build/Dockerfile
=> chore: add some missing docker instructions to build

.github/workflows/post-release.yml
Trigger Helm repo to updates chart versions on post release.
=> feat(github): trigger update helm charts on post release

README.md
Adds links to public roadmap/project in README
=> chore: add public roadmap links/badge

go.mod, go.sum
=> chore: bump prom verison

CHANGELOG.md
=> chore: update CHANGELOG for release 1.19

internal/cleanup/cleanup.go
Dont log skipping cleanup method when it is disabled.
=> chore(cleanup): only log skip message when method enabled

README.md
chore: update readme w better usecase verbiage
=> chore: update readme w better usecase verbiage

sdk/go/CHANGELOG.md, sdk/go/CHANGELOG.template.md
Initial CHANGELOG and release PR for `sdk/go/v0.1.0`.
=> feat(sdk/go): add initial CHANGELOG

.devcontainer/Dockerfile
https://github.com/flipt-io/flipt/actions/runs/4651341493/jobs/8230884387#step:4:1157
Re: https://github.com/actions/runner-images/issues/6775
=> chore: try to fix devcontainer build on actions

README.md
Update README with all client libs
=> chore: update README with client libs

.github/workflows/integration-test.yml, .github/workflows/test.yml
chore: dont ignore examples/* repo in CI
=> chore: dont ignore examples repo in CI

internal/server/auth/server.go, internal/server/auth/server_test.go
Remove extraneous print statements
=> chore: cleanup and remove print statements

config/flipt.schema.cue, config/flipt.schema.json
JSON schema, and cue configuration for audit.
Completes FLI-325
=> chore: add audit configuration to json schema and cue file

CHANGELOG.md, CODE_OF_CONDUCT.md
Update changelog for 1.21 release
=> chore: update changelog for 1.21 release

.goreleaser.yml
=> chore: try again to fix the nightly build (those v's)

README.md
- moves the integrations section up higher on the README
- makes them into two tables which are hopefully easier to read/parse
=> chore: make sdk integrations nicer to view on README

ui/index.dev.html, ui/index.html, ui/src/app/flags/EditFlag.tsx, ui/src/app/segments/Segment.tsx, ui/src/components/segments/ConstraintForm.tsx, ui/src/types/Constraint.ts, ui/vite.config.ts
Re: #1466 
Adds constraint description field to UI
=> feat(ui): add optional constraint description

internal/telemetry/telemetry.go, internal/telemetry/telemetry_test.go
Fixes: FLI-346
Fixes issue where db backend is not reported if db is configured through a URL
=> Fix db telemetry

internal/config/config_test.go, internal/config/storage.go, internal/config/testdata/storage/git_auth_enabled_basic_auth_invalid.yml, internal/config/testdata/storage/git_auth_enabled_nothing_provided.yml, internal/config/testdata/storage/git_basic_auth_invalid.yml
Configuration for private repo auth support. If the user provides any one of these parameters we will use it in the `Clone`.
Completes FLI-377
=> chore: configuration for private repo auth

go.mod, internal/storage/fs/local/source.go, internal/storage/fs/local/source_test.go, internal/storage/fs/local/testdata/features.yml
Add local implementation of `fs.FSSource`.
Completes FLI-368
=> feat: add local source with test

ui/tests/preferences.spec.ts
add tests for switching theme prefs
=> chore: add test for UI theme preferences

internal/cmd/grpc.go, internal/config/config_test.go, internal/config/storage.go, internal/storage/fs/git/source.go
Support config parameter for polling interval for git backend.
=> feat(fs/git): support custom poll interval

ui/src/components/flags/FlagForm.tsx, ui/src/components/forms/Toggle.tsx, ui/tests/flags.spec.ts
Fixes: FLI-400
disable toggle in read-only mode + add test
=> feat: No toggle readonly

CHANGELOG.md
=> chore: prep changelog

internal/server/middleware/grpc/support_test.go, internal/server/rule.go, internal/server/rule_test.go, internal/server/support_test.go, internal/storage/fs/snapshot.go, internal/storage/fs/sync.go, internal/storage/sql/common/rule.go, internal/storage/storage.go
count rules was not taking flagKey into account 😞
=> fix: count rules was not taking flagKey into account

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/feature_request.md
- rm markphelps from auto assignee on issue templates
- minor cleanup
=> chore: rm markphelps from auto assignee on issue templates

sdk/go/README.md
Was a little confused when setting this up for the first time.
=> Update import in the Go SDK README

.github/workflows/post-release.yml, .goreleaser.yml
=> chore: Update post-release.yml

ui/src/app/flags/EditFlag.tsx, ui/src/app/flags/variants/Variants.tsx, ui/src/components/flags/FlagForm.tsx, ui/src/types/Flag.ts
=> feat(ui): add flag type radio

ui/src/app/console/Console.tsx, ui/src/app/flags/EditFlag.tsx, ui/src/app/flags/rollouts/Rollouts.tsx, ui/src/components/forms/Combobox.tsx, ui/src/components/forms/Listbox.tsx, ui/src/components/namespaces/NamespaceListbox.tsx, ui/src/components/rollouts/RolloutForm.tsx, ui/src/components/rollouts/rules/SegmentRuleForm.tsx, ui/src/components/rollouts/rules/ThresholdRuleForm.tsx, ui/src/components/rules/EditRuleForm.tsx, ui/src/components/rules/RuleForm.tsx, ui/src/components/rules/distributions/SingleDistributionForm.tsx, ui/src/types/Evaluatable.ts, ui/src/types/Flag.ts, ui/src/types/Rollout.ts, ui/src/types/Segment.ts, ui/src/types/Selectable.ts, ui/src/types/Variant.ts
=> feat: eval rollout segment ui

build/testing/cli.go, go.work.sum
our CLI ITs are all failing with perm denied errors: https://github.com/flipt-io/flipt/actions/runs/5640253383/job/15276585323?pr=1898#step:5:887
This should fix that
=> fix: dagger cli test

.github/workflows/integration-test.yml, .github/workflows/test.yml, go.work.sum
to get around failing workflows re: #1943
=> chore: set dagger version in CI for now

ui/package-lock.json, ui/src/components/Footer.tsx
=> chore: update twitter icon to x

CHANGELOG.md, internal/server/auth/middleware.go, internal/server/auth/middleware_test.go
- update Changelog for 1.24.2
- merge in cherry-picked commit for https://github.com/flipt-io/flipt/pull/1934
=> chore: Update 1.24 changelog

README.md
=> chore: add console badge to readme

.github/workflows/release-clients.yml
re: https://github.com/flipt-io/flipt-grpc-dotnet/issues/4
=> chore: call proto-upgrade workflow in grpc-dotnet repo

.github/workflows/release-tag-latest.yml
Adds a workflow which is triggerable manually to attempt tagging latest.
=> chore(github): add workflow to tag latest

.github/workflows/release-tag-latest.yml, .github/workflows/release.yml
=> fix(github): add missing closing fi

.gitattributes
Windows and CRLF insanity; Ensure we lean into `lf`
=> .gitattributes to combat Windows

.github/workflows/nightly.yml, .github/workflows/snapshot.yml, .goreleaser.multi.yml
- fix broken nightly build (missing quill)
- add footer to GH release notes with links
=> chore: fix nightly build; add footer to release notes on GH

.goreleaser.nightly.yml, .goreleaser.yml
- fix nightly build (goreleaser)
- change around release notes footer
=> chore: fix nightly build, re-arrange post release notes

build/generate/screenshots.go, ui/screenshot/concepts/evaluation.js, ui/screenshot/getting_started/evaluation_console.js
Should help with `no such host` errors.
=> fix(build/generate): add exposed port to flipt

README.md, deploy/Dockerfile, go.work.sum, render.yaml
Add render.yml and Render deploy button
=> chore: Render

CHANGELOG.md, build/testing/cli.go, build/testing/testdata/flipt-namespace-foo.yml, internal/cue/flipt.cue, internal/ext/importer.go, internal/ext/importer_test.go, internal/ext/testdata/import_new_namespace.yml
should be the latest fixes from `main` cherry-picked onto the `release/1.26` branch
=> chore: 1.26.1

.github/workflows/release.yml
=> chore: attempt to fix slack webhook post on release

.goreleaser.yml, README.md
- update goreleaser release notes with install instructions
- update README to mention Homebrew install
- update README to mention auditing
=> chore: update readme/goreleaser notes

CHANGELOG.md
=> chore: bump changelog for 1.27.1

go.work.sum, internal/release/check.go, internal/release/check_test.go
=> chore: inc test coverage for release checker

config/flipt.schema.json
update json schema for storage config
=> chore: update json schema

examples/audit/webhook/README.md, examples/audit/webhook/docker-compose.template.yml, examples/audit/webhook/flipt.config.yml
Fixes: FLI-610
Adds example on how to configure webhooks via templates
=> chore: Webhooks template example

CHANGELOG.md, internal/cmd/http.go, internal/storage/fs/s3/source.go
prep 1.28.1 with bugfixes:
- #2200 
- #2193
=> chore: prep 1.28.1

ui/screenshot/concepts/distributions.js, ui/screenshot/concepts/rules.js, ui/screenshot/getting_started/create-rule.js
follow up to #2199 
fix some remaining screenshot issues
=> chore: fix remaining screenshots script issues

.goreleaser.yml, README.md, install.sh
change Docker and binary download urls to vanity URLs
=> chore: change download urls

CHANGELOG.md
=> chore: prep v1.29

internal/storage/fs/snapshot_test.go
Fixing up FS test suite due to missing flag name. 😞
=> chore: tests were broken because of this fixed it up

CHANGELOG.md
I cherry picked 4805b9e2 onto release/1.31
=> chore: prep for 1.31.2

ui/src/app/console/Console.tsx, ui/src/components/console/ContextEditor.tsx
While PR #2464 fixed the general issue with monaco editor it has introduced the regression to the size of built assets. The build process includes extra languages which are no used by the app.
Refs: #2464 #2059
=> fix(ui/console): rework monaco editor

ui/src/components/Pagination.tsx, ui/src/components/flags/FlagTable.tsx, ui/src/components/namespaces/NamespaceTable.tsx, ui/src/components/segments/SegmentTable.tsx, ui/src/components/tokens/TokenTable.tsx
=> feat(ui): allow setting page size for tables

ui/src/app/Layout.tsx, ui/src/app/meta/metaSlice.ts, ui/src/components/Loading.tsx, ui/src/types/Meta.ts
=> fix(ui):  Page api call could finish earlier that Layout api calls

DEVELOPMENT.md
Updating DEVELOPMENT.md about CGO requirement
cc @julesglad
=> chore: update dev instructions about CGO

ui/src/app/preferences/Preferences.tsx
=> feat(ui): show time/date format on settings/preferences page

.github/workflows/integration-test.yml, .github/workflows/uffizzi-build.yml, .github/workflows/uffizzi-preview.yml
Kodiak beat me to merging the last PR.
Here are some more necessary fixes to get the GH workflows behaving properly now with upload-artifact v4.
=> fix(github): update more workflows for upload-artifact changes

CHANGELOG.md, go.work.sum
- update change log
- go mod tidy
=> chore: prep for v1.34 release

cmd/flipt/config.go
Don't have a good idea how to write test for this. Corba doesn't provide any suggestions. 
fixes #2614
=> fix: config init does not work correctly

ui/src/components/Searchbox.tsx
it's very hard to see what is in the input
=> fix(ui): searchbox has a black text color in dark mode

.goreleaser.darwin.yml, .goreleaser.linux.yml, .goreleaser.yml
=> chore: Try to fix nightly build again

ui/src/components/segments/ConstraintForm.tsx
=> fix(ui): boolean constraint type asks for value when you edit it

ui/src/app/console/Console.tsx, ui/src/app/flags/Flag.tsx, ui/src/app/flags/Flags.tsx, ui/src/app/flags/flagsApi.ts, ui/src/data/api.ts, ui/src/store.ts, ui/src/utils/redux-rtk.ts
just a prove of concept how it could look
=> refactor: clean up reference in http request

ui/src/app/console/Console.tsx
Fixing input alignment for Entity id on small screens
=> fix(ui): fix input alignment on small screens

ui/src/app/flags/analytics/Analytics.tsx
Style the analytics well a bit
=> chore: style analytics well

CHANGELOG.md
update changelog for 1.37 release
=> chore: changelog for 1.37 release

config/migrations/clickhouse/1_default_aggregated.up.sql, config/migrations/clickhouse/2_default_aggregated_view.up.sql, internal/config/analytics_test.go, internal/server/analytics/clickhouse/client.go, internal/storage/sql/migrator.go
=> fix(analytics): aggregate data to run queries faster

internal/config/analytics.go, internal/telemetry/telemetry.go, internal/telemetry/telemetry_test.go
add analytics telemetry if enabled
=> chore: add analytics telemetry if enabled

ui/src/components/Nav.tsx
=> chore: add command mode help text

ui/src/app/auth/Login.tsx, ui/src/app/flags/Flag.tsx, ui/src/app/segments/Segment.tsx
Cannot update a component (`NotificationProvider`) while rendering a different component
=> fix(ui): prevent react warning

ui/src/app/flags/analytics/Analytics.tsx, ui/src/app/meta/metaSlice.ts, ui/src/types/Meta.ts
Fixes: https://github.com/flipt-io/flipt/issues/2846
=> chore: fix for analytics 501 issue

internal/server/evaluation/legacy_evaluator.go, internal/server/evaluation/legacy_evaluator_test.go
IsNotOneOf operator used same logic as IsOneOf
=> Fix IsNotOneOf operator

core/validation/flipt.json
Adds a JSON schema file to help users edit `*features.yml` files.
Solves #2883, but only for v1.2.
=> feat: Add json schema for flipt features

CHANGELOG.md
=> chore: prepare release 1.40

config/flipt.schema.cue, config/flipt.schema.json, internal/cmd/grpc.go, internal/config/cache.go, internal/config/config_test.go, internal/config/testdata/cache/redis-username.yml
=> fix(cache): accept a username in redis configuration

CONTRIBUTING.md
Switch language in contributing.md and add info about DCO
=> chore: add DCO text to contributing

config/flipt.schema.cue, config/flipt.schema.json, internal/config/testdata/tracing/otlp.yml, internal/config/testdata/tracing/wrong_sampling_ratio.yml, internal/config/tracing.go
YAML config should be snake case
We really need to figure out a way to automate this check as it's bitten us before. Anyone have any ideas?
=> fix(breaking): sampling ratio yaml config

go.mod, go.sum, internal/cmd/grpc.go, internal/metrics/metrics.go
Hi, I'm opening this PR to make a little improvement in the OTLP metrics by:
* Adding attributes like the host and runtime information
* Adding the OTEL Runtime Metrics when OTLP is enabled
=> Improve otlp metrics

CHANGELOG.md
=> chore: Release/1.41.1

cmd/flipt/bundle.go, cmd/flipt/export.go, cmd/flipt/import.go, cmd/flipt/main.go, cmd/flipt/migrate.go, cmd/flipt/validate.go, internal/config/config.go, internal/config/config_test.go
pass in context from command for cancelation when loading config file
=> chore: Pass context to get config

cmd/flipt/cloud.go
=> fix: rm port from cloud host if there

cmd/flipt/cloud.go, go.work.sum
=> chore: check for existing instance in cloud

ui/src/app/Layout.tsx, ui/src/app/Onboarding.tsx, ui/src/app/events/eventSlice.ts, ui/src/components/Banner.tsx, ui/src/store.ts, ui/tests/onboarding.spec.ts
=> feat: add banner about cloud offering

.goreleaser.nightly.yml, .goreleaser.yml
https://goreleaser.com/deprecations/#changelogskip
=> chore: fix goreleaser deprecations

CHANGELOG.md
=> chore: update changelog for release

cmd/flipt/cloud.go, cmd/flipt/main.go, config/flipt.schema.cue, config/flipt.schema.json, internal/config/cloud.go
breaking change, although no one is really using this yet in prod so we should be good
Fixes: FLI-1058
=> chore(refactor): rename instance to gateway for flipt cloud

CHANGELOG.md
=> chore: release v1.43.0

internal/cmd/grpc.go
Re: https://community.flipt.io/t/disable-log-for-grpc-health-v1-health/28
=> chore: dont log grpc healthcheck

.github/workflows/integration-test.yml, .github/workflows/test.yml
* update to latest dagger 0.11.7
* use dagger-for-github action
=> refactor gh action

.github/workflows/test.yml
pass in dagger cloud token correctly
=> chore(ci): pass in dagger cloud token correctly

.github/workflows/test.yml, dagger.json
Add views to exclude directories so that we don't bust the cache in CI every time.
=> Add views to Dagger

.goreleaser.yml, build/Dockerfile
- add back build/Dockerfile for release
- fix goreleaser warning about version missing
=> chore: add back build/Dockerfile for release

CHANGELOG.md
bump changelog for release 1.45
=> chore: bump changelog for release 1.45

build/go.mod, go.mod, sdk/go/go.mod
Re: https://github.com/flipt-io/flipt/issues/3235
=> chore: bump rpc package to latest version

CHANGELOG.md
Update changelog for releasing 1.46
=> chore: prep for 1.46 release

internal/ext/importer.go, internal/ext/importer_test.go
=> fix(import): resolve issue with import flag with default variant

config/migrations/mysql/12_namespaces_add_state_modified_at.up.sql
=> fix(storage): support mysql 5.7 in 12 migration

config/flipt.schema.cue, config/flipt.schema.json, go.work.sum, internal/config/config.go, internal/config/cors.go, internal/config/testdata/marshal/yaml/default.yml
=> fix(cors): add missing from default allowed CORS headers

.goreleaser.darwin.yml, .goreleaser.linux.yml
=> chore: set goreleaser versions

internal/cmd/grpc.go, internal/server/audit/template/executer.go, internal/server/audit/template/executer_test.go, internal/server/audit/template/leveled_logger.go, internal/server/audit/template/leveled_logger_test.go, internal/server/audit/webhook/client.go, internal/server/audit/webhook/client_test.go
=> fix(audit): provide correct leveled_logger for retryablehttp client

CHANGELOG.md
PR for release version 1.48.1 including @erka fix for the logger panic.
=> Release 1.48.1

.github/workflows/integration-test.yml, build/testing/integration.go
=> ci(audit): add integration testing for audit webhooks

ui/package-lock.json, ui/package.json, ui/src/components/forms/Dropdown.tsx
=> chore(ui): update playwright deps to restore ui integration tests

go.work.sum, ui/package-lock.json, ui/package.json, ui/src/App.tsx, ui/src/app/Layout.tsx, ui/src/app/Onboarding.tsx, ui/src/app/events/eventSlice.ts, ui/tests/onboarding.spec.ts
1. Fixes a deprecation issue for formbricks by upgrading to latest version
2. Makes banner dismissed cookie dependent on version (so it will show once more for users who have previously dismissed the old banner)
3. Updates Onboarding page to better describe 'new' cloud
4. Adds community discourse forum link to onboarding page
=> chore: upgrade formbricks lib; reword banner and onboarding

internal/server/authz/engine/bundle/engine.go, internal/server/authz/engine/bundle/engine_test.go, internal/server/authz/engine/ext/extentions.go, internal/server/authz/engine/rego/engine.go, internal/server/authz/engine/rego/engine_test.go, internal/server/authz/engine/testdata/rbac.rego
=> fix(authz): added a helper function to the policy engine to simplify auth method verification

README.md
We're launching Flipt Cloud on Product Hunt on Monday. Adding badge for visibility
=> chore: Add product hunt badge to readme

go.mod, go.work.sum, internal/config/database_linux.go, internal/config/database_linux_test.go
=> fix: use user's home for sqlite db if preferred location doesn't exist

.github/workflows/test.yml, install.sh
couple more posix fixes (suggested by Cursor) + add test for the install script + shellcheck
=> chore: fix install script + shellcheck

.github/workflows/integration-test.yml, .github/workflows/test.yml
try remove dagger cloud to see if it makes builds noticeably slower
=> chore: try remove dagger cloud to see if it makes builds noticeably slower

ui/src/app/flags/analytics/Analytics.tsx, ui/src/components/rollouts/Rollouts.tsx
=> fix(ui): tweak flag tabs to have the same layout

CHANGELOG.md, go.work.sum
=> chore: Release/1.52.1

internal/server/authn/method/github/server.go
slight refactor to remove some duplication in the github/auth server code
- adds comments
- removes some helper functions and inlines them
- use maps.Keys
=> chore: slight refactor of github/auth server

stackhawk.yml
fixes broken hawkscan scan on nightly image
before: https://github.com/flipt-io/flipt/actions/runs/12100000265
now: https://github.com/flipt-io/flipt/actions/runs/12107330112/job/33754219563
=> chore: fix hawkscan scanning

ui/src/components/Header.tsx, ui/src/components/header/UserProfile.tsx
Before
After:
some regression in #3738
=> fix(ui): fix the user profile icon

internal/cmd/http.go
The additional UI http headers are added to each api requests. They add
extra bytes to each api call without any value (up to 15-20% of request
size). This work rearrange the code to apply those headers only for
requests to UI assets.
=> fix: apply UI additional http headers only for requests to UI assets

internal/config/authentication.go, internal/config/config.go, internal/config/config_test.go, internal/config/storage.go, internal/config/testdata/advanced.yml, internal/config/testdata/authentication/token_bootstrap_token.yml, internal/config/testdata/authorization/all_authentication_methods_enabled.yml, internal/config/testdata/storage/git_basic_auth_invalid.yml, internal/config/testdata/storage/git_ssh_auth_invalid_missing_password.yml, internal/config/testdata/storage/git_ssh_auth_invalid_private_key_both.yml, internal/config/testdata/storage/git_ssh_auth_invalid_private_key_missing.yml, internal/config/testdata/storage/git_ssh_auth_valid_with_path.yml
OK, initial pass to get config tests green again.
=> fix(tests/config): get test suite back into passing state

internal/storage/environments/fs/namespaces.go, ui/src/app/namespaces/Namespaces.tsx, ui/src/app/namespaces/namespacesApi.ts, ui/tests/namespaces.spec.ts
fixes ability to update namespace
=> chore: fix namespace update

internal/storage/git/repository.go
fixes issue with stuck mutex locking
=> fix: V2 stuck mutex acq

ui/src/app/preferences/preferencesSlice.ts
=> fix(ui): use correct default theme on first load

config/flipt.schema.cue, config/flipt.schema.json, go.work.sum, internal/cache/cache.go, internal/cache/memory/cache.go, internal/cache/redis/cache.go, internal/cache/redis/cache_test.go, internal/config/cache.go, internal/config/server.go
Re: #4033 
Add ability to specify Redis key prefix
=> feat(cache): support optional prefix for redis cache keys

CHANGELOG.md
=> chore: update changelog for 1.57 release

internal/cmd/grpc.go, internal/storage/unmodifiable/store.go, internal/storage/unmodifiable/store_test.go
=> fix(store): disable modification of the store in read only mode

ui/package-lock.json, ui/package.json, ui/src/components/Header.tsx, ui/src/components/environments/EnvironmentListbox.tsx, ui/src/components/forms/Listbox.tsx, ui/src/components/namespaces/NamespaceListbox.tsx, ui/tests/flags.spec.ts, ui/tests/namespaces.spec.ts, ui/tests/segments.spec.ts
=> refactor(ui): rework listbox

internal/config/storage.go, internal/storage/git/repository.go
adds some debug logging for pushing to remote as i couldnt figure out what was happening but turned out to be a misconfiguration on my end
=> chore: V2 debug logging remote

ui/src/components/Combobox.tsx
gives combobox a relative classname and width so the positioning context for the dropdown is limited to the width of its parent
=> fix: give combobox relative width

ui/src/app/Settings.tsx, ui/src/app/preferences/Preferences.tsx, ui/src/app/preferences/preferencesSlice.ts, ui/src/components/Chips.tsx, ui/src/components/command/CommandDialog.tsx, ui/src/components/constraints/ConstraintTable.tsx, ui/src/components/constraints/Constraints.tsx, ui/src/components/forms/Select.tsx, ui/src/components/namespaces/NamespaceTable.tsx, ui/src/components/variants/VariantTable.tsx, ui/src/components/variants/Variants.tsx, ui/src/data/hooks/notification.ts, ui/src/types/Preferences.ts, ui/tests/namespaces.spec.ts, ui/tests/preferences.spec.ts
1. Cleans up settings/preferences UI
2. ~~Give user ablity to set a default 'view mode' for views with potentially many items like constraints/variants~~
3. Updates variants and constraints to use tanstack table with better styling
=> feat: update settings page; use tanstack table for constraints/variants

internal/storage/environments/fs/namespaces.go, internal/storage/environments/fs/namespaces_test.go
=> fix: issue where updating namespace deletes all its data

ui/src/utils/helpers.test.ts, ui/src/utils/helpers.ts
=> chore: make keys lowercase in ui

config/flipt.schema.cue, config/flipt.schema.json, core/validation/flipt.cue, core/validation/flipt.json, go.mod, go.sum, internal/cmd/authn.go, internal/config/authentication.go, internal/storage/authn/redis/client.go, internal/storage/authn/redis/client_test.go, internal/storage/authn/redis/store.go, internal/storage/authn/redis/store_test.go, ui/src/app/auth/Login.tsx
Port over #4034 and #4035 for v2
=> feat: port over redis cluster and prefix

internal/cmd/grpc.go, internal/config/config.go, internal/config/config_test.go, internal/config/log.go, internal/config/metrics.go, internal/gateway/marshaller.go, internal/server/analytics/clickhouse/client.go, internal/server/analytics/clickhouse/mutation.go, internal/server/analytics/prometheus/client.go, internal/server/authn/method/oidc/server.go, internal/server/authn/method/oidc/server_test.go, internal/server/authn/middleware/grpc/middleware.go, internal/server/authn/middleware/grpc/middleware_test.go, internal/server/authz/engine/rego/engine.go, internal/server/authz/engine/rego/engine_test.go, internal/server/authz/middleware/grpc/middleware.go, internal/server/authz/middleware/grpc/middleware_test.go, internal/server/middleware/grpc/middleware_test.go, internal/storage/analytics/fields.go, internal/storage/authn/redis/store.go, internal/storage/authn/testing/testing.go, internal/storage/environments/fs/flipt/flags.go, internal/storage/environments/fs/flipt/flags_test.go, internal/storage/environments/fs/flipt/segments.go, internal/storage/fs/snapshot_test.go, internal/storage/git/filesystem.go
Ran https://pkg.go.dev/golang.org/x/tools/gopls/internal/analysis/modernize -fix
=> chore: run gopls modernize

.github/workflows/integration-test.yml, build/testing/integration.go, internal/storage/authn/sql/store.go, internal/storage/sql/common/segment.go, internal/storage/sql/fields.go
test with prepared statements disabled for postgres to catch issues with type conversions
re: https://github.com/flipt-io/flipt/pull/3454#issuecomment-2340272083
=> chore: test with prepared statements off for pg

ui/src/components/Button.tsx, ui/src/components/Combobox.tsx, ui/src/components/Select.tsx, ui/src/components/environments/EnvironmentBranchSelector.tsx, ui/src/components/forms/SegmentsPicker.tsx, ui/src/components/forms/Select.tsx, ui/src/components/ui/button.tsx
=> fix(ui): v2 clean up branch selector

internal/storage/environments/git/store.go, internal/storage/environments/git/store_test.go, internal/storage/git/metrics.go, internal/storage/git/repository.go, ui/src/components/environments/branches/CreateBranchPopover.tsx
Fixes: #4265
- push remote branch if remote configured on create
- clear branch name input on branch modal close
=> fix: Push on branch

ui/src/app/NotFoundLayout.tsx, ui/src/app/Support.tsx, ui/src/app/analytics/Analytics.tsx, ui/src/app/auth/Login.tsx, ui/src/app/flags/NewFlag.tsx, ui/src/app/segments/NewSegment.tsx, ui/src/components/environments/branches/CreateBranchPopover.tsx, ui/src/components/namespaces/NamespaceForm.tsx, ui/src/components/rollouts/EditRolloutForm.tsx, ui/src/components/rollouts/RolloutForm.tsx, ui/src/components/rules/RuleForm.tsx, ui/src/components/segments/ConstraintForm.tsx, ui/src/components/variants/VariantForm.tsx, ui/tests/support.spec.ts
=> chore: update inapp links for v2 docs

internal/storage/fs/snapshot.go, internal/storage/fs/snapshot_test.go, internal/storage/fs/testdata/valid/explicit_index/prod/prod.features.yml
=> fix: flag metadata parsing from snapshot

CLAUDE.md, internal/config/config_test.go, internal/coss/storage/environments/git/github/github.go, internal/release/check_test.go, internal/server/authn/method/kubernetes/server_internal_test.go, internal/server/authn/method/oidc/server_internal_test.go, internal/server/authn/middleware/grpc/middleware.go, internal/server/authn/middleware/grpc/middleware_test.go, internal/storage/environments/evaluation/publisher.go, internal/storage/environments/git/store.go, internal/storage/git/filesystem.go, magefile.go
https://pkg.go.dev/golang.org/x/tools/gopls/internal/analysis/modernize
=> chore: add modernize mage target, run it, update CLAUDE.md

internal/config/config.go, internal/config/config_test.go, internal/config/testdata/authentication/github_case_sensitive.yml, internal/server/evaluation/client/server_test.go
=> fix(authn): github allowed_teams keys are lowercased in configuration

ui/src/types/Variant.ts
=> fix(ui): variant with no name is not shown in the rules

.github/workflows/integration-test.yml, .github/workflows/test.yml, build/internal/flipt.go, build/main.go, build/testing/integration.go, build/testing/test.go, codecov.yml, internal/secrets/file/provider_test.go
try to get Go integration test coverage working and uploaded to codecov
this might not show up on codecov until its on the v2 branch.. but i verified individual coverage files are being generated, and codecov says it can automatically merge them https://docs.codecov.com/docs/merging-reports
=> chore: Integration test coverage

install.sh
- Removes jq dependency from the v2 install script
- Simplifies `get_latest_version()` function to use standard shell tools
- Implements proper semantic version sorting without external dependencies
- **Modified `install.sh`**: Replaced complex jq-based parsing with grep/cut/sort approach
- **Removed conditional logic**: No more checking for jq availability or GNU sort
- **Added semantic version sorting**: Uses `sort -t. -k1,1n -k2,2n -k3,3n` for proper semver ordering
The new implementation:
1. Uses `grep '"tag_name"'` and `cut -d '"' -f 4` to parse GitHub API response
2. Filters to v2.x.x releases with `grep '^v2\.'`
3. Sorts semantically by major.minor.patch using standard sort command
4. Takes the highest version with `tail -n 1`
This approach is more portable and eliminates the need …
=> feat: remove jq dependency from v2 install script

ui/CLAUDE.md
Claude can use multiple CLAUDE.md files per project to get better context.
This adds one specifically for the UI folder
=> chore: add claude.md for ui subfolder

CHANGELOG.md
=> chore: update changelog for 2.0.1

.github/prompts/format-release-notes.prompt.yml, .github/prompts/generate-changelog-entry.prompt.yml, .github/prompts/generate-release-pr.prompt.yml, .github/prompts/validate-changelog.prompt.yml, .github/workflows/finalize-release.yml, .github/workflows/prepare-release.yml, .github/workflows/release.yml
This PR introduces a comprehensive AI-powered release automation system that streamlines the entire release process from changelog generation to GitHub release notes formatting. The system reduces manual work, ensures consistency, and minimizes the chance of human error during releases.
- **Changelog Generation**: Automatically creates changelog entries by analyzing commits and PRs since the last release
- **Release Notes Formatting**: Formats professional, user-friendly release notes from changelog content
- **PR Description Generation**: Creates comprehensive release PR descriptions with highlights and testing checklists
- **Content Validation**: AI validates changelog completeness against actual code changes
**Before**: 7 manual steps → **After**: 2 steps (trigger workflow + merge PR) …
=> feat: Add AI-powered release automation workflows

.github/prompts/release.md, .goreleaser.yml
Re: https://github.com/flipt-io/homebrew-brew/issues/5
See: https://goreleaser.com/customization/changelog/
=> chore: add back homebrew config for release; try generating release notes with ai

config/flipt.schema.cue, config/flipt.schema.json
=> chore: add bitbucket to scm schema

go.work.sum, internal/cmd/grpc.go
=> fix(auth): allow to exclude auth for ofrep endpoint

internal/server/authn/method/util.go, internal/server/authn/method/util_test.go
Summary:
Refactored code in util.go for better readability and maintainability.
Applied inline error handling and replaced magic values with constants.
Ensured code style aligns with project and Google Go style guide recommendations.
=> refactor(authn/method): improve code style and error handling in util.go
