CHANGELOG.md, Makefile, config/migrations/postgres/1_variants_unique_per_flag.down.sql, config/migrations/postgres/1_variants_unique_per_flag.up.sql, config/migrations/sqlite3/1_variants_unique_per_flag.down.sql, config/migrations/sqlite3/1_variants_unique_per_flag.up.sql, docs/concepts.md, storage/db.go, storage/flag.go, storage/flag_test.go, storage/rule.go, storage/segment.go
Fixes #87 to require variant keys to be unique only for an individual flag, not globally.
=> Unique Variant fix

storage/rule.go, storage/rule_test.go, ui/src/components/Segments/Segment.vue
Sometimes I want to segment some features for our company users only, e.g. username ending in company e-mail domain, and while trying to configure this I found out that Segment rules were lacking a `suffix` operator. I could achieve similar behavior by adding several `==` constraints for each username, but keeping that list up-to-date would be painful (and I believe a huge list of constraints can also lead to poor evaluation performance?).
To solve this, this PR introduces two new string matching operators: `prefix` and `suffix`. Now, matching the mentioned segment of users is one single constraint rule. Prefix was added because it was simple to add suffix and I see some usages such as allowing some flags by phone number country code, e.g. phone number starts with `+55` etc.
If you prefer …
=> Add prefix and suffix segment rule operators

Dockerfile
To avoid depending on a local setup for the build and only using Docker as packaging, we can leverage multi-stage builds to guarantee build reproducibility while still keeping the final image clean and small.
It is possible to stop the build in a specific stage for development/debugging purposes with the `--target` flag, e.g. `docker build -t flipt --target build .`
=> Set multi-stage Dockerfile for easier builds

Makefile, go.sum, storage/db_test.go, storage/evaluator.go, storage/evaluator_test.go
Fixes: #166 
Was [ranging over a map of rules](https://github.com/markphelps/flipt/pull/168/files#diff-2a28b7ff422916110e588eb24cbce69dL124) which is inconsistent per the [spec](https://golang.org/ref/spec#For_statements):
> The iteration order over maps is not specified and is not guaranteed to be the same from one iteration to the next.
=> Fix inconsistent segment matching

.gitignore, go.mod, go.sum
Was doing some benchmarking of memory usage running [vegeta](https://github.com/tsenart/vegeta) and saw that memory allocs were pretty insane for `compress/flate.NewWriter` (up to 17105 MB) which I tracked down to [chi compress middleware](https://github.com/go-chi/chi/blob/v3.3.4/middleware/compress.go#L268). This seems to create a new flate/compressor for each invocation.
Updating to master branch of chi seems to fix this by using a [sync.Pool of compressors](https://github.com/go-chi/chi/blob/221acf29d02b708ec13791ff562888a730bfe6a7/middleware/compress.go#L136) and reduces memory allocs.
=> Bump Chi to master to fix large memory allocs

Makefile, ui/src/components/Flags/Flag.vue, ui/src/components/Flags/Targeting.vue, ui/src/components/Segments/Segment.vue
=> Handle flags/segments not found in UI

Makefile, storage/db_test.go, storage/evaluator_test.go
```
➜ make bench
>> running benchmarks
go test -v -bench=. ./... -run=XXX
goos: darwin
goarch: amd64
pkg: github.com/markphelps/flipt/storage
BenchmarkEvaluate_SingleVariantDistribution/match_string_value-4                    4494            242572 ns/op           24074 B/op        486 allocs/op
BenchmarkEvaluate_SingleVariantDistribution/no_match_string_value-4                 6280            187252 ns/op           19620 B/op        390 allocs/op
BenchmarkEvaluate_SingleVariantDistribution/no_match_just_bool_value-4              6550            202475 ns/op           18034 B/op        381 allocs/op
BenchmarkEvaluate_SingleVariantDistribution/no_match_just_string_value-4            6272            181950 ns/op           17939 B/op        381 allocs/op …
```
=> Add evaluation benchmarks

config/local.yml, ui/src/components/Flags.vue, ui/src/components/Flags/Rule.vue, ui/src/components/Segments.vue
Fixes: #190 
* Add pagination for flags and segments in UI
* Show segment key and link to segment in targeting
=> Add pagination for flags and segments in UI

server/evaluator.go, server/evaluator_test.go
The current implementation skips over distributions that have a 0% rollout and build a buckets array.
The buckets array is accessed by index, but since we skip all 0% distributions, the index of the loop can get out of sync with the last index of the buckets array, creating index out of range errors.
This adds 2 tests specific for the issue and fixes them.
Let me know if this needs updating / re-working.
=> fix 0% distribution issues

CHANGELOG.md, storage/db/evaluation.go, storage/db/evaluation_test.go
Fixes: #229 
Fix evaluation does not consistently maintain distribution order when using Postgres
=> Fix evaluation does not consistently maintain distribution order when using Postgres

cmd/flipt/export.go, cmd/flipt/flipt.go, cmd/flipt/import.go, config/config.go, config/config_test.go, storage/cache/evaluation.go, storage/cache/flag.go, storage/cache/metrics.go, storage/cache/rule.go, storage/cache/segment.go, storage/db/db.go, storage/db/db_test.go, storage/db/metrics.go, storage/db/migrator.go
* Add prometheus metrics around db connections
* Update fqdn for cache metrics
=> Db metrics

CHANGELOG.md, errors/errors.go, rpc/flipt.pb.go, rpc/flipt_grpc.pb.go, server/evaluator.go, server/evaluator_test.go
Related to #376
Don't error when trying to evaluate a flag that is disabled, instead just return false (no match)
/cc @vic3lord
=> Dont error on disabled flag

README.md
As discussed in #385 this is the step 1: align the README with the current setup that spins up the service on `0.0.0.0` instead of localhost.
=> Replaces the localhost by 0.0.0.0 in the README 

Makefile
Add commit hash to dev build, so it would be available when running
flipt --version. Silently fallback to an empty commit hash when git
command isn't available in order to allow building w/o git.
useful for issue reporting.
=> Feature: Add commit hash to dev build

ui/src/components/Flags/Targeting.vue
fixes #515 
Fix corrupted rule issue by clearing selectedVariant when closing
add rule dialog.
=> bugfix: Fix corrupted rule issue

.github/workflows/test.yml, .golangci.yml, Makefile, cmd/flipt/main.go, script/bootstrap, server/server.go, storage/db/common/rule.go
* Uses `grpc.WithTransportCredentials(insecure.NewCredentials())`
* Upgrade linter version
* Fix linter errors
=> Fix grpc insecure

CHANGELOG.md, cmd/flipt/main.go, internal/ext/common.go, internal/ext/exporter.go, internal/ext/exporter_test.go, internal/ext/importer.go, internal/ext/importer_test.go, internal/ext/testdata/export.yml, internal/ext/testdata/import.yml, internal/ext/testdata/import_no_attachment.yml, ui/build/utils.js, ui/src/components/Nav.vue, ui/src/components/UpdateNotification.vue
Fixes: #710 
Add missing segment match type in export/import
=> Fixes segment export/import match_type

.github/workflows/test.yml, .tool-versions, internal/ext/fuzz_test.go, internal/ext/importer.go, internal/ext/testdata/fuzz/FuzzImport/23a479a6d020799b0dfd2f87cb73b2cca2087341827edef76cee0ffb2c099f75, internal/ext/testdata/fuzz/FuzzImport/30227e9d2cd52e137e200e3e27990735115095efc22a6df092d85566ccaf8014, internal/ext/testdata/fuzz/FuzzImport/3bfb3390d4d70789a687706474d457e4ee150c8d626e2e079b445f71e861b2b7, internal/ext/testdata/fuzz/FuzzImport/45ee39c40278286647ba2de44d5036001a146c77a4716d23b8785bfd00bc4852
Fuzz Testing with 1.18rc1 and fixing fuzz bugs
=> Fuzz Testing

Taskfile.yml, modd.conf, ui/src/components/Flags/Flag.vue, ui/src/components/Segments/Segment.vue
While working on setting up a simliar example as described in #732 in order to start working on a solution, I realized that it was very tedious to create constraints (and variants) that were based on existing ones with only minor differences.
Example:
```
Constraint 1: { property: 'environment', operator: 'eq', value: 'development' }
Constraint 2: { property: 'environment', operator: 'eq', value: 'staging' }
```
In this example the constraints only differ by the 'value', but in order to create these contraints in the UI I had to start from scratch each time.
This PR adds
1.  'duplicate' functionality in the UI for constraints and variants
2. labels for the icons in the constraints/variants tables
3. Minor description changes in the Taskfile.
=> Add ability to quickly duplicate constraints/variants

ui/src/components/Flags/DebugConsole.vue, ui/src/components/Flags/Flag.vue, ui/src/components/Flags/Targeting.vue, ui/src/components/Segments/Segment.vue
Fixes: #758 
- Disallow rule to be created with no variants/distributions in UI
- Fix small issue where clicking 'Choose Variants' again didnt clear our distributions
- Update imports from lodash to use ES6 style
=> Disallow rule create with no distributions; update imports

cmd/flipt/main.go, go.mod, go.sum
Fixes https://github.com/markphelps/flipt/issues/802
For CORS, the server needs to include `Origin` in the `Vary` response (if `Access-Control-Allow-Origin` is not set to `*`)
https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS#access-control-allow-origin
Flipt is using go-chi/cors to handle CORS which does include that header
https://github.com/go-chi/cors/blob/9b0b248d5e6ba10c954f076a98c5f7760f243882/cors.go#L242-L247
However, if the request includes `Accept-Encoding`, this triggers this line
https://github.com/go-chi/chi/blob/86f9a6e7ce9bf453eaa339b51f88f586edbccbc1/middleware/compress.go#L321
which overrides any previously set Vary headers
N.B. `Accept-Encoding` is a forbidden header https://developer.mozilla.org/en-US/docs/Glossary/Forbidden_header_name
meaning it can only be set …
=> Upgrade go-chi/chi to commit that handles Vary header properly

.github/dependabot.yml
Ignore PRs from dependabot for major version updates as these are risky and should be done manually
See: https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#ignore
=> Ignore major dependabot upgrades

examples/basic/main.go, go.mod, go.sum
flipt-grpc-go moved to https://github.com/flipt-io/flipt-grpc-go
=> Update flipt-grpc-go version and path

.goreleaser.yml
Re: #993 
Add `netgo` build tag when building Flipt release
Backport for v1.9 (will create 1.9.1). Will do the same for v1.10 (1.10.1)
=> Use netgo when building

Taskfile.yml, cmd/flipt/main.go, config/config.go, config/config_test.go, config/testdata/advanced.yml
Fixes #992 
1. Adds support for encoding log output as JSON using either `FLIPT_LOG_ENCODING` env var or setting `log.encoding` via yaml
2. Only prints banner and api/ui addrs as text if we're running in console mode
/cc @GeorgeMac
=> JSON log output

cmd/flipt/main.go, config/config.go, config/config_test.go, config/testdata/default.yml
This continues on from a discussion in the original logrus to zap PR: https://github.com/flipt-io/flipt/pull/1020
This forwards all gRPC internal logging into zap.
Originally, I tried to use `grpc_zap.ReplaceGrpcLoggerV2` in the first PR, which led to lots of gRPC chatter in the logs.
This was because the default zap level for all Flipt logs was INFO and gRPC has a lot of INFO chatter.
Normally, the default severity level for gRPC is `ERROR`. Which is why you don't see this.
My first attempt to improve this tapped into the env var `GRPC_GO_LOG_SEVERITY_LEVEL`.
However, this had the interesting effect of both forwarding logs to zap *and* printing gRPC logs in their native log format to stdout/stderr.
Instead, I have now introduced a new flipt compatible `log.grpc_level` option.
This option …
=> feat(logging): forward grpc internal logging to zap

server/evaluator.go, server/evaluator_test.go, storage/sql/db_test.go, ui/src/components/Flags/DebugConsole.vue
Fixes: #1046 
Now returns a 400 Bad Request from the API when a value cannot be parsed at the type expected.
Also, updates the DebugConsole UI to show the error message and correctly style the response.
=> Fix parse error for bool/number to not return 500

cmd/flipt/main.go
Just a quick fix for an observation.
The shutdown context and 5 second timeout was getting initialized on Flipt start.
Meaning, the shutdown context was likely (unless Flipt was stopped immediately) to be well and truly cancelled before any interrupt is sent.
This moves the initialization of the 5-second timeout context to be after any interrupt is received.
Ensuring at-least five seconds grace period is given on shutdown (maybe this should be configurable too at some point).
=> fix: initialize shutdown context timeout after interrupt

cmd/flipt/main.go
Such a minor thing, but swapping the HTTP method strings to the available constants.
=> Swap to http.Method* Constants

config/migrations/sqlite3/1_variants_unique_per_flag.down.sql
I noticed the following error while attempting to run the down migrations for `sqlite` driver:
```
attempting to drop during import: reverting migrations: near "key": syntax error in line 0: /* SQLite doesn't allow you to drop unique constraints with ALTER TABLE
so we have to create a new table with the schema we want and copy the data over.
https://www.sqlite.org/lang_altertable.html
*/
PRAGMA foreign_keys=off;
CREATE TABLE variants_temp
(
id VARCHAR(255) PRIMARY KEY UNIQUE NOT NULL,
flag_key VARCHAR(255) NOT NULL REFERENCES flags ON DELETE CASCADE,
key VARCHAR(255) NOT NULL,
name VARCHAR(255) NOT NULL,
description TEXT NOT NULL,
created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
UNIQUE key ON CONFLICT REPLACE
);
INSERT INTO …
```
=> fix(migrations/sqlite3): syntax error in uniqueness constraint on temp table in down operation

Taskfile.yml
Remove the 'caching' that Task allows for `task bootstrap`. this will guarantee that users that build Flipt for the first-time or in a devcontainer always have the necessary tools installed (ie: buf)
cc @josebalius
Also it doesn't slow down the build since Go will not re-download if those tools already exist at those versions
=> chore: fix bootstrap in devcontainer/first build

CHANGELOG.md, cmd/flipt/main.go, internal/config/cache.go, internal/config/cors.go, internal/config/tracing.go
fix(config): fix default booleans not being overriden by env vars
fix(telemetry): fix otel span propogation through Flipt
=> fix(config): fix default booleans not being overriden by env vars

.github/workflows/release.yml
Bought a goreleaser-pro subscription so we can have nightly/rc builds that are published.
This setups the release action to use the pro version + use our license key
=> chore: switch to goreleaser-pro

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/feature_request.md, .github/workflows/lint.yml, .github/workflows/test.yml, .markdownlint.yaml, CHANGELOG.md, CODE_OF_CONDUCT.md, DEVELOPMENT.md, README.md, examples/auth/README.md
- moves lint steps into their own workflow file
- adds `markdownlint` job to lint markdown because we arent barbarians
- fixes markdown lint errors
=> chore: add markdownlint

ui/package-lock.json, ui/package.json, ui/vite.config.js
- update to use vite 3 for dev to fix websockets while running behind reverse proxy (ngrok) https://github.com/vitejs/vite/pull/6819
- update to 'official' vite-vue-2 plugin as the one we were using is no longer maintained https://github.com/underfin/vite-plugin-vue2/tree/master/#vite-plugin-vue2
=> chore: update to vite3 and official vite-vue-2 plugin

.github/workflows/integration-test.yml, test/api.sh, test/api_with_auth.sh, test/config/test-with-auth.yml, test/config/test.yml
This was an experiment, but it worked. So, opening it up for review.
This adds another run of the API shakedown tests.
In this additional pass, authentication is set to required, and the API calls are decorated with the access token generated on boot.
To achieve this, the existing API tests have been amended to put any tokens found in `FLIPT_TOKEN` env var into the auth header.
Equally, the test will also invoke a bash function (if `_api_test_hook` is defined) after Flipt has come online, but before running tests.
This allows the API with auth script a way to hook into test lifecycle to grab the bootstrapped token and export it before tests run.
=> test: add additional e2e with authentication required

.github/CODEOWNERS, .github/dependabot.yml, DEPRECATIONS.md
- setup [codeowners](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-code-owners)
- add automerge label for Docker and GH Actions dependabot updates
- Update Deprecations.md to rm `markphelps` references
=> chore: setup codeowners

.github/workflows/nightly.yml, .goreleaser.yml
gonna try this again since #1158 republished over `latest` oops
=> chore: nightly builds

cmd/flipt/main.go, go.mod, go.sum, internal/telemetry/telemetry.go, internal/telemetry/telemetry_test.go
Fixes: https://github.com/flipt-io/flipt/issues/1155
- Don't log warning if telemetry cant run for whatever reason
- Refactor telemetry a bit and push down most of the logic into telemetry package
- Shuts down telemetry if it fails to report 3 times in a row
=> fix: refactor telemetry, dont log warning if not able to report

cmd/flipt/main.go, internal/server/middleware/grpc/middleware.go, test/api.sh, test/api_with_auth.sh, test/config/test.yml
@markphelps noticed that the core auth service (list, self, getByID) was not actually mounted yet (my bad 🤦).
I added some test cases to the shakedown tests around these endpoints.
Along with mounting the service itself.
The tests should at-least avoid the regression of this in the future.
The tests:
1. create a new token.
2. list flags using that token.
3. list tokens using that token and assert token is present in list.
4. get self using token.
=> fix(auth): mount core auth service via grpc gateway

internal/config/config_test.go, internal/config/testdata/advanced.yml
The format of `cors.allowed_origins` config was changed by https://github.com/flipt-io/flipt/pull/1079 refactoring.
So I change the test case to explain the format explicitly.
Before the above change at v1.13.0, [the format with white space](https://github.com/flipt-io/flipt/commit/f06335ad5af6dd853b73b2126e550ae2b377424a#diff-6146da5455717d6d0dc2fcb1b31d8f88f3fb164a536d1bff64394511b2c0344a) worked fine since the parameter was parsed by `viper.GetStringSlice` [here](https://github.com/flipt-io/flipt/pull/1079/files#diff-9610c88fc96f562246494f72b1eaeff59e104154ccc636f919a8020506923d0fL22). But after the above change, it is parsed by `mapstructure.StringToSliceHookFunc(",")` [here](https://github.com/flipt-io/flipt/pull/1079/files#diff-54c7c1af5fa8d5db4dc49f0e8e80e93ba2b1183ba4d5c9e2e5729e6d …
=> Change test case to show the correct format of multi domains for CORS

internal/config/config.go, internal/config/config_test.go, internal/config/testdata/advanced.yml
@showwin pointed out that we regressed in terms of splitting behaviour on `allowed_origins` here:
https://github.com/flipt-io/flipt/pull/1173
Before the config refactor, we were splitting using `strings.Fields()` (this was the internal behaviour of `viper.GetStringSlice()`). Afterwards, `mapstructure.StringToSliceHook(",")` was leading to a simple `strings.Split(..., ",")`.
This adjusts the string to slice hook to use `strings.Fields(...)`.
This function treats one or more consecutive whitespace characters as a delimiter.
I added an example case to demonstrate this.
Once merged, we will cut a few patch releases on previous versions.
=> fix(config/cors): use strings.Fields for string to string slice fields

README.md
chore: update README with additional client SDKs
=> chore: update README with additional client SDKs

CHANGELOG.md, internal/config/config.go, internal/config/config_test.go, internal/config/testdata/advanced.yml
Backporting fix in #1179 onto release v1.15.
Once merged, we can cut `v1.15.2`.
=> fix(config/cors): [release/1.15] use strings.Fields for string to string slice fields (#1179)

CHANGELOG.md, internal/config/config.go, internal/config/config_test.go, internal/config/testdata/advanced.yml
This is the backport of the fix in #1179 to the 1.14 release of Flipt.
=> fix(config/cors): [release/1.4] use strings.Fields for string to string slice fields (#1179)

.github/workflows/nightly.yml, .github/workflows/release.yml, .goreleaser.nightly.yml, .goreleaser.yml
This _should_ fix the issue where creating a backport release was incorrectly also tagging the image as `latest` and pushing to our Docker registries
This removes the tagging of latest from `goreleaser` workflow and instead tags and pushes the image only if it is actually the most recent semantic release.
I tested this locally by writing a little script:
```bash
if [[ $(git tag -l --sort=-version:refname | head -n 1) == $TAG ]]; then
echo "MATCH"
else
echo "NO MATCH"
fi
```
```console
$ ./test.sh
NO MATCH
$ TAG=v1.15.1 ./test.sh
NO MATCH
$ TAG=v1.15.2 ./test.sh
MATCH
```
=> chore: only tag/push latest Docker for latest semantic tag

internal/storage/sql/testing/testing.go
I've noticed connections on cockroachdb attempting to apply migrations are getting stuck a lot during testing.
I'm unsure if this will help. However, I decided to attempt and migrate to the `wait.ForSQL` pattern for cockroach.
Just in case there is some kind of race when cockroach HTTP server is ready but SQL is in a bad state.
Example: https://github.com/flipt-io/flipt/actions/runs/3578054959/jobs/6017766294
=> fix(sql/testing): use wait.ForSQL when readying cockroach

.github/workflows/snapshot.yml
to fix
```
⨯ release failed after 0s                  error=yaml: unmarshal errors:
line 35: field nightly not found in type config.Project
Error: The process '/opt/hostedtoolcache/goreleaser-action/1.13.1/x64/goreleaser' failed with exit code 1
```
=> chore: update to use goreleaser-pro for snapshot build

.github/workflows/release.yml
Testing using similar script strategy in #1182 
```console
workspace/flipt - [main●] » TAG=refs/tags/v1.15.0 ./test.sh
NO MATCH
workspace/flipt - [main●] » TAG=refs/tags/v1.16 ./test.sh
NO MATCH
workspace/flipt - [main●] » TAG=refs/tags/v1.16.1 ./test.sh
NO MATCH
workspace/flipt - [main●] » TAG=refs/tags/v1.16.0 ./test.sh
MATCH
workspace/flipt - [main●] » git tag -l --sort=-version:refname | head -n 1
v1.16.0
```
=> chore: try to fix latest tag/push on release

.github/workflows/post-release.yml
Closes: FLI-103
Trigger deploy of try.flipt.io after each release of Flipt
=> chore(gh): deploy latest version of try.flipt.io after flipt release

.github/workflows/nightly.yml, .github/workflows/release.yml, .github/workflows/snapshot.yml
Fix issue with the nightly build: https://github.com/flipt-io/flipt/actions/runs/3643433494/jobs/6151648683#step:7:57
Pass: https://github.com/flipt-io/flipt/actions/runs/3644496837/jobs/6153804553
=> chore(build): fix nightly/all builds to install gcc

go.mod, go.sum, internal/config/authentication.go, internal/config/cache.go, internal/config/config.go, internal/config/config_test.go, internal/config/cors.go, internal/config/database.go, internal/config/deprecate.go, internal/config/deprecations.go, internal/config/log.go, internal/config/meta.go, internal/config/server.go, internal/config/tracing.go, internal/config/ui.go
Small refactor to move deprecations checking into its own step in the config parsing
- creates `deprecation` type to hold field name and any additional message`
- creates `deprecator` interface to check if any fields are deprecated and return a slice of `deprecations` that will be appended to warnings on the config
- removes the need to return `[]string` in the `setDefaults` method/interface
=> chore: refactor deprecations checking to own method

CHANGELOG.md, DEPRECATIONS.md, cmd/flipt/main.go, internal/config/cache.go, internal/config/config.go, internal/config/config_test.go, internal/config/testdata/advanced.yml, internal/config/testdata/deprecated/ui_disabled.yml, internal/config/ui.go
Re: FLI-125
- Refactors config parsing to separate out `Warnings` from the `Config` itself, making it easier to write tests against config parsing
- Deprecates `ui.enabled` as in the future we will have 2 versions of Flipt:
1. Current version where UI is always enable
2. Headless version which is API only
=> feat: deprecate ui enabled

.github/workflows/integration-test.yml, .github/workflows/nightly.yml, .github/workflows/release-clients.yml, .github/workflows/release.yml, .github/workflows/snapshot.yml
use fresh minted GITHUB_TOKEN when calling `setup-task` in workflows to avoid GitHub rate limits causing jobs to fail
ex: https://github.com/flipt-io/flipt/actions/runs/3832718965/jobs/6523354201#step:6:5
https://github.com/arduino/setup-task#repo-token
=> chore: use minted GITHUB_TOKEN for task setup to avoid ratelimits

cmd/flipt/main.go, go.mod, internal/release/check.go, internal/release/check_test.go
- Performs some refactoring i've wanted to do for awhile, moving the release / version check mechanism out of main (mostly) and adding some tests around it
- Also checks for `rc` in version to determine if its a proper release or not
=> chore: Release check refactor

.github/workflows/post-release.yml, .github/workflows/release-clients.yml
Try to fix the following workflows to run after the `release` workflow succeeds:
- `release-clients` (updates grpc clients if necessary)
- `post-release` (performs other post release tasks, currently updating `try.flipt.io`)
This updates these workflows to be triggered on [workflow_run](https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#workflow_run)
For whatever reason they were not being triggered using the `release` trigger
=> chore: try to fix post release workflows to trigger

.github/workflows/post-release.yml, .github/workflows/release-clients.yml
Follow up to #1271 
I forgot that we don't always create releases from the `main` branch, so these workflows wouldn't always fire :(
=> chore: rm branch from post release workflows

internal/cmd/http.go, internal/gateway/gateway.go, test/api.sh
Fixes FLI-176
This fixes the case where the `/meta` prefixed endpoints would return `500` (and panic server-side) when authentication was required and no authentication was provided.
Additionally, this only occurred when the `Accept` header was explicitly set to `application/json`.
The accept header caused the `HttpBodyMarshaler` to be invoked. When authentication was not provided, the resulting body was an error and not the expected `HttpBody` instance. This marshaller was fallback to an embedded marshaller in this instance. This wasn't being set and was therefore `nil`, causing a panic at runtime.
Update: After reflecting on the behaviour that this only failed when the `Accept` header was presented, I looked into whether you need to explicitly set the `HttpBodyMarshaler` and it turns …
=> fix(meta): remove `runtime.HttpBodyMarshaler` from gateway stack

.devcontainer/devcontainer.json, DEVELOPMENT.md, config/local.yml, internal/cmd/http.go, magefile.go, ui/doc.go, ui/embed.go, ui/index.html
This takes advantage of https://vitejs.dev/guide/backend-integration.html and allows us to still load the UI on port `:8080` when developing while taking advantage of hot reloading provided by Vite.
The instructors are updated in `DEVELOPMENT.md`, but basically the steps are:
1. Run `npm run dev` where you have the `flipt-ui` repository checked out. This will start a development server on port `5173` and proxy API requests to the Flipt API on port `8080`.
2. Run `mage dev` from the this repository. This will create a dev build that will serve the UI from the development server, while still making it accessible on port `8080`.
3. Run the binary with the local config: `./bin/flipt --config ./config/local.yml`. This will enable CORS with the correct configuration and start the server on port …
=> chore: make UI dev easier

internal/cmd/http.go
We're currently generating and setting the CSRF token to empty string when a key is not configured.
This ensures we only generate and set a token if configured to do so.
=> fix(csrf): dont attempt to create CSRF token when key is not defined

magefile.go
Fixes `bootstrap` command to run in `_tools` directory when installing tools
=> fix: mage bootstrap command

internal/cmd/grpc.go
Noticed this when shutting down the latest rc release:
```
^C2023-01-20T20:45:46Z	INFO	shutting down...
2023-01-20T20:45:46Z	INFO	shutting down HTTP server...	{"server": "http"}
2023-01-20T20:45:46Z	INFO	shutting down GRPC server...	{"server": "grpc"}
2023-01-20T20:45:46Z	INFO	shutting down grpc server...	{"server": "grpc"}
```
This PR removes the last line (duplicate message)
=> chore: rm duplicate grpc shutdown log

.github/workflows/release.yml
the change in #1182 broke the creation of the docker multi-arch manifest, since tagging/pushing via docker via the CLI only tags and pushes the image for the architecture on which its run
this requires us to then go back and manually fix the `latest` tag to be the correct multiarch manifest
Im proposing we remove this stage for now until we come up with a better solution of properly creating / pushing multiarch manifests only if this is the latest semantic verison
=> chore: remove tag/push latest for now

internal/cmd/http.go
Fixes: FLI-178
Sets [`Content-Security-Policy`](https://developer.mozilla.org/en-US/docs/Web/HTTP/CSP) header to `"default-src 'self'; img-src *;"` which defaults to only allow resources, scripts, etc from this host, but allows images from anywhere per: https://developer.mozilla.org/en-US/docs/Web/HTTP/CSP#examples_common_use_cases
See also: https://infosec.mozilla.org/guidelines/web_security#content-security-policy
Also sets [`X-Content-Type-Options`](https://infosec.mozilla.org/guidelines/web_security#x-content-type-options) as well
I am a bit concerned about breaking some functionality since there are some warnings in the browser, however it doesn't seem to actually affect anything during the light testing I've done:
One option is it make these opt-in, or maybe opt out? Although …
=> feat: set csp and content-type-options headers

.golangci.yml
```
mage lint
Linting...
WARN [runner] The linter 'structcheck' is deprecated (since v1.49.0) due to: The owner seems to have abandoned the linter.  Replaced by unused.
WARN [runner] The linter 'scopelint' is deprecated (since v1.39.0) due to: The repository of the linter has been deprecated by the owner.  Replaced by exportloopref.
WARN [runner] The linter 'deadcode' is deprecated (since v1.49.0) due to: The owner seems to have abandoned the linter.  Replaced by unused.
WARN [runner] The linter 'varcheck' is deprecated (since v1.49.0) due to: The owner seems to have abandoned the linter.  Replaced by unused.
WARN [runner] Can't run linter goanalysis_metalinter: goimports: can't extract issues from gofmt diff output "--- /Users/markphelps/workspace/flipt/rpc/flipt/auth/auth.pb.go.orig\t202 …
```
=> fix: get linter running correctly locally

cmd/flipt/main.go, internal/config/config_test.go, internal/config/log.go, internal/config/testdata/advanced.yml
Fixes FLI-148
Fixes https://github.com/flipt-io/flipt/issues/1252
Adds support for custom keys in log output for:
- time
- level
- message
Each key can be configured under the `log.keys` object in the configuration.
Using the following Flipt configuration I get the subsequent logging output format:
config.yaml:
```yaml
log:
level: DEBUG
encoding: json
keys:
time: "time"
level: "level"
message: "msg"
```
Flipt output:
```json
{"level":"INFO","time":"2023-01-27T12:39:30Z","msg":"flipt starting","version":"dev","commit":"","date":"","go_version":"go1.19.5"}
{"level":"DEBUG","time":"2023-01-27T12:39:30Z","msg":"not a release version, disabling telemetry"}
{"level":"DEBUG","time":"2023-01-27T12:39:30Z","msg":"local state directory exists","path":"/Users/georgemac/Library/Application …
```
=> feat(logging): support custom time, level and message keys

cmd/flipt/main.go, internal/cmd/http.go, internal/info/flipt.go
Fixes: FLI-191
Don't set CSP header when running in development mode (version == "dev")
In the future I'd like to switch to some kind of 'mode' based logic, where we can more easily tell if Flipt is running locally for our development vs running in 'release' mode
=> fix: disable csp headers in non-release mode for ui dev

examples/tracing/docker-compose.yml, internal/cmd/grpc.go, internal/config/tracing.go, internal/server/evaluator.go, internal/server/flag.go, internal/server/otel/attributes.go, internal/server/otel/noop_exporter.go
Fixes: FLI-194
Adds some telemetry span attributes for the `Evaluate` and `GetFlag` endpoints
=> Otel improvements

internal/cmd/grpc.go, internal/info/flipt.go, internal/storage/sql/common/evaluation.go, internal/storage/sql/common/flag.go, internal/storage/sql/common/rule.go, internal/storage/sql/common/segment.go, internal/storage/sql/db.go, internal/storage/sql/db_internal_test.go
This is kind of a doozy so bear with me. 🐻
This came about while I was looking at our StackHawk scans in reference to FLI-177.
Basically, StackHawk issues a bunch of concurrent queries to probe our app for security concerns, SQL injections, etc.
When I was running this locally (using the SQLite DB for Flipt), I kept running into these 500 errors:
```console
ERROR	finished unary call with code Internal	{"server": "grpc", "grpc.start_time": "2023-01-27T15:40:34-05:00", "system": "grpc", "span.kind": "server", "grpc.service": "flipt.Flipt", "grpc.method": "GetRule", "peer.address": "127.0.0.1:63802", "error": "rpc error: code = Internal desc = database is locked", "grpc.code": "Internal", "grpc.time_ms": 5191.929}
```
```
database is locked
```
Being the relevant bit.
In looking into this …
=> fix/feat: use joins instead of n+1/opening multiple connections

config/flipt.schema.cue, config/flipt.schema.json
=> chore: add new log keys to config schemas

internal/server/flag.go, internal/server/flag_test.go, internal/server/rule.go, internal/server/rule_test.go, internal/server/segment.go, internal/server/segment_test.go
Fixes: FLI-189
- Prevent 500
- Don't expose invalid base64 decode error to user if bad `pageToken`
```
curl -v "http://localhost:8080/api/v1/flags/flagKey/rules?limit=10&offset=10&pageToken=pageToken"
< HTTP/1.1 500 Internal Server Error
< Content-Type: application/json
< Vary: Origin
< X-Content-Type-Options: nosniff
< Date: Fri, 27 Jan 2023 20:26:02 GMT
< Content-Length: 72
{"code":13,"message":"illegal base64 data at input byte 8","details":[]}%     
```
```
curl -v "http://localhost:8080/api/v1/flags/flagKey/rules?limit=10&offset=10&pageToken=pageToken"
< HTTP/1.1 400 Bad Request
< Content-Type: application/json
< Vary: Origin
< Date: Thu, 02 Feb 2023 21:16:11 GMT
< Content-Length: 70
{"code":3,"message":"pageToken is not valid: \"pageToken\"","details":[]}%     
```
=> fix: 500/ dont expose invalid base64 decode error for page token

internal/cmd/http.go
Fixes: FLI-190
Adds missing `frame-ancestors` directive to `Content-Security-Policy` response header to prevent clickjacking
https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/frame-ancestors
=> chore: add frame-ancestors directive to CSP header

DEPRECATIONS.md, config/default.yml, config/flipt.schema.cue, config/flipt.schema.json, internal/cmd/grpc.go, internal/config/cache.go, internal/config/config.go, internal/config/config_test.go, internal/config/deprecations.go, internal/config/testdata/advanced.yml, internal/config/testdata/deprecated/tracing_jaeger_enabled.yml, internal/config/tracing.go
Fixes: FLI-197
Fixes: #1310 
Deprecates `tracing.jaeger.enabled` in favor of:
```yaml
tracing:
enabled: true
backend: jaeger
```
=> feat/proposal: Deprecate jaeger enabled

internal/cleanup/cleanup.go, internal/cleanup/cleanup_test.go, internal/config/authentication.go
It was observed that OIDC method-created authentications were not getting cleared away.
The `cleanup` process when created was hardcoded to only perform cleanup for `METHOD_TOKEN` (mistakenly).
This was an easy mistake (not registering the method in all the places). It was why I added the generic method container and the `AllMethods()` support to ensure that adding new methods was as simple as ensuring the methods returns it info here:
https://github.com/flipt-io/flipt/blob/6144f3244c61b9987c8a2ac5e837840fbc051d3b/internal/config/authentication.go#L168-L171
The types should depend on performing background operations of this `AllMethods()` list. Instead of having to manually add new methods everywhere they're created.
However, I never updated `cleanup` to take advantage of this.
This …
=> fix(cleanup): ensure all methods register their cleanup schedules

internal/cmd/auth.go, internal/server/auth/http.go, internal/server/auth/http_test.go, test/api.sh
Supports https://github.com/flipt-io/flipt/issues/1334
I believe there might exist a deeper experience issue with the UI's handling of entering an unauthenticated state.
However, as pointed out, the expire token self endpoint is an _authenticated_ route.
This means we can only expire a valid (non-expired) authenticated request.
I believe this is correct and fair behaviour. Because the operation is a mutating and destructive action that should only be performed by an authenticated party.
That said though, I think it might be prudent to instruct the user agent to actually expire the _cookie_ in all cases where a token is presented via a Cookie header, but that leads to an unauthenticated response.
I suspect this might not actually fix the whole end-to-end problem in #1334 but I think it is …
=> test(auth): ensure failed cookie auth attempt instructs user-agent to clear cookie

internal/cleanup/cleanup.go
`Cleanup for auth method not defined (skipping)` -> `cleanup for auth method not defined (skipping)`
=> chore: downcase log for cleanup skipped

go.mod, go.sum
It removes the replace directive for Docker libs when testcontainers-go 0.170 was added
In testcontainers-go 0.18.0, the dependencies have been fixed.
Do not use fixed version of Docker that is outdated
=> chore: fix dependencies after testcontainers-go bump

internal/cmd/auth.go, internal/config/authentication.go, internal/config/config_test.go, internal/config/testdata/advanced.yml, internal/server/auth/method/kubernetes/server.go, internal/server/auth/method/kubernetes/server_internal_test.go, internal/server/auth/method/kubernetes/server_test.go, internal/server/auth/method/kubernetes/testing/grpc.go, internal/server/auth/method/kubernetes/testing/http.go, internal/server/auth/method/kubernetes/verify.go
Depends on https://github.com/flipt-io/flipt/pull/1341 ✅ 
Fixes FLI-210
Fixes FLI-211
This PR is the core of the implementation of the VerifyServiceAccount authentication method RPC call.
The purpose of this call is to verify a supplied service account against the OIDC configuration of a trusted kubernetes cluster. Given the token is valid then it is used to create an authentication and associated client token in the backing authentication storage implementation.
This PR includes both the implementation and the installation of the method into the gRPC and HTTP servers.
It also includes a fix to the defaults for both CA path and Issuer URL.
The CA path was incorrectly prefixed with `.cert` and it needed to be `.crt`.
The Issuer URL default includes the prefix `.cluster.local` in the …
=> feat(auth/k8s): initial auth method service implementation

internal/ext/exporter.go, internal/ext/exporter_test.go, internal/server/middleware/grpc/support_test.go, internal/server/rule.go, internal/server/rule_test.go, internal/server/support_test.go, internal/storage/sql/common/flag.go, internal/storage/sql/common/rule.go, internal/storage/sql/common/segment.go, internal/storage/sql/flag_test.go, internal/storage/sql/rule_test.go, internal/storage/sql/segment_test.go, internal/storage/storage.go
Fixes: FLI-245
Like #1369 but for `rules`
=> feat: (sqlite) add namespace support for rules storage

cmd/flipt/export.go, cmd/flipt/import.go, go.work.sum, internal/storage/sql/migrator.go
When working on #1396 I saw that if you tried to run import using cockroachDB you would get a nil pointer error. This is because we never added `cockroachDB` to the switch statement for import/export commands.. oops
=> fix: import for cockroach db

internal/cmd/auth.go, internal/cmd/http.go, internal/gateway/gateway.go, internal/server/auth/method/kubernetes/testing/http.go, internal/server/auth/method/oidc/testing/http.go, rpc/flipt/marshaller.go, test/api.sh
Currently, we return a very "go" specific type of error messaging when body inputs fail to unmarshal against the protobuf schema:
```
{
"code": 3,
"message": "json: cannot unmarshal bool into Go value of type map[string]json.RawMessage",
"details": []
}
```
This error messaging does not really tell users what is going on with their inputs to the API, so this PR serves to change the error messaging to something like the following:
```
{
"code": 3,
"message": "invalid values for key(s) in json body",
"details": []
}
```
Fixes: FLI-129
Fixes: FLI-130
=> fix: return better error messages for grpc-gateway errors

sdk/go/CHANGELOG.md, sdk/go/go.mod
This prepares the release of sdk/go to version `v0.1.1`.
It includes fixes to transient dependency versions.
=> feat(sdk/go): prepare release v0.1.1

hack/build/integration/integration.go, hack/build/integration/integration_test.go, hack/build/internal/test/integration.go, rpc/flipt/flipt.pb.gw.go, rpc/flipt/flipt.yaml, sdk/go/flipt.sdk.gen.go, sdk/go/http/flipt.sdk.gen.go
Fixes FLI-279
Fixes FLI-277
Fixes FLI-228
This PR contains a few changes:
1. ~It merges `main` into `namespaces` branch.~ (Did this separately).
2. Defines the gateway routes for the Namespaces RPCs.
3. Updates the integration tests for Namespaces:
It updates the integration tests to run both with and without a namespace key.
Effectively testing the API both in the default namespace and an explicit namespace.
When a namespace key is provided, it first tests the namespaces RPC and in doing so creates a namespace to then be used as a scope for the rest of the Flipt APIs.
Namespace is now an outler loop around the integration test matrix.
Meaning we test the combination of: Namespace x Transport x Authentication.
Leading to 8 runs of the entire suite in each of the various configurations.
=> feat(hack/build): add cases for namespace scoped integration tests

.github/workflows/release-clients.yml
Following along with this guide here: https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#running-a-workflow-based-on-the-conclusion-of-another-workflow
This changes the trigger to look for `event_name == workflow_run` and it only triggers when the conclusion of the previous run was successful.
=> fix(github): use event name workflow_run and conclusion

config/migrations/sqlite3/7_namespaces_relationships.up.sql
While poking around in the namespaces branch I noticed that a migration (over `sqlite`) with state led to `variants`, `rules` and `distributions` getting dropped during migration.
This appears to be due to the fact that we're performing a copy and then drop table by table.
When we drop parent tables their cascading deletes are taking effect and whiping these referencing tables before we even get to migrating them.
This change makes it so that we create and copy all tables into temp tables first, before we drop and rename at the end of the migration. When we define the temporary table, any references also reference the other temporary tables. SQLite appears to correctly rename these references when the tables are renamed. This protects each table from the original table getting dropped.
1. …
=> fix(migrations/sqlite): reorder to ensure we copy all data before drop

hack/build/integration/integration.go, internal/storage/sql/common/rule.go, internal/storage/sql/evaluation_test.go, internal/storage/sql/mysql/mysql.go, internal/storage/sql/postgres/postgres.go, internal/storage/sql/rule_test.go, internal/storage/sql/sqlite/sqlite.go, rpc/flipt/flipt.pb.gw.go, rpc/flipt/flipt.yaml, sdk/go/http/flipt.sdk.gen.go
Since the addition of `namespace`s, we want to disallow users or remove our system of namespaced related errors. One scenario we would like to prevent all together is the ability for someone to link two entities of different namespaces.
Due to the introduction of the `NamespaceKey` in most entity models within our protobuf definition, we can only check things or create things in the namespace provided within the request. This will disallow users from mixing namespaces for creating a rule.
Nonetheless, in this PR I check to see that, you can not create a rule for entities that do not exist in a namespace.
For `distribution`s, in the db layer, the `rule_id` and `variant_id` are uniquely identified via a UUID (Primary Key). It would not make too much sense to uniquely identify it with the …
=> feat: add checks and tests for potential `namespace`d related failures

internal/server/evaluator.go, internal/server/metrics/metrics.go
Fixes: FLI-292
Adds missing namespace metrics for prometheus, the spanAttrs were added in previous PRs
=> chore: add missing namespaces metrics

go.mod, internal/cmd/protoc-gen-go-flipt-sdk/http.go, sdk/go/http/auth.sdk.gen.go, sdk/go/http/flipt.sdk.gen.go
The current http sdk client fails with requests against Flipt instances that are namespace aware (according to the proto definitions). We start to see errors like the following:
```
$ go run main.go
This is the error:  proto: (line 1:167): unknown field "namespaceKey"
```
This is because the http client does not know what to do with unknown fields when it goes to decode the output back out to the user. This change introduces a `DiscardUnknown` Unmarshal option, so the client can know what to do with unknown fields relative to the protobuf definition.
=> fix: protojson to use DiscardUnknown option for backwards compatibility

internal/ext/importer.go, rpc/flipt/validation.go, rpc/flipt/validation_test.go
Writing validation logic for particular namespace requests. We want to disallow the creation of some namespaces based on inputs, mainly one could create a namespace, without this change, with backslashes. A namespace created with backslashes confuses the UI since it is included in the path of subsequent namespace requests.
Fixes FLI-300
Fixes FLI-299
=> chore: validation logic for namespace requests

hack/build/testing/integration/readonly/readonly_test.go, internal/ext/importer.go
Supports FLI-300
This ensures namespaces created via `import --create-namespace` use the provided namespace key as the name.
There is another issue that create namespace succeeds even with a blank name which will be fixed in another PR.
This is simply to enure import passes a name on namespace creation.
=> fix(cmd/import): pass namespace key as name on create

.github/workflows/lint.yml, CHANGELOG.md
- update changelog for future namespace release
- add mage proto lint check
=> chore: update changelog for future namespace release; add mage proto lint check

go.mod, sdk/go/CHANGELOG.md, sdk/go/go.mod
Preparing release of `sdk/go` v0.2.0.
=> chore(sdk/go): upgrade rpc/flipt to v1.20.0

.github/workflows/release.yml, .goreleaser.yml
1. Installs `mage` into the release workflow.
2. Prepends all images with `v` now that gorelease strips it.
=> fix(github): install mage in release and prepend tag with v

CHANGELOG.md
chore: update changelog for 1.20 release
=> chore: update changelog for 1.20 release

.github/workflows/devcontainer.yml
trying to fix this error:
```
The push refers to repository [ghcr.io/flipt-io/flipt-devcontainer]
denied: installation not allowed to Create organization package
```
Moving to a repo scoped package which the action should have permissions to create
=> chore: move devcontainer image to be repo-scoped

sdk/go/README.md, sdk/go/defaults.go, sdk/go/doc.go, sdk/go/example_test.go
- Adds a constant `DefaultNamespace`.
- Updates `doc.go` examples to demonstrate passes `NamespaceKey`.
- Adds a client <-> server compatability documentation section to README.md.
Fixes: FLI-314
=> chore(sdk/go): update docs examples to reference namespaces

Dockerfile
Fixes error when building local Dockerfile:
```
=> CACHED [build 6/9] COPY go.sum .                                                                                                  0.0s
=> ERROR [build 7/9] RUN go mod download                                                                                            13.2s
------
> [build 7/9] RUN go mod download:
#15 13.15 go: go.flipt.io/flipt/errors@v1.19.3 (replaced by ./errors/): reading errors/go.mod: open /home/flipt/errors/go.mod: no such file or directory
```
=> chore: fix Dockerfile go mod download step

internal/server/middleware/grpc/support_test.go
As test were ran in CI, the "mock" sink did not have a `String` method for zap to call. It resulted in a `panic` in the log output. This fixes the issue.
=> chore: fix stringer error

internal/server/audit/audit.go, internal/server/audit/audit_test.go, internal/server/auth/server.go, internal/server/auth/server_test.go, internal/server/middleware/grpc/middleware.go, internal/server/middleware/grpc/middleware_test.go
Modify event structure to have `action` and `type` as top level fields. Also add timestamp to the event structure.
=> feat: make changes to audit event structure

.goreleaser.nightly.yml
Add those `v` prefixes back for the nightly images
=> chore: Update .goreleaser.nightly.yml

cmd/flipt/validate.go, internal/cue/validate.go
Introduce `format` flag for the `flipt validate` command.
Text format (failure):
```
$ ./bin/flipt validate features.yml
❌ Validation failure!
- Message: invalid value "flag1..." (out of bound =~"^[-_,A-Za-z0-9]+$")
File   : features.yml
Line   : 2
Column : 11
- Message: invalid value 110 (out of bound <=100)
File   : features.yml
Line   : 27
Column : 23
```
JSON format (failure piped through `jq`):
```
$ ./bin/flipt validate features.yml --format=json | jq
{
"errors": [
{
"message": "invalid value \"flag1...\" (out of bound =~\"^[-_,A-Za-z0-9]+$\")",
"location": {
"file": "features.yml",
"line": 2,
"column": 11
}
},
{
"message": "invalid value 110 (out of bound <=100)",
"location": {
"file": "features.yml",
"line": 27,
"column": 23
}
}
]
}
```
Text format (success):
```
$ ./bin/flipt …
```
=> feat: add text and json format option for output on `flipt validate` command

internal/storage/sql/common/segment.go, internal/storage/sql/segment_test.go
Fixes #1653 
This fixes a bug where a segments with constraints existing before version 1.22 are now failing due to their constraint descriptions returning a `NULL`. We were attemping to parse the `NULL` into a string field.
This updates the scan to use a `sql.NullString` for constraint desciption on `GetSegment`.
=>  fix(storage/sql): handle null description on constraint during GetSegment

cmd/flipt/import.go
Fixes: FLI-378
`flipt import` panics if filename not provided correctly
```
workspace/flipt - [fix-import-filename-check] » ./bin/flipt import --config /tmp/flipt.yaml
panic: runtime error: index out of range [0] with length 0
goroutine 1 [running]:
main.(*importCommand).run(0x1400003d2c0, 0x140006a8f00, {0x1400046c0c0, 0x0, 0x0?})
go.flipt.io/flipt/cmd/flipt/import.go:87 +0x8b0
github.com/spf13/cobra.(*Command).execute(0x140006a8f00, {0x1400046c080, 0x2, 0x2})
github.com/spf13/cobra@v1.7.0/command.go:940 +0x5c8
github.com/spf13/cobra.(*Command).ExecuteC(0x140006a8600)
github.com/spf13/cobra@v1.7.0/command.go:1068 +0x35c
github.com/spf13/cobra.(*Command).Execute(...)
github.com/spf13/cobra@v1.7.0/command.go:992
github.com/spf13/cobra.(*Command).ExecuteContext(...) …
```
=> fix: panic if no import file name provided

codecov.yml, examples/audit/docker-compose.yml, examples/authentication/dex/docker-compose.yml, examples/authentication/proxy/docker-compose.yml, examples/basic/docker-compose.yml, examples/database/cockroachdb/docker-compose.yml, examples/database/mysql/docker-compose.yml, examples/database/postgres/docker-compose.yml, examples/metrics/docker-compose.yml, examples/nextjs/docker-compose.yml, examples/openfeature/docker-compose.yml, examples/redis/docker-compose.yml, examples/tracing/jaeger/docker-compose.yml, examples/tracing/otlp/docker-compose.yml, examples/tracing/zipkin/docker-compose.yml
s/`FLIPT_META_TELMETRY_ENABLED`/`FLIPT_META_TELEMETRY_ENABLED`/g
=> chore: fix telemetry typo; add build to codecov ignore

ui/src/components/namespaces/NamespaceForm.tsx
catches errors on namespaces form if namespaces API returns err
more: https://redux-toolkit.js.org/api/createAsyncThunk#unwrapping-result-actions
1. shutdown backend server (API)
2. try to create namespace
3. see the success msg even though nothing was created
1. shutdown backend server (API)
2. try to create namespace
3. proper err message
=> fix: catch errs on call to namespaces API in namespace form

build/testing/integration.go, internal/cmd/grpc.go, internal/config/config.go, internal/config/config_test.go, internal/config/experimental.go, internal/config/testdata/advanced.yml, internal/config/testdata/storage/git_basic_auth_invalid.yml, internal/config/testdata/storage/git_provided.yml, internal/config/testdata/storage/invalid_git_repo_not_specified.yml, internal/config/testdata/storage/local_provided.yml
Fixes FLI-396
This gives us the ability to create conditionally enabled and disabled configuration sections.
Giving us the ability to feature toggle entire sections within flipt via the `experimental` section of the config file.
Making a section experimental is done by adding a struct tag `experiment:"<key>"` where `key` is the `mapstructure` key for the `ExperimentalFlag` defined within the `ExperimentalConfig`. By connecting these dots the config parser will lookup whether or not a flag is in an enabled state and if not, set the config target to it's zero value.
This PR also adds a experimental guard around the new `storage` section.
https://github.com/flipt-io/flipt/blob/eb1ee40e9047ea3805829a52cdefc40d5885603e/internal/config/experimental.go#L6
Note that there is one flag currently …
=> feat(config): add support for experimental configuration and features

.golangci.yml, internal/storage/sql/common/segment.go, internal/storage/sql/flag_test.go, internal/storage/sql/segment_test.go
fixes bug where we werent using the `namespace_key` when looking up constraints for segments
=> fix: cross namespaced constraints

build/testing/cli.go
This ensures that the user default configuration directory is supported.
It does so by starting Flipt process in a background process, sleeping for 2 seconds, sending a SIGTERM to start a graceful shutdown and then propagating the background processes exit code from the script.
=> test(cli): ensure user configuration path supported

build/testing/integration/api/api.go, build/testing/integration/api/api_test.go, build/testing/integration/readonly/readonly_test.go, internal/cmd/auth.go
Fixes FLI-402
This initial WIP defines the failing tests for this issue.
Currently, we're not mounting the authentication endpoints when auth is configured as not required in the filesystem backends work. This leads to both the public and self endpoints to not be reachable (404).
The frontend expects these endpoints to be present. Also, we have a (somewhat) feature, which is that you can still list authentication entries when all of the auth subsystem is disabled. Given there happen to have previously been authentication credentials entered into backing database.
In order to continue supporting this, we're going to connect to the database whenver the database backend is configured for flag storage. However, in order to support not attempting DB connections with the new git and local …
=> test(integration): ensure public and auth self routes are reachable

build/internal/ui.go
the `node:18` tag recently was bumped up to be based on debian `bookworm`, which apparently playwright doesn't like (see: https://github.com/flipt-io/flipt/actions/runs/5257503513/jobs/9500375823)
this pins us to the previous version that we were using `bullseye` for our UI ITs
https://hub.docker.com/layers/library/node/18/images/sha256-d0afe9aa33273de0aa336cc70844be7ba9f0c82deb6c06a07d4d8e01ec11f750?context=explore
We could consider looking into what it would take to get playwright to work with this newer version.. or just carry on with using bullseye for now
=> chore: fix Dagger UI build as node-18 bumped to a different base image

internal/cmd/http.go
I noticed that OIDC authentication was broken with the message `{"code":13,"message":"handling OIDC callback: Provider.Exchange: authentication request state and authorization state are not equal: invalid parameter","details":[]}`, beginning with the changes from https://github.com/flipt-io/flipt/pull/1754. 
This fix stops the `http.Request.URL` struct from being overwritten to preserve the query data.
EDIT: Just realised that this is the same change that @GeorgeMac suggested (https://github.com/flipt-io/flipt/pull/1754#discussion_r1230635329)
=> fix: prevent overwriting URL struct

build/testing/integration/readonly/readonly_test.go
In this PR there is a fix for this issue: https://github.com/flipt-io/flipt/pull/1784
This adds a check to each of the list integration tests we have to actually check the page size.
So far this test has been ensuring that after a full walk the result is the entire contents of Flipt.
However, it wasn't ensuring that each page was exactly the size of the explicit limit.
The trailing slash code is stripping all the query parameters, but this test passed because the result is still the entire contents of Flipt being returned.
I will get this merged once it is rebased on the fix provided by @MattNotarangelo.
=> test(integration): ensure all list limits are enforced correctly

build/testing/integration/api/api.go, build/testing/integration/readonly/readonly_test.go, build/testing/integration/readonly/testdata/default.yaml, build/testing/integration/readonly/testdata/production.yaml
Fixes FLI-463
This PR ensures that `Evaluation.Variant` works as expected in both the `api` and `readonly` suites.
It uses the new SDK types to exercise this API to ensure the variant endpoint is compatible with the existing Evaluation RPC on the Flipt service. It also adds a few cases to ensure some of the negative cases (flag disabled, not found and so on).
=> test(integration): ensure Evaluation.Variant returns as expected

.goreleaser.yml
https://goreleaser.com/deprecations/#archivesreplacements
This caused the nightly build to fail: https://github.com/flipt-io/flipt/actions/runs/5415977052/jobs/9845050343
=> chore: fix deprecated archive replacement

build/testing/integration/readonly/testdata/production.yaml, cmd/flipt/validate.go, internal/cue/fixtures/invalid.yaml, internal/cue/validate.go, internal/cue/validate_test.go
Fixes: FLI-467
Fixes `validate` command to:
1. return proper location of error, not just the location of the parent/entrypoint
2. provide more helpful error messages around what field is invalid
Slight refactor as well to hopefully make writing more tests easier in the future
```yaml
rollout: 50
rollout: 50
- variant: variant_002
- variant: variant_002
rollout: 50
rollout: 50
- key: flag_004
- ey: flag_004
name: FLAG_004
name: FLAG_004
description: Some Description
description: Some Description
enabled: true
nabled: true
variants:
variants:
- key: variant_001
- key: variant_001
name: VARIANT_001
name: VARIANT_001
```
```
$ ./bin/flipt validate -F json input.yaml | jq
{
"errors": [
{
"message": "field not allowed",
"location": {
"file": …
```
=> fix: Fix validate command

README.md, ui/src/components/Footer.tsx
Might get more 👀 on https://features.flipt.io/
=> chore: add feedback link to app footer

internal/storage/fs/snapshot.go, internal/storage/sql/common/util.go, internal/storage/sql/errors.go
chore: use common aliases for flipt/errors pkg
=> chore: use common aliases for flipt/errors pkg

.pre-commit-config.yaml, DEVELOPMENT.md
- adds instructions on installing of [pre-commit](https://pre-commit.com/hooks.html) which allows us to define (and even create) Git hooks
- adds `conventional-pre-commit` hook to verify conventional commit msg
- adds section on using Conventional Commits in the Development.md file
This is currently opt-in, as the dev would need to run the following for this to have any effect:
- `pip install pre-commit` or `brew install pre-commit`
- `pre-commit install`
In the future we could consider making it part of the `bootstrap` step
=> chore: Pre commit hook

internal/cue/fixtures/valid.yaml, internal/cue/flipt.cue, internal/ext/importer_test.go, internal/ext/testdata/import.yml, internal/ext/testdata/import_no_attachment.yml
allow for variant description in `flipt validate`
=> fix: support variant desc in cue import schema

CHANGELOG.md
changelog for v1.23.3
includes `flipt validate` fixes
=> chore: v1.23.3

ui/src/app/flags/EditFlag.tsx, ui/src/app/flags/Evaluation.tsx, ui/src/app/flags/Flag.tsx, ui/src/app/flags/rollouts/Rollouts.tsx, ui/src/app/segments/Segment.tsx, ui/src/components/TabBar.tsx, ui/src/components/flags/FlagTable.tsx, ui/src/components/flags/RolloutForm.tsx, ui/src/components/forms/Combobox.tsx, ui/src/components/forms/Select.tsx, ui/src/components/rollouts/RolloutForm.tsx, ui/src/components/rollouts/rules/ThresholdRuleForm.tsx, ui/src/components/rules/EditRuleForm.tsx, ui/src/components/rules/RuleForm.tsx, ui/src/components/rules/distributions/SingleDistributionForm.tsx, ui/src/components/segments/ConstraintForm.tsx, ui/src/components/segments/SegmentTable.tsx, ui/src/data/api.ts, ui/src/types/Constraint.ts, ui/src/types/Flag.ts, ui/src/types/Rollout.ts, ui/src/types/Variant.ts
Fixes: FLI-474
adds ability to create a rollout threshold rule with percentage/value
don't have list/delete/update yet.. but those are to come next
also adds `type` to Flag Table:
=> feat: create eval rollout threshold

ui/src/app/namespaces/namespacesSlice.ts
fixes: FLI-482
```
Selector selectNamespaces returned a different result when called with the same parameters. This can lead to unnecessary rerenders.
Selectors that return a new reference (such as an object or an array) should be memoized: https://redux.js.org/usage/deriving-data-selectors#optimizing-selectors-with-memoization 
Object { state: {…}, selected: (2) […], selected2: (2) […] }
```
<https://redux.js.org/usage/deriving-data-selectors#optimizing-selectors-with-memoization>
=> fix(ui): memoize selectors for namespaces

ui/src/app/console/Console.tsx
=> fix: broken ui build

internal/server/audit/audit.go, internal/server/audit/types.go, internal/server/middleware/grpc/middleware.go, internal/server/middleware/grpc/middleware_test.go
Add audit logging for `rollout` type, for the `create`, `update`, and `delete` action.
Completes FLI-457
=> feat: add audit logging for rollout actions

build/testing/integration/readonly/readonly_test.go, internal/server/rollout.go, internal/storage/fs/fixtures/fswithindex/prod/prod.features.yml, internal/storage/fs/fixtures/fswithindex/sandbox/sandbox.features.yaml, internal/storage/fs/fixtures/fswithoutindex/prod/features.yml, internal/storage/fs/fixtures/fswithoutindex/prod/prod.features.yaml, internal/storage/fs/fixtures/fswithoutindex/staging/features.yml, internal/storage/fs/fixtures/fswithoutindex/staging/sandbox/features.yaml, internal/storage/fs/fixtures/fswithoutindex/staging/sandbox/sandbox.features.yml, internal/storage/fs/fixtures/fswithoutindex/staging/staging.features.yaml, internal/storage/fs/snapshot.go, internal/storage/fs/snapshot_test.go, internal/storage/fs/sync.go, internal/storage/sql/common/rollout.go, internal/storage/sql/flag_test.go, internal/storage/sql/rollout_test.go
Adds FS store implementation for rollouts. There are a few things happening here:
1. Adding the logic to account for rollouts off of the `yml` files for FS
2. Adding unit tests for the FS implementation
3. Adding integration tests for the read only suite that will evaluate boolean/batch on the eval-v2 routes
Completes FLI-455
Completes FLI-419
=> feat(rollouts): Add FS store implementation of rollouts

ui/src/app/console/Console.tsx, ui/src/data/api.ts, ui/vite.config.ts
Proxying to use evaluation v2 endpoints for the `Console` page rather than evaluation v1 endpoints (legacy).
Completes FLI-477
=> feat(console-evaluation): use v2 evaluation in console rather than v1 evaluation

config/migrations/sqlite3/10_rollouts.up.sql, internal/storage/sql/rollout_test.go, ui/src/app/flags/Evaluation.tsx, ui/src/app/flags/rollouts/Rollouts.tsx, ui/src/components/rollouts/Rollout.tsx, ui/src/components/rollouts/SortableRollout.tsx, ui/src/components/rollouts/forms/QuickEditRolloutForm.tsx, ui/src/components/rules/Rule.tsx, ui/src/components/rules/forms/MultiDistributionForm.tsx, ui/src/components/rules/forms/QuickEditRuleForm.tsx, ui/src/components/rules/forms/RuleForm.tsx, ui/src/data/api.ts, ui/src/types/Distribution.ts, ui/tests/rules.spec.ts
Fixes: FLI-476
- Adds back ability to re-order rules
- Adds ability to re-order rollouts
- Fixes ability to re-order rollouts in SQL
- Adds re-order rollout tests
**The video is from before the fix in the DB just to show drag-drop func**
https://github.com/flipt-io/flipt/assets/209477/7cd0d3f2-d956-4f6b-9872-5f9ebc41ed68
=> feat: Reorder Rollouts

.github/workflows/test.yml, build/magefile.go, build/testing/test.go
This moves all unit tests in CI to use the Dagger mage targets.
We will need to update the branch protection rules to accomodate this.
=> chore(github): move all db unit tests to dagger

build/go.mod, build/go.sum, rpc/flipt/go.sum
This fixes the problem with `go mod tidy`.
This can be replaced relatively.
=> fix(build): use relative replace for rpc/flipt

ui/screenshot.js, ui/screenshot/concepts/constraints.js, ui/screenshot/concepts/rollouts.js, ui/screenshot/concepts/variants.js
previously the screenshots were not always reliably scrolling to the bottom of the page when requested, sometimes the screenshot would happen mid-scroll.
This effectively fixes that
=> chore: fix scrollToBottom for screenshots

build/testing/integration/readonly/readonly_test.go, build/testing/integration/readonly/testdata/default.yaml, build/testing/integration/readonly/testdata/production.yaml, internal/storage/sql/common/evaluation.go, internal/storage/sql/evaluation_test.go
Add logic to account for segments without constraints. For rules, segments without constraints result in a match during evaluation. This PR does the following:
- Uses a `LEFT JOIN` instead of a `JOIN` in the query to get segments that do not have constraints out of the db
- Writes unit/integration tests to validate that the behavior is working
=> chore(rollouts): account for segments without constraints

build/testing/integration/readonly/testdata/default.yaml, build/testing/integration/readonly/testdata/production.yaml, ui/src/app/auth/Login.tsx, ui/src/app/flags/Evaluation.tsx, ui/src/components/NotificationProvider.tsx, ui/src/components/notifications/ErrorNotification.tsx, ui/src/utils/helpers.ts
Fixes: FLI-509
- don't allow navigating to `/flag/evaluation` for boolean flags
- also redoes our ErrorNotification/context so that it can accept either `Error` or `string`s and display the string message
=> chore: disallow rollouts eval UI

CHANGELOG.md
=> chore: update changelog for v1.24

internal/server/auth/middleware.go, internal/server/auth/middleware_test.go
Fixes an issue where when OIDC is used in conjunction with other authentication methods (Token, Kubernetes etc.) with the new email matches feature, we end up inadvertantly rejecting all non-OIDC method generated tokens.
The email matches feature should only be enforced on authentication tokens generated with the OIDC method.
From the newly added test around this behaviour:
```
--- FAIL: TestEmailMatchingInterceptor/successful_token_was_not_generated_via_OIDC_method (0.00s)
logger.go:130: 2023-08-01T14:41:44.690Z	DEBUG	no email provided but required for auth
middleware_test.go:281: 
Error Trace:	/src/internal/server/auth/middleware_test.go:281
Error:      	Not equal: 
expected: <nil>(<nil>)
actual  : *status.Error(&status.Error{s:(*status.Status)(0xc0000143d8)})
Test: …
```
=> fix(auth/middleware): only enforce email matches on OIDC method tokens 

config/flipt.schema.cue, config/flipt.schema.json
This PR adds an optional string array field definition for the `authentication.methods.oidc.providers.[provider].scopes` option to the JSON and CUE schemas for the flipt configuration file.
I wasn't sure if it was preferable to just use a loose string type, or if a specific enum with the standard OIDC claims of `email`, `profile` would be more correct. Let me know if you'd prefer it as an enum instead and I can update.
I have no experience with CUE schemas or idea of how to go about validating my change. I read up on the docs and this seemed like the right change there. Apologies if this is making more work than it's resolving 😆. 
Thanks for the warm response!
Fixes #1944
=> feat(config/flipt.schema.*): add oidc provider scopes property

ui/screenshot/concepts/distributions.js, ui/screenshot/concepts/evaluation.js, ui/screenshot/concepts/rules.js, ui/screenshot/extra/darkmode.js, ui/src/components/rollouts/forms/RolloutForm.tsx
Fixes disabling the button when you choose `Segment` rollout type and there are no segments chosen. Also ran:
```
$ npm run format
```
=> chore: fix segment adding for rollouts

ui/src/data/api.ts
Fixes: #1933 
Previously we were clearing the entire browser localStorage for our app on 401/logout. This was also causing user prefs like 'theme' to be cleared.
This fixes it to only clear the session related values on 401
=> fix: dont clear all localstorage on 401

ui/src/app/Layout.tsx, ui/src/app/flags/Flag.tsx, ui/src/app/namespaces/namespacesSlice.ts, ui/src/app/segments/Segment.tsx, ui/src/store.ts
Fixes: #1942 
- persists current namespace in browser localStorage so its consistent across tabs
- also allows sharing direct URLs as now the namespace is loaded from URL if it does not match what is in the store (and then updates the value in the store also)
=> fix: store namespace in localstorage

ui/src/components/rules/forms/QuickEditRuleForm.tsx
=> fix(ui): rule form inputs in darkmode

ui/package-lock.json, ui/package.json, ui/src/app/flags/Evaluation.tsx, ui/src/app/flags/rollouts/Rollouts.tsx, ui/src/components/forms/Combobox.tsx, ui/src/components/forms/SegmentsPicker.tsx, ui/src/components/forms/Select.tsx, ui/src/components/rollouts/forms/EditRolloutForm.tsx, ui/src/components/rollouts/forms/QuickEditRolloutForm.tsx, ui/src/components/rollouts/forms/RolloutForm.tsx, ui/src/components/rules/forms/QuickEditRuleForm.tsx, ui/src/components/rules/forms/RuleForm.tsx, ui/src/types/Evaluatable.ts, ui/src/types/Segment.ts, ui/tests/rules.spec.ts
UI For edits/updates to rule/rollout segments.
Completes FLI-537
=> feat(rollouts/rules): UI for rollout/rule editing of segments

config/local.yml, internal/cmd/auth.go, internal/config/config_test.go, internal/config/storage.go, internal/config/testdata/storage/invalid_readonly.yml, ui/src/app/meta/metaSlice.ts, ui/src/components/Header.tsx, ui/src/types/Meta.ts
Gives us (and operators) to force the UI into read-only mode by setting the following:
```yaml
experimental:
filesystem_storage:
enabled: true
storage:
readOnly: true
```
In this next release we will be 'graduating' filesystem storage, so the `experimental` bit will not be required.
The goal of this feature is two fold:
1. To enable devs to be able to more easily test the UI in readonly mode (without requiring us to configure a readonly storage mode)
2. To allow operators to put Flipt in readonly mode even if backed by a database
For 2., more work will need to be done either at the API or ideally storage layer to reject all write requests, as currently this change only affects the UI so users could still make API requests or modify data via import/export even if `storage: readonly: true` …
=> feat: Force readonly

README.md
chore: mark ruby gem as stable in README.md
=> chore: mark ruby gem as stable in README.md

ui/src/components/forms/SegmentsPicker.tsx, ui/src/components/rollouts/forms/EditRolloutForm.tsx, ui/src/components/rollouts/forms/QuickEditRolloutForm.tsx, ui/src/components/rollouts/forms/RolloutForm.tsx, ui/src/components/rules/forms/QuickEditRuleForm.tsx, ui/src/components/rules/forms/RuleForm.tsx, ui/tests/rules.spec.ts
This PR addresses the two issues:
- Change UX around adding segments to always add the plus button whenever a segment is chosen
- Only show `AND` and `OR` radio buttons when you choose multiple segments
Completes FLI-545
Completes FLI-546
=> feat(rules/rollouts): hide or and and based on segment keys length, and UX around adding segments

build/internal/cmd/generate/main.go, build/testing/integration/readonly/testdata/default.yaml, build/testing/integration/readonly/testdata/production.yaml, internal/ext/common.go, internal/ext/exporter.go, internal/ext/exporter_test.go, internal/ext/importer.go, internal/ext/importer_test.go, internal/ext/testdata/import_rule_multiple_segments.yml, internal/storage/fs/snapshot.go, internal/storage/sql/common/rollout.go, internal/storage/sql/common/rule.go, internal/storage/sql/rollout_test.go, internal/storage/sql/rule_test.go
Make `segment` under rules respect one of two types.
This:
```yaml
rules:
segment: "foo"
```
Or:
```yaml
rules:
segment:
keys:
- foo
- bar
operator: AND_SEGMENT_OPERATOR
```
=> feat(rules): Make segment be one of two types

internal/storage/sql/common/evaluation.go
Revise query to collect ruleIDs, and then use those collected IDs in subsequent query for the segments/constraints. We sort the rules at the end via the `rank`, so we can actually just remove the `OrderBy` clause in the first query to optimize.
Before this, the subquery [here](https://github.com/flipt-io/flipt/blob/segment-anding/internal/storage/sql/common/evaluation.go#L33-L44) was not filtering rules based on `flag_key` or `namespace_key`.
=> feat(rules): Revise query for optimization

internal/storage/storage.go
Use json tags for `EvaluationSegment` for serializing `map` to cacher.
=> chore(evaluation): Use JSON tags for EvaluationSegment

ui/src/components/flags/FlagForm.tsx, ui/src/components/segments/SegmentForm.tsx, ui/tests/flags.spec.ts, ui/tests/segments.spec.ts
Fixes: FLI-556
Makes flag/segment name/desc/flag type inputs disabled when in readonly mode
=> fix(ui): make flags/segments inputs disabled in readonly mode

.github/workflows/release-clients.yml
pass tag correctly to dotnet grpc release workflow
=> chore: fix release-grpc-dotnet workflow

ui/src/data/api.ts
Builds on #2014 
Adds `Cache-Control: no-store` header for UI so results are always consistent (updating flag shows immediately instead of waiting on cache expiry)
[no-store from RFC](https://datatracker.ietf.org/doc/html/rfc7234#section-5.2)
```
The "no-store" request directive indicates that a cache MUST NOT store any part of either this request or any response to it.
```
With Cache Enabled:
```
2023-08-18T08:10:54-04:00	DEBUG	get flag	{"server": "grpc", "request": "key:\"flag_001\"  namespace_key:\"default\""}
2023-08-18T08:10:54-04:00	DEBUG	skipping storage cache as 'no-store' was set	{"server": "grpc"}
```
=> chore: skip storing in cache for ui consistency

CHANGELOG.md, internal/cmd/grpc.go
Fix issue where cacher was still getting set to nil because of shadowing rules, resulting in the middleware for caching not getting activated because of a later nil check: https://github.com/flipt-io/flipt/blob/f6f01890f6017b6cebb2f70c2052c4d2e6591d29/internal/cmd/grpc.go#L317
=> fix: Fix cache shadow

.github/ISSUE_TEMPLATE/config.yml
https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository#configuring-the-template-chooser
adds option/link to join our discord instead of filing an issue
=> chore: setup links to discord in issues

ui/src/app/console/Console.tsx, ui/src/components/flags/FlagForm.tsx, ui/src/components/segments/SegmentForm.tsx
In light mode some of the icons were hard to see on hover
=> fix: Hover icons

.github/workflows/integration-test.yml, .github/workflows/nightly.yml, .github/workflows/release-tag-latest.yml, .github/workflows/release.yml, .github/workflows/snapshot.yml, .github/workflows/test.yml
https://github.com/magefile/mage-action/pull/293 added the ability to do `install-only`
this updates all our workflows to make use of it so mage is available for all later steps
=> chore: update mage action to latest action which allows install

magefile.go, ui/src/App.tsx, ui/src/app/Support.tsx, ui/src/app/namespaces/Namespaces.tsx, ui/src/app/preferences/Preferences.tsx, ui/src/app/tokens/Tokens.tsx, ui/src/components/Nav.tsx
Removes link to docs to instead link to a dedicated support page with links to:
- File a GitHub issue
- Send an email requesting slack connect invite
- Send a general support email
Also includes links to our docs still in top right
=> feat(hackweek): add support page instead of link to docs

internal/ext/importer.go, internal/ext/importer_test.go, internal/ext/testdata/import_new_namespace.yml
Supports https://github.com/flipt-io/flipt/issues/2086
This does not fix the main report of the above issue. However, it does address one of the observed symptoms.
We were silently returning a nil error when a namespace existed on `--create-namespace` during import.
This meant the command succeeded, but didn't attempt to populate the namespace with the import contents.
=> fix(ext): attempt to import when namespace exists on create namespace

internal/cue/flipt.cue
Fixes: #2090 
Make rollout description optional in cue def
=> fix(schema): make rollout description optional in cue schema

.goreleaser.yml
- rm `pr` mode for homebrew tap update until https://github.com/goreleaser/goreleaser/issues/4283 is fixed
- setup announcing releases in our Slack https://goreleaser.com/customization/announce/slack/
=> chore: rm pr mode for goreleaser tap update; add slack announce

config/flipt.schema.cue, config/flipt.schema.json, internal/cmd/grpc.go, internal/config/audit.go, internal/config/config.go, internal/config/config_test.go
Move `events` to top level of the audit configuration.
=> feat: move events to top level of audit configuration

go.work.sum, internal/telemetry/telemetry.go, internal/telemetry/telemetry_test.go
Fixes: FLI-593
Adds info about if audit events are configured for our anonymous telemetry to help us make smarter product decisions going forward
=> feat: add audit info to telemetry

internal/server/audit/webhook/client.go
fixes: #2127 
This PR is for fixing this [issue](https://github.com/flipt-io/flipt/issues/2127).
The client was not sending a body in the request upon failure, and that is due to not "rewinding" the HTTP body upon failure.
In this change, we create a request every time we are communicating with the webhook server to avoid those types of errors.
=> fix(webhook): Rewind HTTP request body upon request failure

cmd/flipt/main.go, go.work.sum, internal/config/config.go, internal/config/config_test.go
Fixes: #2126
- Updates `Load` to use `Defaults` if no config file is present, thus allowing the normal env var overrides to take effect
- Adds tests for overriding config via env vars
```
workspace/flipt - [default-config-env] » FLIPT_LOG_LEVEL=debug ./bin/flipt
2023-09-18T10:38:18-04:00	INFO	no configuration file found, using defaults
2023-09-18T10:38:18-04:00	DEBUG	configuration source	{"path": ""}
_________       __
/ ____/ (_)___  / /_
/ /_  / / / __ \/ __/
/ __/ / / / /_/ / /_
/_/   /_/_/ .___/\__/
/_/
Version: dev
Commit: 9c3299ef96451cc7a9708943dcabd7e1cafc9289
Build Date: 2023-09-18T14:03:05Z
Go Version: go1.21.0
OS/Arch: darwin/arm64
2023-09-18T10:38:18-04:00	DEBUG	not a release version, disabling telemetry
2023-09-18T10:38:18-04:00	DEBUG	local state directory exists	{"path": …
```
=> fix: Default config allow env overrides

config/flipt.schema.cue, config/flipt.schema.json, internal/cmd/grpc.go, internal/config/config_test.go, internal/config/testdata/tracing/otlp.yml, internal/config/tracing.go
Necessary to send OTLP tracing data to servers like NewRelic:
https://docs.newrelic.com/docs/more-integrations/open-source-telemetry-integrations/opentelemetry/get-started/opentelemetry-set-up-your-app/
=> feat(tracing): add OTLP headers config

cmd/flipt/export.go, cmd/flipt/import.go, cmd/flipt/server.go, go.work.sum
Fixes: FLI-607
Fixes a bug when trying to export with a call to a server running https
```
flipt export --address https://flipt-xyz.onrender.com/
2023-09-20T12:25:13.050-0400	FATAL	flipt/server.go:65	unexpected protocol	{"address": "https://flipt-xyz.onrender.com/"}
main.fliptClient
go.flipt.io/flipt/cmd/flipt/server.go:65
main.(*exportCommand).run
go.flipt.io/flipt/cmd/flipt/export.go:88
github.com/spf13/cobra.(*Command).execute
github.com/spf13/cobra@v1.7.0/command.go:940
github.com/spf13/cobra.(*Command).ExecuteC
github.com/spf13/cobra@v1.7.0/command.go:1068
github.com/spf13/cobra.(*Command).Execute
github.com/spf13/cobra@v1.7.0/command.go:992
github.com/spf13/cobra.(*Command).ExecuteContext
github.com/spf13/cobra@v1.7.0/command.go:985
main.main
go.flipt.io/flipt/cmd/flipt/main.go:163 …
```
=> fix: export with https

CHANGELOG.md, build/testing/integration/api/api.go, internal/config/authentication.go, internal/config/cache.go, internal/config/database.go, internal/config/server.go, internal/config/storage.go
do not expose secrets to JSON endpoints
we should come up with a strategy to test for this to prevent regressions and also to guard against any future config options having to do with secrets
=> fix(security): dont marshal secrets to JSON

.goreleaser.yml, cmd/flipt/completion.go, cmd/flipt/config.go, cmd/flipt/export.go, cmd/flipt/import.go, cmd/flipt/main.go, cmd/flipt/migrate.go, go.work.sum
- Adds shell completion to CLI
- Install shell completion via homebrew (goreleaser)
- Moves `--config` option from global to only the commands that leverage it
=> feat: cmd shell completions

.goreleaser.darwin.yml, .goreleaser.linux.yml, .goreleaser.yml
Fixes broken releases by setting `project_name` field for GoReleaser
Before (Broken): https://github.com/flipt-io/flipt/actions/runs/6305618044/job/17119520010
This PR (Fixed): https://github.com/flipt-io/flipt/actions/runs/6317979263/job/17156184368
=> Fix goreleaser

install.sh
Fixes: FLI-623
Easy install script
Borrowed/modified from https://raw.githubusercontent.com/metalbear-co/mirrord/main/scripts/install.sh
Install latest:
```
workspace/flipt - [install-script] » ./install.sh
Installing version v1.27.2
Flipt installed!
For feedback and support, join our Discord server: https://flipt.io/discord, open an issue or discussion on our GitHub: https://github.com/flipt-io/flipt/ or send us an email at dev@flipt.io
```
Install specific version (both with and without v prefix):
```
workspace/flipt - [main●] » VERSION=v1.26.0 ./install.sh
Installing version v1.26.0
Flipt installed!
For feedback and support, join our Discord server: https://flipt.io/discord, open an issue or discussion on our GitHub: https://github.com/flipt-io/flipt/ or send us an email at …
```
=> chore: add oneliner install script

internal/cue/testdata/invalid_yaml_stream.yaml, internal/cue/testdata/valid_yaml_stream.yaml, internal/cue/validate.go, internal/cue/validate_fuzz_test.go, internal/cue/validate_test.go, internal/storage/fs/fixtures/fswithindex/prod/prod.features.yml, internal/storage/fs/fixtures/yaml_stream/features.yaml, internal/storage/fs/snapshot.go, internal/storage/fs/snapshot_test.go
We have recently added the ability to import/export files with multiple YAML documents contained within them. This PR adds the ability for the FS backends to craft flag state from either single document YAML files, multi-document YAML files or both.
This change also has the effect of removing the column number from error reporting out of the cue validate logic.
I talked with @markphelps offline about this, it seems that supporting YAML streams with cue's File semantics is a bit weird. We can follow up with this issue on another iteration.
Completes FLI-618
=> feat: Support YAML stream for FS Backends

build/testing/testdata/cli.txt, cmd/flipt/doc.go, cmd/flipt/export.go, cmd/flipt/import.go, cmd/flipt/main.go, go.mod, go.sum
re: FLI-608
- adds hidden subcommand to enable us to generate the CLI docs for copy/pasting into our actual documentation
```
$ flipt docs
$ tree tmp/docs/
tmp/docs/
├── flipt.md
├── flipt_config.md
├── flipt_config_edit.md
├── flipt_config_init.md
├── flipt_export.md
├── flipt_import.md
├── flipt_migrate.md
└── flipt_validate.md
1 directory, 8 files
```
=> feat: Gen cli docs

internal/server/evaluation/evaluation.go, internal/server/evaluation/evaluation_test.go
Fixes: #2006 
Re: https://github.com/flipt-io/flipt/issues/2006#issuecomment-1740497457
I dont see any harm in returning the request ID as passed in, especially since its already on the response types.. It should allow users to uniquely identify requests/responses in batch evaluations
=> feat: add requestID to batch response

internal/storage/fs/s3/source.go
The application was not honoring the region configuration.
This PR will set the region value from configuration wherever it was set, either environment variable or configuration file.
Without this the following error occurred:
```
Error: Open .flipt.yml: operation error S3: GetObject, https response error StatusCode: 400, RequestID: N7MN8TJY9CFY5BXF, HostID: 7KtR0/CRqaCS7aU4+8LLyDz9MTw2aFPEE/a7VSMUk6JE5DEnl8xCYalJHuBBkCKiB9rN65cZmb8=, api error AuthorizationHeaderMalformed: The authorization header is malformed; a non-empty region must be provided in the credential.
```
=> chore: specify region to fix s3 feature

config/flipt.schema.cue, config/flipt.schema.json, internal/cmd/http.go, internal/config/config.go, internal/config/diagnostics.go, internal/config/testdata/marshal/yaml/default.yml
Re: https://github.com/flipt-io/flipt/discussions/2194
=> feat: allow disabling profiling endpoints

internal/cmd/http.go
Fixes: #2198 
Re: https://github.com/microsoft/monaco-editor/issues/271
Looks like this is required for using monaco editor 🤷🏻 
I tried it out by removing the:
```
if !info.IsDevelopment() { }
```
Reproduced it and then applied the fix.
Need to figure out how to better test this, or if the `info.IsDevelopment` check is even necessary anymore (I think its only necessary if you run the server (Go) and the UI (React) on different ports like when wanting to iterate quickly on the UI without recompiling
=> fix: csp header for monaco editor

examples/nextjs/Caddyfile, examples/nextjs/README.md, examples/nextjs/components/Greeting.tsx, examples/nextjs/docker-compose.yml, examples/nextjs/package-lock.json, examples/nextjs/package.json, examples/nextjs/pages/api/hello.ts, examples/nextjs/pages/index.tsx
update the nextJS example to use the newer node-sdk with boolean/variant (`evaluate/v1`) endpoints.
Going to use this example as a source for upcoming blog on typesafety/ffs
=> chore: update nextjs example to use newer eval endpoints

build/testing/integration/api/api.go, internal/server/middleware/grpc/middleware.go
Fixes https://github.com/flipt-io/flipt/issues/2236
It was reported that the API responds inconsistently when the cache is enabled and you attempt to evaluate using both the new and the legacy API. @rudineirk correctly identified the root cause being that the cache key is shared for both the old and new evaluation responses. Further investigation showed that when Flipt attempts to unmarshall a new evaluation API response payload into the old protobuf type, it succeeds to unmarshal (no wire protocol errors). However, what it produces is an invalid result as the fields are all in different locations.
This means the API responds as a successful evaluation, however, it returns a completely invalid result. For example, this leads to a flag incorrectly reporting as disabled.
The fix for this …
=>  fix(service/middleware): use separate cache keys for old and new evaluations

config/flipt.schema.cue, config/flipt.schema.json, go.mod, go.work.sum, internal/cmd/grpc.go, internal/config/config_test.go, internal/config/storage.go, internal/config/testdata/storage/git_ssh_auth_invalid_missing_password.yml, internal/config/testdata/storage/git_ssh_auth_invalid_missing_user.yml, internal/config/testdata/storage/git_ssh_auth_invalid_private_key_both.yml, internal/config/testdata/storage/git_ssh_auth_invalid_private_key_missing.yml, internal/config/testdata/storage/git_ssh_auth_valid_with_path.yml
Fixes #2271 
This introduces SSH authentication credential support for the Git backend.
Using either explicit private key bytes, or a path to the private key bytes, you can configure Flipt to pull over SSH.
This is an alternative approach for pulling from private registries.
I recommend following along with GitHubs documentation on deploy keys to learn how to setup a repo with this.
We can add some documentation on our side to point to this too.
https://docs.github.com/en/authentication/connecting-to-github-with-ssh/managing-deploy-keys#deploy-keys
The Flipt server configuration looks like the following:
```yaml
storage:
type: git
git:
repository: git@github.com:flipt-io/some-private-repo.git
authentication:
ssh:
password: flipt
private_key_path: private-key.pem
insecure_ignore_host_key: …
```
=> feat(git): support SSH authentication

README.md, examples/audit/README.md, internal/server/audit/logfile/logfile.go, internal/server/audit/logfile/logfile_test.go
fixes: #2294 
- create parent path for audit log if not exists
- add some tests for audit log
- update readme paths for new audit docs
=> fix: Audit log path fixes

internal/config/storage.go, internal/config/testdata/storage/invalid_readonly.yml
found this while trying to test if the namespace picker works in read only (it does), this makes `read_only` match our other config properties, snake_case instead of camelCase.
we should likely add a test somehow that all config properties in YAML are specified in snake_case
I don't think this is a breaking change since it was never publicly documented
=> fix: readOnly config option should be read_only

config/flipt.schema.cue, config/flipt.schema.json, go.mod, go.sum, internal/config/config_test.go, internal/config/storage.go, internal/config/testdata/storage/oci_invalid_no_repo.yml, internal/config/testdata/storage/oci_invalid_unexpected_repo.yml, internal/config/testdata/storage/oci_provided.yml
Supports #2296 
This is over the long-running `gm/fs-oci` branch.
Adds configuration sections for the new OCI FS backend.
This section includes repository reference target and authentication credential details.
I chose to not use the wording basic auth, because I believe that we could support user/pass for both basic and for oauth flows via these same parameters (that is how the Oras Go lib appears to support it).
=> feat(oci): add configuration for new OCI backend

cmd/flipt/main.go, go.mod, internal/config/config.go, internal/config/config_test.go, internal/config/database_default.go, internal/config/storage.go, internal/config/testdata/storage/oci_provided.yml, internal/oci/file.go, internal/oci/file_test.go, internal/oci/oci.go
Supports #2296 
Fixes FLI-660
This adds a new package `oci` with a single type `Store`.
The store manages reading from the new Flipt bundle OCI format.
It will be consumed by the new `oci.Source` type in a subsequent PR.
It supports fetching with an optional `IfNoMatch` digest.
The source will provide the previously observed digest between subsequent fetches.
Then it will skip producing a new snapshot when `Matched == true` as this means the reference hasn't changed contents target. It does so even in the face of created at timestamp change. It purely focusses on the contents state.
=> feat(oci): add new package with store implementation

internal/oci/file.go, internal/storage/fs/git/source.go, internal/storage/fs/git/source_test.go, internal/storage/fs/local/source.go, internal/storage/fs/local/source_test.go, internal/storage/fs/oci/source.go, internal/storage/fs/oci/source_test.go, internal/storage/fs/s3/source.go, internal/storage/fs/s3/source_test.go, internal/storage/fs/store.go, internal/storage/fs/store_test.go
Fixes FLI-661
This is currently based on #2332 I will undraft and rebase on `gm/fs-oci` when that is merged.
This introduces the new `storage/fs/oci.Source` type.
=> feat(storage/fs/oci): add new OCI source

build/testing/cli.go, build/testing/helpers.go, build/testing/testdata/bundle/.flipt.yml, build/testing/testdata/bundle/a.features.yml, build/testing/testdata/bundle/b.features.json, cmd/flipt/bundle.go, internal/oci/file.go, internal/oci/file_test.go, internal/oci/oci.go
Fixes FLI-658
Fixes FLI-659
This implements both of the following subcommands:
```console
flipt bundle push <from> <to>
flipt bundle pull <remote>
```
This PR also adds unit tests and CLI integration tests for all the flipt bundle sub-commands.
I will make bundle hidden in a subsequent PR when I integrate the OCI backend into main.
=> feat(cmd/flipt): add bundle push and pull

.github/workflows/integration-test.yml, build/testing/integration.go, cmd/flipt/bundle.go, config/flipt.schema.cue, config/flipt.schema.json, internal/cmd/grpc.go, internal/config/config_test.go, internal/config/storage.go, internal/config/testdata/storage/oci_invalid_unexpected_scheme.yml, internal/config/testdata/storage/oci_provided.yml, internal/oci/file.go, internal/oci/file_test.go, internal/storage/fs/oci/source_test.go
Fixes FLI-663
This the last PR to add the OCI backend to Flipt.
It installs the new OCI storage into the main Flipt process.
It also includes the wiring to add the OCI integration test suite to dagger and the associated GH workflow.
=> feat(oci): integrate new FS backend into Flipt

config/flipt.schema.cue, config/flipt.schema.json, internal/cmd/http.go, internal/config/config.go, internal/config/config_test.go, internal/config/cors.go, internal/config/testdata/advanced.yml, internal/config/testdata/marshal/yaml/default.yml
Today @graup requested support for some CORS issues relating to headers.
Our Fern clients inject the following extra headers:
- `X-Fern-Language`
- `X-Fern-SDK-Name`
- `X-Fern-SDK-Version`
These are not currently being admitted by the CORS policy.
This change both adds these headers as always permitted, as well as allowing users to customize the headers to suit their needs. I have also reached out to Fern to see if we can make new headers opt in in the future. So that we avoid accidentally breaking clients.
If we can't get opt in, perhaps we also should just set up an integration suite from a browser perspective with the node client. Something which tests the CORS aspects on each Fern update.
=> fix(cors): support fern and customizable allowed headers

internal/cue/flipt.cue
Add missing new operators to cue validation file.
=> chore: add isoneof and isnotoneof to cue file

ui/src/components/segments/ConstraintForm.tsx
make the constraint datettime form look a little nicer vs lowercase timezones
=> chore(ui): minor fix for datetime constraint label

go.work, sdk/client/go/README.md, sdk/client/go/flipt-client-go/evaluation.go, sdk/client/go/flipt-client-go/go.mod, sdk/client/go/flipt-client-go/models.go, sdk/client/python/README.md
This PR introduces the `flipt-client-go` for embedding a dynamic library written with the Rust core for flipt evaluations.
Completes FLI-675
=> feat: add initial commit for flipt-client-go evaluation client

sdk/client/engine/src/lib.rs, sdk/client/go/README.md, sdk/client/go/flipt-client-go/evaluation.go, sdk/client/go/flipt-client-go/models.go, sdk/client/python/README.md, sdk/client/python/flipt-client-python/flipt_client_python/__init__.py, sdk/client/python/flipt-client-python/flipt_client_python/models.py
There inevitably will be errors upon user input for evaluations. This change will return such errors to the caller in an enveloped structure that contains a `ResponseCode`, and an optional Result (Boolean, Variant) and error message.
Completes FLI-689
=> feat: incorporate error handling from Rust core over FFI to clients

internal/cue/flipt.cue, internal/cue/testdata/valid.yaml
Fixes #2421
This makes the CUE schema more permissive and accepts arrays, as well as objects under variant attachments.
=> test(cue): add failing case for attachment array support

ui/src/components/tokens/TokenTable.tsx
User may use search to delete the token and after deletion we still want to have the search input so user could get back other token. Before user faced the empty table and no search input.
Fixes: #2436
=> fix(ui/token): show search input if it contains user's input

internal/config/storage.go
we should really figure out how to test that our JSON representation for our configs are all in camelCase
=> fix: camelcase JSON representation in storage config

ui/src/app/flags/Flag.tsx, ui/src/app/flags/flagsSlice.ts, ui/src/app/namespaces/namespacesSlice.ts
should fix https://github.com/flipt-io/flipt/issues/2444
🙈
=> fix: incorrect selector usage in redux

build/testing/integration.go, build/testing/test.go
There an issue with the `latest` Gitea docker image: https://github.com/go-gitea/gitea/issues/28230
This is causing our fs/git ITs to fail as well. Pinning the version to a known good version for now until ☝🏻 is resolved
=> chore: pin gitea image for ITs for now

ui/src/app/flags/rollouts/Rollouts.tsx, ui/src/app/flags/rules/Rules.tsx, ui/src/app/segments/Segment.tsx, ui/src/app/segments/Segments.tsx, ui/src/app/segments/segmentsApi.ts, ui/src/components/segments/ConstraintForm.tsx, ui/src/components/segments/SegmentForm.tsx, ui/src/data/api.ts, ui/src/store.ts, ui/src/utils/helpers.ts, ui/src/utils/redux-rtk.ts
Try to use Redux RTK for Segments.
Refs: #2433
=> refactor(ui): move Segments to use Redux storage

README.md
DavidAnson/markdownlint-cli2-action was bumped from 13 to 14 and linter started to complain about README.md. For some reason it was merged automatically by kodiakhq bot even the action failed.
Refs: #2450
=> chore: add alt attribute after markdownlint upgrade

ui/src/app/flags/rules/Rules.tsx, ui/src/app/flags/rulesApi.ts, ui/src/components/rules/forms/QuickEditRuleForm.tsx, ui/src/components/rules/forms/RuleForm.tsx, ui/src/data/api.ts, ui/src/store.ts
=> refactor(ui): move Rules to use Redux for storage

ui/src/components/console/ContextEditor.tsx, ui/src/components/console/worker.ts
Refs: #2059
BTW,  Monaco has feature to [highlight the code](https://microsoft.github.io/monaco-editor/playground.html?source=v0.44.0#example-creating-the-editor-syntax-highlighting-for-html-elements). We could drop `highlight.js` and replace it with that if needed.
=> fix(ui/console): monaco web workers don't work

ui/jest.config.ts, ui/src/app/console/Console.tsx, ui/src/components/console/ContextEditor.module.css, ui/src/data/api.ts, ui/src/types/Auth.ts, ui/src/types/Curl.ts, ui/src/utils/helpers.ts
fixes: #2255 
- implemented 'Copy as curl' button
- Fixed the following ui bugs:
+ Request Context editor hides the 'Evaluate' button on smaller heights
+ The component showing the response gets highlighted (using hljs) only on the first request, and not on subsequent requests or when an error happens.
I wasn't sure how to specify the need for an API token for the curl command if auth was required. I just put `-H "Authorization: Bearer <api-token>"`.
=> feat(ui/console): add copy as curl button

cmd/flipt/main.go
This changes the CLI to only output the error, not the entire help docs
```
workspace/flipt - [main●] » ./bin/flipt --config config/local.yml
Error: loading configuration scopes must contain read:org when allowed_organizations is not empty
Usage:
flipt <command> <subcommand> [flags]
flipt [command]
Examples:
$ flipt
$ flipt config init
$ flipt --config /path/to/config.yml migrate
Available Commands:
bundle      Manage Flipt bundles
config      Manage Flipt configuration
export      Export Flipt data to file/stdout
help        Help about any command
import      Import Flipt data from file/stdin
```
```
workspace/flipt - [silence-usage●] » ./bin/flipt --config config/local.yml
Error: loading configuration scopes must contain read:org when allowed_organizations is not empty
```
=> feat(cli): silence usage on errors

cmd/flipt/main.go, internal/config/config.go
I would say that it's more chicken and egg problem. Viper is loading the configuration after the logger says that there is no configuration file. 
fixes #2531
=> fix(cfg): default config outputs first INFO log regardless of FLIPT_LOG_LEVEL

.gitignore, CONTRIBUTING.md, DEVELOPMENT.md, README.md, devenv.lock, devenv.nix, devenv.yaml
- setup [devenv](https://devenv.sh/)
- update readme/contributing docs
- merges in #2541
=> chore: Devenv

build/internal/cmd/gitea/main.go
go-git added validation for refs and branch refs is not defined correctly.
fixes #2522
=> fix: resolved issues with go-git 5.11.0

.github/workflows/integration-test.yml
The ITs are currently not running.
There is a bug, but GH quietly fails and doesn't run the tests.
=> fix(github): replace slashes with dashes via gh workflow step

internal/storage/fs/blob/dir.go, internal/storage/fs/blob/dir_test.go, internal/storage/fs/blob/file.go, internal/storage/fs/blob/file_test.go, internal/storage/fs/blob/fileinfo.go, internal/storage/fs/blob/fileinfo_test.go, internal/storage/fs/s3/s3fs.go, internal/storage/fs/s3/s3fs_test.go, internal/storage/fs/s3/store.go
Move s3fs to storage/fs/s3 and extract file types into storage/fs/blob package
This is related to work with Azure Blob Storage #2538
=> refactor(storage): move s3fs to storage/fs/s3 and extract file types

internal/cleanup/cleanup.go, internal/cleanup/cleanup_test.go
This parallelizes the `cleanup` suite auth method tests.
Each auth method was being tested in serial. The test consistents of some rather long sleeps, because oplock works around polling and expiry / grace period timestamps. These could probably also be reduced. However, in this PR, I parallelized the tests for each method as the suite of tests was growing each time we added a new authentication method.
This brings the test suite down from ~60s (4 methods * 15 seconds) to a constant ~15s that wont grow with each new method.
=> test(cleanup): parallelize cleanup method tests

.devcontainer/Dockerfile, .devcontainer/devcontainer.json, .devcontainer/welcome-message.txt, .gitpod.yml, .vscode/extensions.json, DEVELOPMENT.md
- add gitpod, we get free credits for open source repos (https://www.gitpod.io/discover/opensource)
- try to fix devcontainer/docker image since we changed where default db goes
=> chore: fix broken devcontainer workflow; add gitpod

ui/package-lock.json, ui/package.json, ui/src/app/preferences/Preferences.tsx, ui/src/components/segments/ConstraintForm.tsx, ui/src/data/hooks/timezone.ts
Project has two libs to work with dates date-fns and moment.js. As moment.js
> We now generally consider Moment to be a legacy project in maintenance
mode. It is not dead, but it is indeed done.
=> refactor(ui): drop moment.js

ui/package-lock.json, ui/package.json, ui/src/app/console/Console.tsx, ui/src/components/tokens/ShowTokenPanel.tsx
reuse monaco for json formatting.
=> refactor(ui): drop highlight.js

go.mod, go.sum, go.work.sum, internal/config/config.go
Flipts used it only for config default values.
=> chore(deps): drop jaeger-client-go as it's deprecated three years ago.

ui/package-lock.json, ui/package.json, ui/src/app/console/Console.tsx, ui/src/components/flags/FlagForm.tsx, ui/src/components/flags/VariantForm.tsx, ui/src/components/namespaces/NamespaceForm.tsx, ui/src/components/rules/forms/RuleForm.tsx, ui/src/components/segments/SegmentForm.tsx, ui/src/components/tokens/TokenForm.tsx, ui/src/data/validation.test.ts, ui/src/data/validations.ts
- move creation of validation schemas out of render blocks
- use a new validation schema for console context as it isn't a any json object but map[string]string
- update Yup to new major version
=> refactor(ui): improve Yup usage

.goreleaser.yml
It seems goreleaser is getting the wrong tag when building nightly image
Going to try this setting from goreleaser: https://goreleaser.com/customization/git/#semver-sorting
=> chore: try to fix nightly build tag

.github/workflows/nightly.yml
Re: https://discord.com/channels/960634591000014878/1191792891203424338/1196576871643619359
It seems goreleaser uses `git describe` to get the 'previous tag'. for some reason, this seems to be incorrect in our `main` branch / for snapshot builds. maybe because of how we do tagging off of `release/*` branches?
Anyways, setting `GORELEASER_CURRENT_TAG` env var overrides this, and we can get the correct latest tag using `git rev-list` magic
=> chore: try to fix previous tag for good

ui/index.dev.html, ui/index.html
- update index.dev.html with new command to run ui in dev mode
- added noscript message in index.html
- add head tag to index.html
=> refactor(ui): improve index

cmd/flipt/validate.go, internal/cue/validate.go, internal/storage/fs/object/store.go, internal/storage/fs/oci/store.go, internal/storage/fs/snapshot.go
This is in response to a discussion had with our friends at Paradigm.
The request was:
```
Hi team, given we have flipt validate is there perhaps a way to force some fields to be mandatory?
In our case description is required or we won't have people  outside of developers knowing what that flag actually does.
```
We leverage CUE under the hood to power `flipt validate` and this is driven by our flipt feature CUE schema:
https://github.com/flipt-io/flipt/blob/de980017bc20f1f298c9030bfd1dea98d31fea28/internal/cue/flipt.cue#L1-L20
This proposed change adds the ability to extend this schema with your own valid subset of this schema.
```console
flipt validate -e extended.cue features.json
```
Taking the original request to be able to make e.g. description required, this could be achieved with …
=> feat(validate): add ability to further constrain schema

README.md
Been trying out Koyeb, its pretty nice. Adding a deploy to Koyeb button <https://www.koyeb.com/docs/build-and-deploy/deploy-to-koyeb-button> and simplifying the integration section of README
=> chore: add deploy to koyeb button; simplify integration docs

cmd/flipt/evaluate.go, cmd/flipt/export.go, cmd/flipt/import.go
- make cli command option descriptions consistent
- rm zap logger from non `server` commands
=> chore: rm zap logger from cli commands

internal/cue/validate.go, internal/cue/validate_test.go, internal/storage/fs/snapshot_test.go
This is a PR on https://github.com/flipt-io/flipt/pull/2697
This attempts to walk through the path selector in the error, using it as an index into the source document.
It is an attempt to use the path to find the first found position and use that in the error context.
=> fix(cue): get error position using error path

cmd/flipt/doc.go, cmd/flipt/evaluate.go
- Don't omit `false` values of `enabled` from `evaluate` response
- Print output dir where CLI docs are generated after running command
=> chore/fix(cmd): dont omit 'enabled' in evaluate cli if false

internal/cmd/grpc.go, internal/config/authentication.go, internal/config/config_test.go, internal/config/deprecations.go, internal/config/testdata/deprecated/authentication_excluding_metadata.yml
Supports https://github.com/flipt-io/flipt/issues/2643
This capability never worked. So this PR marks it deprecated and stops is from actually disabling authentication for metadata when auth is required.
=> deprecate(config): mark authentication.exclude.metadata as deprecated

ui/src/app/flags/rolloutsApi.ts, ui/src/app/flags/rulesApi.ts, ui/src/app/segments/segmentsApi.ts, ui/src/store.ts
With Redux RTK the UI could show a stale cache in the browser when user deletes a flag or a namespace and immediately recreated it with the same key. For namespace old segments will be displayed and for flags - rollouts or rules depending on flag type.
=> fix(ui): clean redux cache when namespace or flag is deleted

sdk/go/CHANGELOG.md
I will cut the release for `sdk/go/v0.10.0` on this branch shortly.
=> chore(sdk/go): update CHANGELOG for v0.10.0

DEVELOPMENT.md
Currently Github forwards to https://github.com/flipt-io/flipt/blob/main/devenv.sh
=> docs: fix link to devenv.sh

.github/workflows/integration-test.yml, .github/workflows/test.yml, build/testing/integration.go, examples/database/cockroachdb/docker-compose.yml, go.work.sum
Comparing and contrasting this approach to https://github.com/flipt-io/flipt/pull/2747
This just disables logging for cockroach (at-least I am hoping it does based on the docs).
https://www.cockroachlabs.com/docs/v23.2/configure-logs
The other approach works, but adds over 2 minutes to each build clearing out 10GB of space before starting.
=> chore(build/testing): disable cockroachdb logging

.github/workflows/nightly.yml
Currently
>  ⨯ release failed after 0s                  error=failed to parse tag 'sdk/go/v0.10.0' as semver: Invalid S
https://github.com/flipt-io/flipt/actions/runs/7777238935/job/21205299888#step:11:35
=> chore: improve git tag for nightly build

.github/workflows/release.yml, .github/workflows/snapshot.yml, ui/.gitignore, ui/package-lock.json, ui/package.json, ui/src/App.tsx
Adds a small in app survey that only shows once
=> feat: add inapp survey

internal/cmd/http.go, ui/dev.go, ui/embed.go
Fixes CSP issue introduced in #2753 
Also allows us to catch CSP-related issues in UI testing (ITs) as now we will be setting CSP headers whenever the UI is embedded. 
We cant set these headers when Flipt and UI are running on different ports during development as CSP will block the UI
=> fix: csp headers for formbricks

ui/src/components/Modal.tsx, ui/src/components/Slideover.tsx
In #2725 there were changes to z-index of header and Slideover and Modal is behind the header. It's visible in creating new token/namespace or in any modal dialog
=> fix(ui): increase z index for Slideover and Modal

internal/cmd/grpc.go
We want to account for users to potentially change the service name of what is reported in their spans.
This change allows for the `OTEL_SERVICE_NAME` environment variable to be respected.
Fixes: #2773
Completes FLI-844
=> feat(otlp): account for service name in environment variable

ui/src/app/flags/analytics/Analytics.tsx
Probably it happens because the input dates are changing too often during renders and forces redux rtk to do another fetch.
=> fix(ui): prevent multiple analytics requests at once with polling

ui/src/utils/helpers.ts
Fixes #2789 
Remove the call for `toLowerCase()` from the stringAsKey function as upper-case letters are acceptable in keys.
=> fix(ui): stop removing upper case letters in keys

.github/workflows/test.yml, internal/server/audit/audit.go, internal/server/audit/audit_test.go, internal/server/auth/middleware/grpc/middleware.go, internal/server/auth/middleware/grpc/middleware_test.go, internal/server/auth/server.go, internal/server/auth/server_test.go, internal/server/middleware/grpc/middleware_test.go, ui/src/components/SessionProvider.tsx, ui/src/components/header/UserProfile.tsx, ui/src/types/Auth.ts, ui/src/types/auth/JWT.ts
Add JWT auth changes for a user to be able to view their JWT auth information in the browser and also change event structure to create an actual structure for Actor information.
⚠️ **BREAKING CHANGE**
The `Actor` field in the event payload is changing. This will affect downstream consumers who are consuming webhooks from webhook templates. This is in favor of a more type safe way of expressing "Actor".
=> feat: add JWT aware UI and revise metadata for audit events

ui/src/components/flags/VariantForm.tsx, ui/src/data/validation.test.ts, ui/src/data/validations.ts
closes #2882
Currently `flipt.cue` doesn't have any restrictions on symbols for `Variant.key` and UI is misaligned here. Is any other symbols should be allowed in UI?
=> fix(ui): allow dot in the key of variant

ui/src/components/Chips.tsx, ui/src/components/forms/Tags.tsx, ui/src/components/segments/ConstraintForm.tsx
=> fix(ui): assistance for arrays data in constraints

config/flipt.schema.cue, config/flipt.schema.json, internal/config/authentication.go, internal/config/config_test.go, internal/config/testdata/authentication/github_missing_org_when_declaring_allowed_teams.yml, internal/server/authn/method/github/server.go, internal/server/authn/method/github/server_test.go
As we've discussed in the related issue I'm opening this PR to introduce a new _filter_ for GitHub OAuth method allowing people to define `allowed_teams` plus to `allowed_organizations`!
Closes #2849
=> feat: add team membership check to GitHub authentication method

cmd/flipt/bundle.go, config/flipt.schema.cue, config/flipt.schema.json, internal/config/config_test.go, internal/config/storage.go, internal/config/testdata/storage/oci_invalid_manifest_version.yml, internal/config/testdata/storage/oci_provided_full.yml, internal/oci/file.go, internal/server/audit/logfile/logfile_test.go, internal/storage/fs/store/store.go
Hi! I'm opening this PR to fix that issue with AWS ECR, when using the OCI Manifest Version 1.1 I receive an error from AWS but when setting to version 1.0 everything works as expected!
So I make it configurable keeping the current using version as default! I searched a bit the code to see if flipt could have any impact on letting the users choose between versions and the answer is **no**, flipt won't use the newly added field (on 1.1 version) `subject`! If you want to compare: [v1.0.2](https://github.com/opencontainers/image-spec/blob/v1.0.2/manifest.md) abd [v1.1.0](https://github.com/opencontainers/image-spec/blob/v1.1.0/manifest.md)
Other people are having the same impact:
* https://github.com/oras-project/oras/issues/1133
* https://github.com/oras-project/oras/issues/1224
Fixes #2907
=> feat: make oci manifest version configurable

internal/storage/sql/common/evaluation.go
If you create a segment with the same key in different namespaces - evaluation will take into account constraints of both segments
=> Fix namespace conflict

ui/package-lock.json, ui/package.json, ui/src/components/console/ContextEditor.tsx, ui/src/components/console/lint.ts
closes #2909
This is not ideal solution but it's provide a better understanding of the issue
=> fix(ui): evaluation console provides the warning for user about context values

config/flipt.schema.cue, config/flipt.schema.json, go.work.sum, internal/config/config_test.go, internal/config/storage.go, internal/config/testdata/storage/git_provided_with_directory.yml, internal/storage/fs/git/store.go, internal/storage/fs/git/store_test.go, internal/storage/fs/git/testdata/subdir/.flipt.yml, internal/storage/fs/git/testdata/subdir/alternative.yml, internal/storage/fs/store/store.go
Supports https://github.com/flipt-io/flipt-server-sdks/issues/158
This adds support for users specifying a `directory` context with the `git` type storage backend.
When declared the backend will perform its flag state location process rooted from the defined directory.
This would allow folks to deploy Flipt multiple times over the same repository for e.g. different environments.
Environments can then be modelled as directories instead of namespaces or branches in this situation.
=> feat(fs/git): add support for a directory scope

core/validation/flipt.json
Correctly validate both cases for rollout segment in the JSON schema:
```
rollouts:
- segment:
key: Single-Constraint
value: false
- segment:
keys:
- Single-Constraint
- Any-Constraint-Segment
value: false
```
=> fix: jsonschema to correctly validate key|keys in rollout segment

config/flipt.schema.cue, config/flipt.schema.json
Re: https://github.com/flipt-io/flipt/discussions/2943
Removes invalid 'trace' level from schemas
=> fix: invalid trace log level schema

config/migrations/clickhouse/3_alter_add_entity_id.up.sql, internal/server/analytics/clickhouse/mutation.go, internal/server/analytics/sink.go, internal/server/middleware/grpc/middleware.go, internal/storage/sql/migrator.go
When using percentage rollout, we need to know evaluation result by entityId.
=> Add entityId to clickhouse analytics

go.work.sum, internal/storage/authn/cache/cache.go, internal/storage/authn/cache/cache_test.go
re: https://github.com/orgs/flipt-io/discussions/2971#discussioncomment-9066911
dont store auth tokens in cache, only hash
=> fix(security): only store auth hash in cache

build/testing/cli.go, cmd/flipt/main.go, internal/config/config.go, internal/config/config_test.go, internal/storage/fs/object/mux.go, internal/storage/fs/object/mux_test.go, internal/storage/fs/object/store.go, internal/storage/fs/object/store_test.go, internal/storage/fs/store/store.go
=> feat(config): support remote blob storage for service configuration

config/flipt.schema.cue, config/flipt.schema.json, examples/openfeature/main.go, go.mod, go.sum, internal/cmd/grpc.go, internal/config/config.go, internal/config/config_test.go, internal/config/testdata/tracing/otlp.yml, internal/config/testdata/tracing/wrong_propagator.yml, internal/config/testdata/tracing/wrong_sampling_ratio.yml, internal/config/tracing.go, internal/server/evaluation/evaluation.go, internal/server/evaluator.go, internal/server/otel/attributes.go, internal/storage/sql/db.go, internal/tracing/tracing.go, internal/tracing/tracing_test.go
This PR introduces two new configuration options under `tracing` section:
* __samplingRatio__: Allow the users to define how much the sample they want to send to their collector, it's handy to let the user control the volume going out
* __propagators__: Allow the users to define one or more propagators, this is specially useful when dealing with propagator migrations or in the environment where each team can decide what to use
Both additions are non breaking change as I kept the default value the same!
More information in the tracer resource was added as well as new span attributes for evaluation methods!
Additionally I've changed the imports of `go.opentelemetry.io/otel/semconv` to use the latest version as every import were using a different and old version! This also shouldn't break …
=> feat: improve open telemetry tracing instrumentation

config/flipt.schema.cue, config/flipt.schema.json, internal/cmd/authn.go, internal/config/authentication.go, internal/server/authn/middleware/grpc/middleware_test.go
Re: #2985 
- Adds support for validating `subject` in JWT claims
- Custom claim validation support will require more work as the [library we use to validate](https://pkg.go.dev/github.com/hashicorp/cap@v0.6.0/jwt#Expected) JWTs does not support custom claim validation so we will need to do it ourselves
/cc @tstraley
=> feat(authn): allow validation of jwt subject claim

go.work.sum, internal/cmd/grpc.go
Fixes #3017 
This skips authentication for the evaluation data service when the evaluation API is marked as skipping authentication.
=> fix(cmd/grpc): skip eval data service when evaluation API auth excluded

CHANGELOG.md
This simply brings along the updates for the v1.40.2 changelog into `main`.
=> chore: update changelog for v1.40.2

go.mod, go.sum, internal/config/config_test.go
Re: #3034 
ℹ️ this shows how the test would have caught #3034 , we should rebase this test on that branch or main once it gets merged in for this test to pass
Adds a test to hopefully catch any incorrect struct tag values:
```
/Users/markphelps/workspace/flipt/internal/config/config_test.go:1515: 
Error Trace:	/Users/markphelps/workspace/flipt/internal/config/config_test.go:1515
/Users/markphelps/workspace/flipt/internal/config/config_test.go:1526
/Users/markphelps/workspace/flipt/internal/config/config_test.go:1498
Error:      	Should be true
Test:       	TestStructTags
Messages:   	mapstructure tag for field 'TracingConfig.SamplingRatio' should be snake_case but is 'samplingRatio'
=> chore: add test to catch invalid struct tags

build/testing/cli.go, build/testing/testdata/cli.txt, cmd/flipt/cloud.go, cmd/flipt/config.go, cmd/flipt/main.go, config/flipt.schema.cue, config/flipt.schema.json, go.work.sum, internal/cmd/cloud/local_server.go, internal/cmd/cloud/web_flow.go, internal/cmd/util/browser.go, internal/cmd/util/prompt.go, internal/config/server.go
Fixes: FLI-958
Adds cloud auth command
```
/bin/flipt cloud --url="http://localhost:3000" auth
```
=> feat: Cloud Authn

cmd/flipt/main.go, go.mod, go.sum
This:
- Upgrades to reverst 0.1.5 so that context canceled propagates through.
- Updates the tunnel so that it returns `nil` in the face of context.Canceled.
=> fix(cloud): improve shutdown logging

build/testing/integration/readonly/readonly_test.go, build/testing/integration/readonly/testdata/main/default.yaml, build/testing/integration/readonly/testdata/main/production.yaml, internal/storage/fs/snapshot.go, internal/storage/fs/snapshot_test.go, internal/storage/fs/testdata/valid/explicit_index/prod/prod.features.yml
Fixes #3076 
See failing test case:
```
readonly_test.go:553: 
Error Trace:	/src/build/testing/integration/readonly/readonly_test.go:553
Error:      	Received unexpected error:
rpc error: code = NotFound desc = rule "12c38328-8077-4629-ade9-a4831db41279" not found
Test:       	TestReadOnly/[Protocol_"grpc";_Namespace_"default";_Authentication_K8sAuth]/Evaluation/Variant/match_no_distributions
```
This fixes `GetEvaluationDistributions` to retun an empty set, instead of rule not found when a rule is defined with no distirbutions.
=> test(integration): add failing case for rules with no distributions

cmd/flipt/cloud.go, internal/server/authn/middleware/grpc/middleware.go, internal/server/authn/middleware/grpc/middleware_test.go, ui/src/components/Header.tsx, ui/src/components/header/UserProfile.tsx, ui/src/types/auth/Github.ts, ui/src/types/auth/JWT.ts, ui/src/types/auth/OIDC.ts
Fixes: FLI-1019
Fixes: FLI-894
Uses the `iss` property in the JWT to redirect the user to cloud if they are logged in using cloud method on logout
=> feat: logout redirect to cloud issuer

.github/workflows/nightly.yml, .github/workflows/snapshot.yml
Fix nightly and snapshot workflows as mage doesn't exist for v1.15 on darwin
https://github.com/flipt-io/flipt/actions/runs/8886339670/job/24399582939#step:8:10
https://github.com/magefile/mage/issues/481
=> fix: nightly and snapshot builds (mage)

go.work.sum, internal/storage/fs/git/reference_resolvers.go, internal/storage/fs/git/reference_resolvers_test.go, internal/storage/fs/git/store.go, internal/storage/fs/git/store_test.go, internal/storage/fs/store/store.go
This is an optimization to ensure that we only ever fetch either tracked or newly requested references from the upstream.
Prior to this change, we always fetched _all_ references from the upstream.
Now instead, we always pull the main reference, plus any newly requested refs or previously fetched refs still in the LRU.
I just added an additional change to this, to ensure that when a branch is supplied (only a branch, not a tag or SHA), that we also perform a single branch clone. So that we don't start off with a full clone.
One user reported to us that a new branch in their upstream was unnecessarily fetched and this caused memory pressure on their instance and it OOMed.
Their relevant feedback on this change:
> I tracked down the culprit of our sudden increase in resource usage to a …
=> perf(fs/git): only fetch known or newly requested references

internal/server/audit/cloud/cloud_test.go, internal/server/audit/events.go, internal/server/audit/logfile/logfile_test.go, internal/server/audit/template/executer_test.go, internal/server/audit/template/template_test.go, internal/server/audit/webhook/client.go, internal/server/audit/webhook/client_test.go, internal/server/audit/webhook/webhook_test.go, internal/server/authz/engine.go, internal/server/authz/engine_test.go, internal/server/authz/middleware/grpc/middleware.go, internal/server/authz/middleware/grpc/middleware_test.go, internal/server/authz/policies/default.json, internal/server/middleware/grpc/middleware.go, rpc/flipt/auth/request.go, rpc/flipt/request.go
- adds `scope` to request model to aide in authz, as we will be 'scoping' authz policies to be at the `namespace`, `flag`, `segment`, and `token` levels. ie we wont support policies where you can update a flag but not a variant since variants are 'nested' under flags
- if no `scope` is present, then we will fallback to the `subject` for authz
- move past tense logic for audit events into the part of code that creates audit events
- get rid of un-needed audit event custom marshaller
- adds `namespaced` interface to `requestor` as we'll need to be able to get the namespace of the request for future RBAC support
I initially was going to have the `Request` also know how to 'create' it's own audit event, however I realized this wasn't really possible since the majority of audit events include …
=> chore: refactor request models to include scope

internal/config/config_test.go, internal/config/storage.go, internal/config/testdata/storage/git_provided_with_backend_type.yml, internal/config/testdata/storage/git_provided_with_storage_type.yml, internal/storage/fs/git/store.go, internal/storage/fs/git/store_test.go, internal/storage/fs/store/store.go
This adds support for having the Git backend clone to local disk.
The motivation is to offload some of the memory pressure for large repositories onto disk.
This way memory doesn't have to scale in proportion to repository size, with the tradeoff that initial clone and fetch times may be increased due to I/O on local disk.
```yaml
storage:
type: git
git:
backend:
type: filesytem
path: /path/to/dir # optional: will create a tempdir in systems temp dir location otherwise
```
=> feat(fs/git): add support for cloning target repository to the local filesystem

go.work.sum, internal/cmd/cloud/local_server.go
Should fix: FLI-1037
Write the html response before sending the token down the channel which causes the server to shutdown
=> fix: write response for cloud login before server shutdown

config/flipt.schema.cue, config/flipt.schema.json, internal/cmd/grpc.go, internal/config/authorization.go, internal/config/config.go, internal/config/config_test.go, internal/config/testdata/advanced.yml, internal/config/testdata/authorization/all_authentication_methods_enabled.yml, internal/config/testdata/marshal/yaml/default.yml, internal/server/authz/engine.go, internal/server/authz/engine_test.go, internal/server/authz/middleware/grpc/middleware.go, internal/server/authz/middleware/grpc/middleware_test.go, internal/server/authz/source/filesystem/filesystem.go, rpc/flipt/request.go
Fixes FLI-1028
This refactors the engine to source policy and optionally data from a configurable source.
Currently, this is simply a path on the filesystem which is periodically read.
The filesystem source uses mod time to avoid causing the policy engine to need to be recompiled or for the data to have to be updated when it does not change.
p.s. I renamed scope to resource because I think scope is often the tuple of subject/resource and action/verb (e.g. `flag:read`).
=> refactor(server/authz): make policy and data external dependencies

config/flipt.schema.cue, config/flipt.schema.json, internal/config/config_test.go, internal/config/storage.go, internal/config/testdata/storage/git_provided_with_backend_type.yml, internal/storage/fs/store/store.go
As per a discussion in https://github.com/flipt-io/flipt/pull/3108#discussion_r1612321837
We're changing `storage.git.backend == filesystem` to `storage.git.backend == local`.
This is to keep it consistent with local naming conventions which exist.
This is not technically a breaking change, because this code is currently unreleased.
=> change(config): rename git backend filesystem to local

internal/cmd/grpc.go
We found that redis shutdown is unexpected on grpc server exit while redeploying Flipt.
=> fix: prevent redis shutdown

cmd/flipt/cloud.go, cmd/flipt/main.go, internal/cmd/grpc.go
Fixes: FLI-1039
- use cloud auth token from JWT instead of API key if present when running `flipt cloud serve`
=> fix: use cloud auth token from JWT instead of API key if present

internal/server/audit/audit_test.go, internal/server/audit/events.go, internal/server/audit/logfile/logfile_test.go, internal/server/authn/server.go, internal/server/authz/middleware/grpc/middleware.go, internal/server/authz/middleware/grpc/middleware_test.go, rpc/flipt/auth/request.go, rpc/flipt/request.go
Updates the call to `IsAllowed` to take a map containing both the entire request structure and the entire authentication instance.
=> refactor(authz): pass entire request and authentication to IsAllowed

ui/src/components/header/UserProfile.tsx
Fixes #3131 
This makes the logout function await expiring self before navigating away to the issuer or root.
=> fix(ui): await expiring auth self before redirecting

cmd/flipt/cloud.go
prompt for login if no token present or it's expired for `flipt cloud serve`
who doesnt love a GOTO statement?
=> chore: prompt for login if no token

.devcontainer/Dockerfile, .github/workflows/devcontainer.yml, config/flipt.schema.cue, config/flipt.schema.json, internal/config/authentication.go, internal/server/authn/method/github/server.go, internal/server/authn/method/oidc/server_test.go
This PR adds support for GHE (Self hosted GitHub Enterprise).
Currently only github.com is supported. In some cases there is the need to have GitHub running on a self hosted instance due to security and isolation reasons. This PR adds support for all GitHub scenarios.
**Note:** Separate PR from #3127
=> feat: add support for ghe

config/flipt.schema.cue, config/flipt.schema.json, internal/config/config_test.go, internal/config/testdata/ui/topbar_color.yml, internal/config/testdata/ui/topbar_invalid_color.yml, internal/config/ui.go, ui/src/App.tsx, ui/src/app/meta/metaSlice.ts, ui/src/components/Header.tsx, ui/src/components/Sidebar.tsx, ui/src/types/Meta.ts
=> feat(ui): allow change top bar theme color

build/main.go
this makes running `dagger functions` and `dagger call test --help` via the CLI a bit more useful.
```
levlaz@Levs-MacBook-Pro flipt % dagger functions
Name             Description
base             Returns a container with all the assets compiled and ready for testing and distribution
base-container   -
build            Return container with Flipt binariesin a thinner alpine distribution
generate         Execute generate function with subcommand
source           -
test             Execute test specific by subcommand
uicontainer      -
levlaz@Levs-MacBook-Pro flipt % dagger call test --help
Execute test specific by subcommand
see all available subcommands with dagger call test --help
USAGE
dagger call test [arguments] <function>
FUNCTIONS
base-container
cli               Run all cli tests …
```
=> add docstrings to functions

internal/server/audit/events.go, internal/server/audit/events_test.go, internal/server/audit/log/log.go, internal/server/audit/log/log_test.go
related to #3101  https://github.com/flipt-io/flipt/pull/3113#issuecomment-2152577268
=> fix(audit): preserve audit log scheme

ui/src/app/console/Console.tsx, ui/src/components/forms/Dropdown.tsx, ui/src/types/Cli.ts, ui/src/utils/helpers.ts
Related to https://github.com/flipt-io/flipt/issues/2863
=> feat: allow to copy evaluate command in a CLI format

.github/workflows/test.yml, build/testing/migration.go
This is a fix for the migration test suite which has been failing since I refactored all the things.
There were a couple things I overlooked for this particular IT suite in the move.
There were two things I changed in the read only harness. Those were that now both namespaces are tested explicitly in the harness itself (remove from the matrix) and I made it so that the harness uses the bootstrap token to create a new token for the lifetime of the test.
What we're seeing in the other suites is the authentication method service is not mounted, because this suite has historically not need auth to work (now it does). So I have enable token method, made auth required and created a bootstrap token. Additionally, I have imported both the production and default namespace data (we only needed …
=> fix(build): configure token authentication for migration test suite

install.sh
During the installation of flipt CLI on Debian servers with `curl -fsSL https://get.flipt.io/install | sh` as mentioned in the flipt docs https://docs.flipt.io/self-hosted/overview due to lack of POSIX complaint, the script used to crash since these scripts had a lot of Bashism into it, but marked as `#!/bin/sh` as well as in doc, it's piped to sh. 
Now the prior script was working on bash and it's the default shell for most of the Linux distros, it contains keywords that are only supported on bash and will fail with sh. Scripts running on sh can run on bash due to its POSIX compliance, and hence, it was a good idea to elevate it to sh improving its portability. 
By making this script POSIX compliant, it would be working on most of the shells beyond bash. 
The final script is tested on …
=> Installation made fully POSIX compliant for sh based shells

build/magefile.go, build/release/release.go
add back magefile for release task
makes it so `mage -d build release:changelog go.flipt.io/flipt $(mage -d build release:next go.flipt.io/flipt minor)` still works
Maybe in the future we replace this with an interactive script?
=> chore: add back magefile for release task

.github/workflows/test.yml
I think previously we  didnt have to pass `CODECOV_TOKEN` to the  upload action, but now it seems like its required:
https://github.com/codecov/codecov-action/tree/v4.5.0/?tab=readme-ov-file#usage
=> chore: try to fix codecov uploading

build/testing/test.go, internal/storage/sql/db_test.go, magefile.go
test coverage was not being aggregated correctly because it wasn't considering tests not in the same package as the code under test, `-coverpkg=./...` fixes this
=> chore: fix test coverage not being reported correctly

cmd/flipt/cloud.go, go.mod, go.sum, internal/server/audit/kafka/kafka_test.go, ui/package-lock.json, ui/package.json
Fixes: FLI-1091
We have decided to remove the `flipt cloud serve` command and require all cloud environments to be created from flipt.cloud
=> chore: remove flipt cloud serve

internal/cmd/grpc.go
Fixes: #3283 
It seems the retryiableHTTP lib accepts any old `interface{}` for its `Logger`.. this is why it passed buildtime but fails at runtime since it actually enforces the logger type at runtime
https://github.com/hashicorp/go-retryablehttp/blob/40b0cad1633fd521cee5884724fcf03d039aaf3f/client.go#L408
simple fix here is to just not pass our own logger to the httpClient
=> fix: passing invalid logger to retriable http client

go.work.sum, internal/common/store_mock.go, internal/ext/common.go, internal/storage/fs/git/store.go, internal/storage/fs/object/file.go, internal/storage/fs/object/file_test.go, internal/storage/fs/object/fileinfo.go, internal/storage/fs/object/fileinfo_test.go, internal/storage/fs/object/store.go, internal/storage/fs/oci/store.go, internal/storage/fs/snapshot.go, internal/storage/fs/snapshot_test.go, internal/storage/fs/store.go, internal/storage/fs/store_test.go
=> feat: support etag for declarative stores

cmd/flipt/import.go, internal/ext/importer.go, internal/ext/importer_fuzz_test.go, internal/ext/importer_test.go, internal/ext/testdata/import_new_flags_only.json, internal/ext/testdata/import_new_flags_only.yml, internal/storage/sql/evaluation_test.go
=> Add import append flag to import new flags/segments only not existing in DB yet

CHANGELOG.md
As mentioned in both the release branch PRs.
This is just the changelog updates in isolation to keep main up to date.
=> chore: update CHANGELOG for 1.45.2 and 1.46.2

.github/workflows/integration-test.yml, build/testing/integration.go, build/testing/integration/integration.go, build/testing/integration/snapshot/snapshot.go, build/testing/integration/snapshot/snapshot_test.go, go.work.sum
while I was looking into #3325 , I realized the (previously) REST ITs which were to test the snapshot / data API were not actually being run
Once I got them running, they weren't actually passing.
This fixes both
=> chore: fix snapshot ITs

internal/storage/sql/db.go, internal/storage/sql/db_internal_test.go
this change resolves https://github.com/flipt-io/flipt/issues/3351 by registering `postgresql` URL alias.
=> feat: support postgresql url prefix

internal/server/authn/middleware/grpc/middleware.go
Had some difficulty debugging the namespace scoped token error, so improved the error message reason.
=> fix: use different error messages for namespace scoped token errors

.github/workflows/test.yml, buf.gen.yaml, openapi.yaml
re: https://github.com/flipt-io/docs/pull/258#issuecomment-2274368235
=> chore: openapi enum type to string

.github/workflows/integration-test.yml, .github/workflows/test.yml
Thought I would pepper this everywhere to avoid the out of disk issues we have been seeing.
=> ci: clear unused tools before dagger runs

.github/workflows/nightly.yml
Try to fix StackHawk scanner action
https://github.com/flipt-io/flipt/actions/runs/10461968611/job/28971622605
https://github.com/stackhawk/hawkscan-action?tab=readme-ov-file#java-requirements-for-hawkscan
Also use openapi.yml in root of repo, don't need to download it from anywhere now
=> chore: try to fix stackhawk action

ui/src/app/console/Console.tsx
With all changes to flags dashboard and showing the boolean flags as
always enabled this commit makes the same for console.
related #3300
=> fix(ui): show boolean flags as enabled in the console dropdown

go.work.sum, ui/src/app/flags/flagsApi.ts, ui/src/app/segments/segmentsApi.ts, ui/src/components/flags/FlagTable.tsx, ui/src/components/segments/SegmentTable.tsx, ui/src/store.ts
Re: #3413 
Moves sorting state of tables to redux so that it persists between pages
=> feat(ui): save sort state in redux

internal/storage/sql/db.go, internal/storage/sql/db_internal_test.go
Hi! According to the migration from `lib/pq` to `pgx` in [v1.41.0](https://github.com/flipt-io/flipt/releases/tag/v1.41.0) it's necessary to replace `binary_parameters=yes` option with `default_query_exec_mode=simple_protocol `. Otherwise, the use of prepared statements will not be disabled.
Reference: https://pkg.go.dev/github.com/jackc/pgx/v5#ParseConfig.
=> fix(storage): enable pgx simple protocol if prepared statements disabled

internal/server/authz/middleware/grpc/middleware.go, internal/server/evaluation/data/server.go, internal/server/evaluation/data/server_test.go, internal/server/middleware/grpc/middleware.go, rpc/flipt/auth/request.go, rpc/flipt/evaluation/request.go, rpc/flipt/request.go
This is proposal for the open PR https://github.com/flipt-io/flipt/pull/3438
It changes the solution so that we actually request specific permissions when attempting to fetch evaluation snapshot data.
In order to enforce some level of authz and not leak entire namespace contents this way.
=> fix(rpc/flipt): implement Requester for evaluation data snapshot

build/testing/integration/snapshot/snapshot_test.go, internal/server/evaluation/data/server.go, rpc/flipt/evaluation/request.go
Re: #3438 
Adds support for namespace scoped tokens for evaluation data api
=> fix: support scoped namespace tokens for evaluation data api

internal/server/audit/types.go, internal/server/audit/types_test.go
=> fix(audit): include default_variant into flag audit payload

examples/nextjs/README.md, examples/nextjs/components/Greeting.tsx, examples/nextjs/package-lock.json, examples/nextjs/package.json, examples/nextjs/pages/index.tsx
Updates to swap out `flipt-node` with `flipt-client-node` and updates to latest browser SDK
This is to show that both JS client side SDKs work in different contexts in NextJS
=> chore: update NextJS example to use updated versions of Flipt clientside SDKs

internal/ext/exporter.go, ui/src/app/flags/rules/Rules.tsx, ui/src/components/forms/Combobox.tsx, ui/src/components/rules/forms/QuickEditRuleForm.tsx
related #3417
This isn't a fix for the original problem but improvement for people to see the problem and fix it.
=> fix(export): display a better error for missing segments and don't hide them in ui

.goreleaser.nightly.yml, .goreleaser.yml
fix deprecated goreleaser warnings
https://goreleaser.com/deprecations/#nightlyname_template
=> chore: fix deprecated goreleaser warnings

internal/cmd/grpc.go, internal/common/store_mock.go, internal/server/ofrep/errors.go, internal/server/ofrep/evaluation.go, internal/server/ofrep/evaluation_test.go, internal/server/ofrep/extensions_test.go, internal/server/ofrep/middleware_test.go, internal/server/ofrep/server.go
Rework bulk evaluation logic to fetch namespace flags if ones are not provided in the evaluation context. As result
all boolean and enabled variant flags will be evaluated.
fixes #3412
=> fix(ofrep): relax flags constraint for bulk evaluation

internal/cmd/http.go, internal/server/middleware/grpc/middleware.go, internal/server/middleware/grpc/middleware_test.go
From Discord [message](https://discord.com/channels/960634591000014878/1303354231901917329/1303366864466088091)
>  I have two namespaces : Default and test with different flags. By passing in the header X-Flipt-Namespace: test, i always have the flags from Default namespace
=> fix(ofrep): forward x-flipt-namespace http header from grpc-gateway to the ofrep service

ui/src/app/flags/rules/Rules.tsx, ui/src/components/rollouts/Rollouts.tsx, ui/src/components/rollouts/forms/QuickEditRolloutForm.tsx, ui/src/components/rules/forms/QuickEditRuleForm.tsx
This pr addressed these scrolls in Chrome on Linux.
=> fix(ui): remove unnecessary scrolls for quick edit forms

rpc/flipt/validation.go
Fixes: https://github.com/flipt-io/flipt/issues/3594
=> fix: update attachment messaging and size to allow 1mb

ui/src/assets/colors/dark.css
UI uses some elements for input date, time, etc... They have extra icon
which very hard to see in dark mode and their popups have white
background.
Before
After
=> fix(ui): use dark scheme for browser built-in inputs/scrolls in dark mode

internal/ext/encoding.go, internal/ext/importer.go, internal/ext/importer_test.go, internal/ext/testdata/import_flag_complex_metadata.json, internal/ext/testdata/import_flag_complex_metadata.yml
This pull request includes several changes to the `internal/ext` package to enhance the encoding and importing functionalities. 
-  `yaml.v3` is used as import encoder. It returns `map[string]any` instead of `map[any]any` in `jaml.v2`. 
-  fix the issue with importing json backups generated by `flipt export -o file.json`
closes #3635  
closes #3636
=> fix(import): import flags with complex metadata

internal/config/authentication.go, internal/config/storage.go
=> fix(config): incorrect json serialization tag

config/flipt.schema.cue, config/flipt.schema.json, examples/analytics/prometheus/docker-compose.yml, examples/analytics/prometheus/flipt-config.yml, examples/analytics/prometheus/web-config.yml, internal/config/analytics.go, internal/server/analytics/prometheus/client.go
Prometheus supports basic auth. Fly.io has bearer token or own Fly
token. To simplify maintenance and Flipt configuration, this PR will allow to set
HTTP Authorization header with value from prometheus auth_token configuration.
=> feat(analytics): allow to set Authorization header for prometheus

ui/package-lock.json, ui/package.json, ui/src/app/Layout.tsx, ui/src/app/console/Console.tsx, ui/src/app/flags/Flag.tsx, ui/src/app/flags/Flags.tsx, ui/src/app/flags/NewFlag.tsx, ui/src/app/segments/NewSegment.tsx, ui/src/app/segments/Segment.tsx, ui/src/app/segments/Segments.tsx, ui/src/components/flags/FlagTable.tsx, ui/src/components/segments/SegmentTable.tsx, ui/src/components/ui/badge.tsx, ui/src/components/ui/button.tsx, ui/src/components/ui/guide.tsx, ui/src/components/ui/input.tsx, ui/src/components/ui/page.tsx, ui/src/components/ui/search.tsx, ui/src/components/ui/select.tsx, ui/src/components/ui/table-pagination.tsx, ui/src/components/ui/table-view-options.tsx, ui/tests/namespaces.spec.ts
This pull request includes several changes across multiple files to improve the UI components . The key changes involve the use of a new `PageHeader` component for better consistency in the layout, updates to the flags and segments tables.
=> feat(ui): new table view for flags and segments

build/testing/integration/api/api.go, go.work.sum, internal/config/database.go
Fix issue raised in Discord about url being return in meta/config endpoint which can contain db creds
=> fix: dont return db url in meta/config response

ui/src/components/flags/FlagTable.tsx
small ui tweak on flags table, i think it looks better without the dot between the enabled badge on flags table
=> chore: rm dot between enabled badge on flags table

ui/src/app/flags/Flags.tsx, ui/src/app/segments/Segments.tsx, ui/src/components/flags/FlagTable.tsx, ui/src/components/segments/SegmentTable.tsx, ui/src/components/ui/skeleton.tsx, ui/src/components/ui/table-skeleton.tsx
If there is small network delay the flags or segments table could show
intro message, which could mislead a bit. Instead of using loader I
would like to use skeleton idea.
=> fix(ui): use table skeleton while flags or segments are loading

cmd/flipt/main.go, internal/config/storage.go, internal/config/storage_test.go, internal/info/flipt.go, internal/info/flipt_test.go, ui/src/app/Layout.tsx, ui/src/app/meta/metaSlice.ts, ui/src/app/preferences/preferencesSlice.ts, ui/src/components/SessionProvider.tsx, ui/src/data/api.ts, ui/tests/flags.spec.ts, ui/tests/index.spec.ts, ui/tests/namespaces.spec.ts, ui/tests/rollouts.spec.ts, ui/tests/rules.spec.ts, ui/tests/segments.spec.ts
`/meta/config` exposes too much configuration and UI doesn't need that much. There were few leakage of the secrets as people provide configuration options in their way and that fire seem never to stop. 
The global idea is to drop `/meta/config` endpoint and this is a first step to it.
=> refactor(ui): stop using /meta/config endpoint

ui/src/components/flags/FlagTable.tsx, ui/src/components/segments/SegmentTable.tsx
Somehow useMemo was missed for those places and if the error occurs
react goes crazy with rerender the page as it gets new empty array
=> fix(ui): cache data list for flags and segments

rpc/flipt/analytics/analytics.pb.gw.go, rpc/flipt/auth/auth.pb.gw.go, rpc/flipt/evaluation/evaluation.pb.gw.go, rpc/flipt/flipt.pb.gw.go, rpc/flipt/meta/meta.pb.gw.go, rpc/flipt/ofrep/ofrep.pb.gw.go, rpc/flipt/request.go, rpc/flipt/request_test.go, rpc/flipt/validation_test.go
Currently Flipt with authz requires user to have read access to default
namespace in order to list the namespaces. This edge case ninja'd its way
into the code like a shadow in the night, but it’s time for this stealthy
PR troublemaker to find another codebase to haunt!
Side effect 1: the deps has been updated and the code should be regenerated.
Side effect 2: the tests are broken with PR #3595 in RPC and they are not run
in CI.
related to #3692 #3688
=> fix: remove default namespace as a requirement to list namespaces

ui/src/app/namespaces/namespacesSlice.ts
There could be situations when previously selected or default
namespace is not available for user. It could be the case that
default namespace was deleted or authz has a specific rules.
This PR will try to get the first available namespace before
falling back to default mock.
related #3688
=> fix(ui): use available namespace as selected before default fallback

internal/server/authz/authz.go, internal/server/authz/engine/bundle/engine.go, internal/server/authz/engine/bundle/engine_test.go, internal/server/authz/engine/rego/engine.go, internal/server/authz/engine/rego/engine_test.go, internal/server/authz/engine/testdata/viewable_namespaces.json, internal/server/authz/engine/testdata/viewable_namespaces.rego, internal/server/authz/middleware/grpc/middleware.go, internal/server/authz/middleware/grpc/middleware_test.go, internal/server/namespace.go, internal/server/namespace_test.go
This PR enables the ListNamespaces API call, which is critical for the UI functionality. By default, the API will return all namespaces in the response. To ensure the response includes only the namespaces a user is permitted to access, the policy should specify a `viewable_namespaces` array containing the appropriate namespace strings.
closes #3688
=> fix(authz): support namespaces filtering

cmd/flipt/main.go, go.mod, go.sum, go.work.sum, internal/cmd/grpc.go, internal/cmd/http.go
Fixes issue raised in the community forum: https://community.flipt.io/t/ofrep-http-trace-context-propagation/66
It seems GRPC gateway / OTEL grpc instrumentation does not properly proxy the `traceparent` information via HTTP headers if present. This fixes that.
It also removes a couple deprecated method calls/setup from the OTEL/grpc projects
See: https://github.com/openfga/openfga/pull/1624
Note: I used stdoutracing for demonstrating the changes before/after
Note: This also adds a new span named `grpc-gateway` before the grpc gateway span (ie: `flipt.ofrep.OFREPService/EvaluateFlag`)
Here's an example request, note the `traceparent` header which is used for parent span propagation:
```
curl --request POST \
--url http://localhost:8080/ofrep/v1/evaluate/flags/adsfasd \
--header …
```
=> fix: otel http parent propogation

ui/package-lock.json, ui/package.json
There is a higher number for CI failures related to playwright tests
with no changes in Flipt UI. Few related bugs were fixed in 1.49.1 so
I hope it will help.
=> chore(deps): bump @playwright from 1.49.0 to 1.49.1

ui/package-lock.json, ui/package.json, ui/src/app/preferences/Preferences.tsx, ui/src/components/Switch.tsx, ui/src/components/forms/Toggle.tsx, ui/src/components/ui/table-skeleton.tsx
=> refactor(ui): replace headlessui Switch with radix-ui

go.work.sum, ui/src/app/flags/flagsApi.ts
=> fix: update flag with no metadata

examples/audit/kafka/README.md, examples/audit/kafka/docker-compose.yml, internal/server/audit/kafka/avro.go, internal/server/audit/kafka/encoding_test.go, internal/server/audit/kafka/kafka.go
There is no easy way to provide all possible schemas for event payload.
As workaround if the payload map have complex type it will be converted
into json string if avro encoding is enabled.
fixes #3825
=> fix(audit): allow to send events with complex payload to kafka with avro

ui/src/app/meta/metaSlice.ts
The regression when `/meta/config` was replaced with `/meta/info` for UI.
Refs: #3684
=> fix(ui): ui.topbar.color config setting has been broken since v1.53.0

internal/server/middleware/grpc/middleware_test.go, internal/server/middleware/grpc/support_test.go
Lots of little fixes. Bit by bit.
=> fix(tests/middleware): ensure eval interceptor noop tests valid rpc

internal/storage/fs/snapshot.go, internal/storage/fs/snapshot_test.go, internal/storage/fs/testdata/empty/features.yml, internal/storage/fs/testdata/production/features.yaml
This fixes are few things which did not work after the first pass moving eval snapshots into the existing fs/snapshot code.
There were a few missing fields on various types:
- Description on Rollout
- Value on Segment type Rollout
- The eval flag was not being appended from the flag set
- The eval snap rollout was not being append
- The eval snapshot namespaces map was not being initialized
I added a bunch of simply baseline unit tests which surfaced all of these things and then I fixed them in this PR.
Here is what the robots said:
* [`internal/storage/fs/snapshot.go`](diffhunk://#diff-a28ccda63499cc749c93d02fc6f1135d3a2289187b50ce0c941dfe03841bd798L174-R176): Initialized the `Namespaces` field in `evaluation.EvaluationSnapshot` within the `EmptySnapshot` function.
* …
=> fix(storage/fs): various fixes and base test cases

ui/package-lock.json, ui/package.json, ui/src/app/console/Console.tsx, ui/src/app/flags/rules/Rules.tsx, ui/src/components/Pagination.tsx, ui/src/components/constraints/Constraints.tsx, ui/src/components/namespaces/NamespaceTable.tsx, ui/src/components/rollouts/Rollouts.tsx
- bumps typescript version to more recent version (5.6)
- installs [knip](https://knip.dev/overview/getting-started) for finding dead ui code
- fix lint issues
- update some other ui deps
=> chore: bump ts version; install knip

ui/src/app/console/Console.tsx, ui/src/components/rollouts/QuickEditRolloutForm.tsx, ui/src/components/rollouts/Rollouts.tsx, ui/src/types/Rollout.ts
Based on #3907 
This fixes the the rollout segment quick form so that the available segments are listed.
=> fix(ui): use correct field segmentKeys on rollout segment

ui/src/app/Layout.tsx, ui/src/components/flags/FlagForm.tsx
Depends on https://github.com/flipt-io/flipt/pull/3909
Makes it a little wider for wider screens.
=> feat(ui): support larger screen widths

ui/src/app/Layout.tsx, ui/src/components/flags/FlagForm.tsx, ui/src/components/rollouts/EditRolloutForm.tsx, ui/src/components/rollouts/QuickEditRolloutForm.tsx, ui/src/components/rollouts/RolloutForm.tsx, ui/src/components/rollouts/Rollouts.tsx, ui/src/types/Rollout.ts
My attempt before didnt work.
It briefly did during a hot reload, but broke elsewhere in the site.
Then it became clear that it is `segments` in the API payload not segmentKeys.
Making it consistent everywhere seems to have it building again and working in my browser.
=> fix(ui): use segments instead of segmentKeys everywhere

ui/src/components/UnsavedChangesModal.tsx, ui/src/components/rollouts/Rollout.tsx, ui/src/components/rollouts/SortableRollout.tsx, ui/src/components/rules/Rule.tsx, ui/src/components/rules/SortableRule.tsx, ui/src/components/segments/SegmentForm.tsx, ui/tests/rollouts.spec.ts, ui/tests/rules.spec.ts
add / fix UI ITs for reordering/deleting rollouts and rules
=> chore: add UI ITs for reordering/deleting rules and rollouts

.devcontainer/Dockerfile, .github/workflows/integration-test.yml, DEPRECATIONS.md, DEVELOPMENT.md, Dockerfile, Dockerfile.dev, PLAN.md, build/Dockerfile, build/internal/flipt.go, cmd/flipt/main.go, magefile.go
prob going to break a bunch of things temporarily.. but I've always regretted having the server run with the root command and would prefer if for v2 we make it explicit like `flipt server`
also updates our dockerfiles to remove postgres lib and updates docs to rm notice for CGO since we arent using SQLite anymore
=> feat: V2 flipt server

internal/config/config.go, internal/config/config_test.go, internal/config/environments.go, internal/config/testdata/environments/no_default.yml, internal/config/testdata/environments/single_is_default.yml, internal/config/testdata/marshal/yaml/default.yml
we need to ensure that there is one and only one default environment for evaluation and UI purposes.
This change makes it so:
1. if there are no envs then we create an env called 'default' and set 'default.default = true'
2. if there is only one env, we set it as 'default'
3. if there are more than one env and none are marked as 'default' then we return an error
I'd love it if we could just make the first item in the env config the default env, but because ranging through Go maps do not guarantee order, I could not come up with a good way of doing this.. so just made it so the user/operator must be explicit
=> chore: fix config tests; make single env default; ensure atleast one default

internal/server/environments/mock_environment.go, internal/server/environments/storage.go, internal/server/evaluation/evaluation_test.go, internal/server/evaluation/mock_environmentstore.go, internal/server/evaluation/ofrep_bridge_test.go, internal/server/evaluation/server.go, internal/server/flag_test.go, internal/server/server.go, internal/storage/environments/environments.go, internal/storage/fs/config.go, internal/storage/git/filesystem.go, internal/storage/git/filesystem_test.go
This PR contains fixes for two things:
1. It supports the concept of a default env during evaluations
It adds a method `GetDefault` to the environment store to create a single path for legacy dependents.
This method handles picking the default env as per configuration.
2. Fixes empty snapshots
Since some recent refactors to remove `gitfs` in favour of `storage/git/filesystem` I created a situation where the snapshotting code silently fails to find any files. This caused empty snapshots to be used during evaluation.
This turned out to be due to the fact that there was no support for the `"."` path in the filesystems `Stat` implementation.
In the journey to fix this, I added support for `os.O_APPEND` to the implementation on writes (preserves original contents and simply appends).
As well …
=> fix(storage/git): support fs.WalkDir and current dir path

DEVELOPMENT.md
Just noticed a small typo in the formatting of the markdown of `DEVELOPMENT.md`.
=> docs: Fix typo in DEVELOPMENT.md

internal/cmd/authn.go, internal/storage/authn/auth.go, internal/storage/authn/memory/store.go, internal/storage/authn/redis/store.go
Fixes: #4093 
We were creating a new in-memory store for the auth service that handles logout instead of re-using the existing one. So creating the session auth would store the tokens either in memory or redis, but when trying to look them up to expire we would be looking in a different part of memory so they would never be found
=> fix: logout in ui error

internal/storage/authn/memory/store.go, internal/storage/authn/redis/store.go, internal/storage/authn/testing/testing.go
This pull request introduces updates to the Redis-based authentication store and its associated tests. The changes focus on improving the handling of authentication record expiration and ensuring consistency in time comparisons.
* [`internal/storage/authn/redis/store.go`](diffhunk://#diff-abeaff6900c1af1b4218b14af77f5d309fb0453899fb822992ab0ea870315f7cR350-R381): Enhanced the `ExpireAuthenticationByID` method to retrieve, unmarshal, update, and re-marshal the authentication record before updating its `ExpiresAt` and `UpdatedAt` fields. This ensures the record is properly updated in Redis with the new expiration time.
* [`internal/storage/authn/testing/testing.go`](diffhunk://#diff-4d5a2b55d592e1ca4b35d55ad0f71d0363067988a4e3cf1fa77d93377a5f750fL229-R229): Modified a test assertion to …
=> fix: issue with redis not setting expires at on auth record

internal/config/authentication.go, internal/config/authorization.go, ui/src/assets/colors/dark.css
- fixes missing shadows in v2 ui
- adds todos about redis cluster and prefix support for authn storage so I dont forget
- removes unused (for now) authz backends as we are only going to support local at initial release
=> fix: ui shadow missing in v2; remove unused authz configs for now

ui/src/app/Layout.tsx, ui/src/components/environments/EnvironmentListbox.tsx
Fixes a few ui layout/color issues including:
1. header not showing on top on scroll
2. env listbox not showing overtop banner
3. weird colors for env listbox in both light and darkmode
4. make default environment always the first in the env picker dropdown
=> fix: issue with z-index in layout/banner; color issues with env listbox

.github/workflows/alpha.yml, .goreleaser.darwin.yml, .goreleaser.linux.yml, .goreleaser.nightly.yml, .goreleaser.yml, cmd/flipt/main.go
rename the nightly build to alpha for now as we wont be running it nightly as github doesnt let you use cron actions against non-main branches
=> chore: change v2 nightly to v2 alpha

ui/src/components/Combobox.tsx, ui/src/components/forms/SegmentsPicker.tsx, ui/src/components/rollouts/QuickEditRolloutForm.tsx, ui/src/components/rollouts/RolloutForm.tsx, ui/src/components/rules/MultiDistributionForm.tsx, ui/src/components/rules/QuickEditRuleForm.tsx, ui/src/components/rules/RuleForm.tsx, ui/src/utils/formik-helpers.ts
fixes: #4143
This PR fixes a bug in the Flipt UI where adding segments to rules caused errors. The issue primarily manifested as "[object Object] not found in segments" when adding a new segment to an existing rule/rollout.
- Centralize segment management logic
- Handle proper object representation in forms
- Prevent duplicate rules/rollouts during updates
- Ensure proper array initialization
- Always initialize distributions as an array (never null)
- Use `rule.id` to find and update the correct rule in Formik state
- Optimize with `useMemo` and `useCallback` hooks
- Update entire rules collection to prevent duplicates
- Follow the same pattern as QuickEditRuleForm
- Fix type safety issues with segment value property
- Optimize performance with React hooks
- Ensure boolean values are …
=> fix: segment picker bugs

internal/cmd/http.go, internal/server/analytics/clickhouse/mutation.go, internal/server/metrics/metrics.go, internal/server/tracing/attributes.go, rpc/flipt/analytics/analytics.pb.go, rpc/flipt/analytics/analytics.pb.gw.go, rpc/flipt/analytics/analytics.proto, rpc/flipt/flipt.yaml, rpc/flipt/openapi.yaml, ui/src/app/flags/analytics/Analytics.tsx, ui/src/app/flags/analyticsApi.tsx, ui/src/data/api.ts, ui/src/utils/redux-rtk.ts, ui/vite.config.ts
fixes analytics for v2 by:
1. creating new `/internal/v2/analytics` endpoint which includes environment in the path
2. fixes metrics to be `_` separated instead of `.` so they are consistent between prometheus and otel
3. update ui analytics component to pass in env
=> V2 fix analytics

go.work.sum, internal/storage/fs/cache.go, internal/storage/fs/poll.go
follow up to #4184 
- Removes double eviction as the LRU cache calls evict for us 
- Turns error log level down to warn for failed fetch
=> chore: fix double evict; turn log down to warn

go.work.sum, internal/server/evaluation/evaluation.go, internal/server/evaluation/evaluation_test.go, ui/src/app/console/Console.tsx
Fixes 2 issues with evaluation:
1. on the console page, after directly linking there from a flag, while the flag was selected it would not let us submit the form because the field wasnt set in the formik context
2. much bigger issue, we werent correctly getting the environment from the request if provided, we were only looking in the header for V1 evaluation requests
one subtlty of this fix however is that users can issue batch eval requests for multiple environments. this isnt ideal as it means we'll be swapping out the env store in a loop.. but it is stored in memory so likely not tooo bad, but should be documented
=> fix: evaluation console and evaluation with envs

internal/storage/sql/common/rollout.go, internal/storage/sql/common/rule.go
The original fix was done in #3454 but updating rollout and rules were not resolved
closes #4230
=> fix(storage): map protobuf enums to ints in sql updates for rule and rollout

ui/src/components/Dropdown.tsx
In v1, we had custom styling for the file/segment dropdown. However, the default styling (which is also used for the branch dropdown) looks good and provides a consistent experience.
To keep the UI consistent across components, I prefer using the default styling everywhere.
=> fix(ui): v2 use the same style for dropdown

cmd/flipt/main.go, cmd/flipt/quickstart.go, internal/cmd/util/browser.go
Adds `flipt quickstart` command that walks user through setting up their first environment and synching to github/gitlab/gitea
```
🚀 Welcome to Flipt v2 Quickstart!
This wizard will help you configure Git storage syncing with a remote repository.
This will overwrite your existing config file if it exists.
? Would you like to continue? Yes
? Git repository URL (e.g., https://github.com/owner/repo.git): https://gitlab.com/markphelps/flipt-features
? Is GitLab the correct provider? Yes
✅ Using GitLab repository: markphelps/flipt-features
? Default branch name: main
? Directory to store data in remote repository: flipt
? Are you using a self-hosted/enterprise GitLab instance? No
? Would you like to open your browser to create an API token? Yes
🌐 Opening …
```
=> V2 quickstart cmd

internal/cmd/http.go, internal/server/flag.go, internal/server/flag_test.go
Fixes #4411 - The v1 ListFlags endpoint was not respecting the X-Environment header for backward compatibility.
- **Modified `internal/server/flag.go`**: Updated `ListFlags` method to check for X-Environment header from context and use it if present, overriding the request parameter
- **Modified `internal/cmd/http.go`**: Added `ForwardFliptEnvironment` middleware to the v1 API gateway to ensure the X-Environment header is properly forwarded from HTTP to gRPC
- **Added test coverage**: Created `TestListFlags_WithXEnvironmentHeader` to verify the fix works correctly
This change maintains full backward compatibility while adding the missing X-Environment header support to the v1 ListFlags endpoint.
=> fix: respect X-Environment header in v1 ListFlags endpoint

go.work.sum, internal/coss/storage/environments/git/azure/azure.go, internal/coss/storage/environments/git/gitea/gitea.go, internal/coss/storage/environments/git/github/github.go, internal/coss/storage/environments/git/gitlab/gitlab.go, internal/coss/storage/environments/git/url.go, internal/coss/storage/environments/git/url_test.go, internal/storage/environments/environments.go
- refactor how git urls are handled and cast to azureURL type for azure to get project
- cleanup environment factory scm creation so each scm gets its own method for clarity
- make scm implementations consistent with timestamps, logging, and sorting
=> V2 scm cleanup

internal/coss/license/license.go, internal/coss/license/license_test.go
This PR refactors the license manager implementation to address several issues identified in PR #4481 code review comments and improve overall code quality and maintainability.
- Eliminated the unnecessary global `keygenValidator` function and variable that added complexity without benefit
- Replaced with direct instance method `validateLicense` on `ManagerImpl` for cleaner architecture
- Added proper nil checks in all `keygenLicenseWrapper` methods (`Activate`, `Deactivate`, `GetExpiry`)
- Prevents runtime panics when the wrapped license is nil
- Removed the problematic re-validation step after license activation
- The activated license is now used directly, improving performance and reducing complexity
- Created `setOSSProduct()` helper to eliminate code duplication across multiple …
=> refactor(license): simplify license manager and fix potential panics

cmd/flipt/main.go, internal/coss/license/license.go
Fixes timeout issues during license deactivation on shutdown that were causing "context deadline exceeded" errors when attempting to deactivate Keygen licenses.
```
^C2025-07-23T00:16:57Z  INFO    shutting down...
2025-07-23T00:16:57Z    INFO    shutting down HTTP server...    {"server": "http"}
2025-07-23T00:16:57Z    INFO    shutting down GRPC server...    {"server": "grpc"}
2025-07-23T00:16:57Z    WARN    failed to deactivate license    {"error": "Delete \"https://api.keygen.sh/v1/accounts/****/machines/****\": DELETE https://api.keygen.sh/v1/accounts/****/machines/**** giving up after 1 attempt(s): context deadline exceeded"}
```
- **Modified `internal/coss/license/license.go`**: 
- Added 10-second timeout to retryable HTTP client for Keygen API calls
- Reduced retry attempts from 5 …
=> fix(license): resolve timeout issues during license deactivation on shutdown

cmd/flipt/main.go, config/flipt.schema.cue, config/flipt.schema.json, internal/config/config.go, internal/config/config_test.go, internal/config/license.go, internal/config/testdata/license/invalid_file_no_key.yml, internal/config/testdata/license/invalid_file_not_found.yml, internal/config/testdata/license/valid_with_key_and_file.yml, internal/config/testdata/license/valid_with_key_only.yml, internal/coss/license/license.go, internal/coss/license/license_test.go
This PR implements offline license validation support alongside the existing online validation, enabling Flipt to operate in air-gapped environments or deployments where direct API access to Keygen is not available.
- **Dual Validation Modes**: Support both online (Keygen API) and offline (local file) license validation
- **Automatic Detection**: License type determined by configuration (online = key only, offline = key + file)
- **File-based Validation**: New `validateOffline()` method using Keygen's cryptographic validation
- **Enhanced Configuration**: Added `file` field to `LicenseConfig` for offline license file paths
- **NewManager()**: Now accepts `*config.LicenseConfig` instead of raw license key string
- **Improved Error Handling**: Better validation and error messages for both …
=> feat(license): add support for offline license validation

.github/workflows/integration-test.yml, .github/workflows/test.yml, build/internal/flipt.go, build/internal/ui.go, build/main.go, build/testing/integration.go, codecov.yml
This PR fixes integration test coverage collection that was previously broken and consolidates the Dagger build system to eliminate code duplication between cache and non-cache build paths.
**Problem**: Coverage data was not being collected from integration tests due to issues with Dagger cache volume exports and the new Go 1.20+ binary coverage format.
**Solution**:
- Fixed coverage data export by copying from cache volumes to regular directories before exporting (Dagger limitation workaround)
- Added proper coverage directory permissions for the `flipt` user
- Ensured binaries are built with `-cover -coverpkg=./...` flags consistently
- Added Go coverage data processing in CI to convert binary format to text format for Codecov
**Problem**: Duplicate code between `Build`/`BuildWithCache` …
=> feat: fix integration test coverage collection and consolidate Dagger build functions

.github/workflows/integration-test.yml
This PR optimizes the UI integration tests to use cached Flipt images from the build-cache job, bringing them in line with how other integration tests work.
- Modified `.github/workflows/integration-test.yml` to make UI tests depend on the `build-cache` job
- Added container registry login step to pull cached images
- Updated Dagger command to use the `--cached-image` parameter
- **Performance**: Should  reduces UI test execution time by ~50%
- **Consistency**: UI tests now use the same caching strategy as other integration tests
=> feat: optimize UI integration tests with cached Flipt images

.github/workflows/integration-test.yml
Fixes integration test workflow failures for PRs from forks by skipping GHCR cache operations.
Fork PRs were failing because they don't have permissions to push to `ghcr.io`.
- Skip `build-cache` job for fork PRs (detected via `github.event.pull_request.head.repo.full_name`)
- Run tests without `--cached-image` flag when cache is unavailable
- Maintain cache optimization for regular contributors
Re: #4522
=> fix: allow integration tests to run for PRs from forks

internal/server/flag.go, internal/server/flag_test.go
I'm not sure whether this is intentional or a bug, but `ListFlags` may not return all attributes for a flag. `ListFlags` is used by server sdks and `flipt evaluate` command.
=> fix: include type and enabled flag attributes for v1 ListFlags api call

config/flipt.schema.cue, config/flipt.schema.json, internal/config/config.go, internal/config/cors.go, internal/storage/environments/environments_test.go
Test fixes from #4563
Add `X-Flipt-Accept-Server-Version` to default allowed cors headers because its sent by client sdks still
=> fix: rm hanging test; add x-flipt-accept-server-version to default cors headers

.github/renovate.json5
explore switching to renovate to support both main and v2 branches for dep updates https://github.com/renovatebot/renovate
=> chore: Add renovate

core/validation/testdata/valid_zero_values.yaml, core/validation/validate_test.go, internal/ext/common.go, internal/ext/common_test.go
Fixes validation errors when using rollout value of 0 in variant flag distributions and percentage value of 0 in boolean flag threshold rollouts.
When updating a variant flag with a distribution rollout value of 0, the operation fails with a CUE validation error: `incomplete value >=0 & <=100`. This occurs because the `omitempty` tag on the `Rollout` field in `Distribution` and `Percentage` field in `ThresholdRule` causes zero values to be omitted during YAML serialization, leading to validation failure.
- **Modified `internal/ext/common.go`**: Removed `omitempty` tags from:
- `Distribution.Rollout` field 
- `ThresholdRule.Percentage` field
- **Added `internal/ext/common_test.go`**: Comprehensive tests for YAML and JSON serialization with zero values
- **Added …
=> fix: allow rollout and percentage zero values in YAML serialization

.all-contributorsrc
Adds @rohitnarayan as a contributor for code.
This was requested by erka [in this comment](https://github.com/flipt-io/flipt/pull/4673#issuecomment-3255696943)
=> docs: add rohitnarayan as a contributor for code

.github/workflows/nightly.yml, .goreleaser.nightly.yml, README.md
Simplifies the nightly build versioning to avoid confusion when determining the latest v2 tag.
The nightly GitHub Action was incorrectly detecting `v2.1.0` as the latest tag instead of `v2.1.2`. This happened because:
- The `v2.1.1` and `v2.1.2` tags were created on the `release/2.1` branch
- The nightly workflow checks out the `v2` branch
- GoReleaser's `git describe` only finds tags that are ancestors of the current HEAD
This caused nightly builds to create confusing versions like `v2.1.1-nightly` when we already had `v2.1.2` released.
Use a static `v2-nightly` version for all nightly builds from the v2 branch. This:
- Removes the need to determine the "latest" tag
- Avoids confusion when tags are created on different branches
- Provides a consistent, predictable version for nightly …
=> fix: use static v2-nightly version for nightly builds

.github/prompts/release.md
Fixes the issue where release announcements were reading the CHANGELOG.md from the wrong commit, resulting in incorrect or missing release notes.
- **Modified `.github/prompts/release.md`**: Updated the AI prompt to explicitly read CHANGELOG.md from the tagged commit using `git show {{.Tag}}:CHANGELOG.md` instead of reading from the current working directory
The previous implementation (from PR #4757) was reading the CHANGELOG.md from the current branch state during the release process. This caused issues when:
1. The CHANGELOG.md was updated after creating the release tag
2. The release workflow ran from a different branch state than the tagged commit
The AI prompt now explicitly instructs to read the CHANGELOG.md content from the specific Git tag being released, ensuring the release …
=> fix: read CHANGELOG.md from tagged commit during release

build/main.go, go.work.sum, internal/server/environments/storage.go, internal/storage/environments/environments.go, internal/storage/environments/git/store.go, internal/storage/environments/git/store_test.go, internal/storage/git/repository.go
Fixes a customer-reported bug where deleted Git branches persist in the Flipt Pro UI after being merged and deleted from the repository.
The bug had two components:
1. **Missing pruning on fetch**: When fetching from remote, Git was not configured to prune (remove) deleted remote tracking branches. This meant that when a branch was deleted upstream, the local ref `refs/remotes/origin/flipt/env/branch` would persist indefinitely.
2. **No cleanup in RefreshEnvironment**: The `RefreshEnvironment` method only added new branches and updated existing ones, but never removed branches that had been deleted from Git.
Added `Prune: true` to `FetchOptions` in the Repository's `Fetch` method. This ensures that deleted remote branches are removed from local tracking refs, matching the behavior of `git …
=> fix(environments): remove deleted branches from UI when synced from Git

.github/workflows/contributing.yml
This PR adds a new Contributing workflow that automatically comments on pull requests when the DCO (Developer Certificate of Origin) check fails, providing clear instructions to contributors on how to sign off their commits.
- **Added `.github/workflows/contributing.yml`**: New workflow that monitors DCO check failures and posts helpful comments
The workflow:
1. Triggers when a check suite completes with a failure
2. Identifies if the failed check is the DCO check
3. Finds the associated pull request
4. Posts an automated comment that:
- Mentions the contributor by their GitHub username
- Explains what went wrong
- Provides step-by-step instructions for signing off commits (both new and existing)
- Includes a link to the failed DCO check
- Only comments once per PR to avoid spam
This …
=> feat(ci): add automated DCO check comment workflow

.github/workflows/contributing.yml
Fixes YAML syntax error on line 121 in the Contributing workflow.
- **Fixed **: Corrected indentation of the multi-line string in the comment body to ensure proper YAML syntax
The previous commit simplified the DCO comment but introduced a YAML syntax error due to incorrect indentation of the template literal content. This PR fixes that indentation issue.
=> fix(ci): correct YAML indentation in comment body

internal/server/analytics/sink.go, internal/server/analytics/sink_test.go, internal/server/evaluation/evaluation.go, internal/server/evaluation/ofrep_bridge.go, internal/server/tracing/attributes.go, internal/server/tracing/attributes_test.go
This pull request refactors how OpenTelemetry tracing attributes are named and handled for flag evaluation events, aligning them with a more consistent and descriptive naming convention. It also introduces explicit transformation functions for evaluation reasons, ensures correct flag type handling, and updates related tests accordingly.
The event name isn't well-defined and is subject to change at the moment. I followed the same style that OpenFeature uses. I also created a discussion about this issue in the `opentelemetry-demo` repo, since the project currently uses different styles across its services. I hope to get some guidance on this topic.
I've removed the code that added extra `feature_flag.*` attributes to the span in favor of using a span event. If there are multiple evaluations …
=> refactor(otel): align event and attribute names with OTEL spec

.github/workflows/contributors.yml
This pull request updates the workflow in `.github/workflows/contributors.yml` to refine when the Contributor Assistant runs, making the automation more targeted and reliable.
Workflow trigger improvements:
* The workflow will now only run on pull request events when a PR is opened, instead of also running on synchronize or reopened events.
Reliability and correctness fixes:
* The conditional for running the job on DCO check failures now ensures that the failed check is actually associated with a pull request, preventing unnecessary or erroneous workflow runs.
=> chore: reduce how often contributor workflow runs

build/internal/flipt.go
Updates the Dagger base image build process to work without `go.work` and `go.work.sum` files, which were removed from version control as they are meant for local development only.
- **Modified `build/internal/flipt.go`**: 
- Removed parsing of `go.work` workspace files
- Now directly mounts root `go.mod` and `go.sum` 
- Explicitly mounts submodule dependency files based on `replace` directives
- Removed unused `golang.org/x/mod/modfile` import
- Supports v2 branch with 6 submodules (core, errors, rpc/flipt, rpc/v2/environments, rpc/v2/evaluation, sdk/go)
This change maintains full compatibility with the existing build process. The Dagger build now uses the `replace` directives in `go.mod` as the source of truth for which submodule dependency files to mount, rather than parsing workspace …
=> fix(build): update Dagger build to work without go.work files

.github/workflows/integration-test.yml, build/go.work.container, build/internal/flipt.go, build/main.go
Replaces the dynamic go.work file generation in the Dagger build container with a static `build/go.work.container` file that gets copied during the build process.
- **Added `build/go.work.container`**: Static workspace file listing all Go modules
- **Modified `build/internal/flipt.go`**: Replaced `WithNewFile` with `WithFile` to copy the static file
- **Version controlled**: The workspace configuration is now explicitly tracked
- **Simpler code**: No multi-line string literals in Go code
- **Easier maintenance**: Updating the module list is more straightforward
- **Better visibility**: Developers can see exactly what modules are in the container workspace
This is a refactor that maintains the same functionality - tests still work the same way, but the implementation is cleaner.
The …
=> refactor(build): use static go.work.container file instead of dynamic generation

.github/workflows/release.yml
=> chore: bump goreleaser to latest version on v2

internal/server/flag.go, internal/server/flag_test.go
This PR updates the `ListFlags` API to include the `Metadata` field in the returned `Flag` objects.
Previously, the `ListFlags` API did not include metadata for flags, which made it inconsistent with other endpoints and limited clients’ ability to fully understand flag context in bulk retrievals.
This change allows clients to access metadata for each flag without needing to fetch flags individually.
- Updated the `ListFlags` server implementation (`server/flag.go`) to populate the `Metadata` field in each `flipt.Flag` returned.
- The metadata is pulled directly from the `flag.Metadata` field retrieved from storage.
Example response:
```json
{
"flags": [
{
"key": "example-flag",
"name": "Example Flag",
"description": "A test flag",
"enabled": true,
"metadata": {
"team": "growth",
"owner": …
```
=> Add `Metadata` field to `ListFlags` API response
